### ISSUE TITLE
Feature: `view.draw_image`

### ISSUE THREAD

**Issue by jiminy-billy-bob** [SketchUp/api-issue-tracker#1]
Adding a method to draw images on a View object in 3D space, similar to what we can see when editing the position of a texture.

It would take 3 parameters:
- The coordinates of 4 points which will be the four corners of the image (the order of the points define the orientation of the image)
- An ImageRep object
- Optionally an opacity value.

`View#draw_image(point_list, image_rep, opacity = 1)`

_FR-0083 on Centercode SU2018_

**Comment by thomthom** [comment]
Logged as SU-38301

**Comment by DanRathbun** [comment]
What about UV coords of internal image to map to the 2d points ?

I would also think it easier to pass coords as an array of 4 values.
