### ISSUE TITLE
Get the active Ruby tool

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#10]
Currently there are cases when you need to monkey patch the Ruby API to achieve your goals. Aerilius's LaunchUp does this to intercept menus items added by other plugins so users can search for them. My own Eneroth Tool Memory does this to get a reference to other extension's Ruby Tools so they can later be re-activated.

Here's how I currently intercept Sketchup::Model#select_tool:

```ruby
class Sketchup::Model
  unless defined?(my_own_unique_reference_to_original_select_tool)
    alias_method :my_own_unique_reference_to_original_select_tool, :select_tool
    private :my_own_unique_reference_to_original_select_tool

    def select_tool(*args)
      # Do whatever you need the intercepted value for here...
      UI.messagebox("The tool #{args.first.class.name} is being activated.")

      # Call the original method.
      my_own_unique_reference_to_original_select_tool(*args)
    end
  end
end
```
To avoid this ugly monkey patching it would be very useful the API native had support for this.

The specific case with intercepting Tool activation could be solved if a ToolObserver could be called with a reference to the actual Ruby object activated as  a tool.

The general problem is harder to solve. Maybe there could be a whole bunch of new observers for various different cases. Or maybe there could be a very general MethodObserver that could be attached to any Ruby methods to intercept it being called.

**Comment by thomthom** [comment]
Logged as SU-38306
