### ISSUE TITLE
[HtmlDialog] Again, visual lag at display of a dialog (SU2024.0.594 - Windows only)

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#1001]
Something has changed this latest update of SU2024, in the startup sequence of the HtmlDialog.

Actually, the dialog appears blank at the onload() event and then is rendered.

For simple dialogs where nothing special is done during the load() event, the effect is barely noticeable.

For advanced dialogs where the titlebar decoration is modified, the flickering is perceivable. 

**This was not the case in the previous version of SU2024**.

https://github.com/user-attachments/assets/3d63c960-154d-4625-8fc7-2b29a93525b7

**Comment by ChrisFullmer** [comment]
Thanks for the feedback on this. We see the flickering and have not been able to reproduce this using Ruby API HTMLDialogs. We closing this as won't fix.
