### ISSUE TITLE
Sketchup::Model#save() also writes a 0 length SKB file

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#104]
#### SketchUp Ruby API Issue

1. SketchUp/LayOut Version: 2016
2. OS Platform: Win 7 SP1

#### Sketchup::Model#save() also writes a 0 length SKB file

**Description:** The API save operation (under SU2016) also creates a 0 length SKB file of no worth.

**Expected Result:** Only the SKP file was expected. (What worth is a 0 length backup anyway?)

```ruby
filepath = UI.savepanel("Save Test",ENV['HOME'],"test_save.skp")
Sketchup.active_model.save(File.join(filepath))
```

**Comment by DanRathbun** [comment]
Okay so this would be a note in the documentation I suppose.

**Comment by DanRathbun** [comment]
Do you want to close this or switch it to a documentation issue ?

**Comment by thomthom** [comment]
Logged as SU-40182
