### ISSUE TITLE
SUModelGetImageDefinitions / SUModelGetNumImageDefinitions

### ISSUE THREAD

**Issue by prachtan** [SketchUp/api-issue-tracker#11]
Reading and parsing Image instance from skp-file is unnecessarily complicated.

It would be very useful to be able to read all ImageDefinitions from model during process of reading/parsing skp file, as well as getting all materials - even _image-type-materials_ - in `SUModelGetMaterials `in standalone importer. 

It can simplify the process of loading data, by using exactly same way to exporting textures/geometries like in case of group or component-instances.

This is also inconsistency between C-API and RubyAPI, because `Sketchup.active_model.definitions` returns all definitions _(even those for Images)_ but it's impossible to get it _(straight)_ from Model in C-API.

There is also issue in RubyAPI:

`Sketchup.active_model.materials.size() != Sketchup.active_model.materials.to_a().size()`

if there are _image-type_ materials in model, and in case of c-api it's impossible to get image-type materials in any way.

**Comment by thomthom** [comment]
@prachtan - for the Ruby issues, can you create a separate issue for that please.

**Comment by thomthom** [comment]
Logged as SU-38307
