### ISSUE TITLE
Ruby Geom::Point3d + other Geom::Point3d returns an error

### ISSUE THREAD

**Issue by kengey** [SketchUp/api-issue-tracker#114]
the ruby documentation states that it should be possible to add a Point3d object to another Point3d object:
[https://ruby.sketchup.com/Geom/Point3d.html#%2B-instance_method](https://ruby.sketchup.com/Geom/Point3d.html#%2B-instance_method)

> The '+' operator is a fast way to add to the current x, y and z values of a point, or to set the values of a point by adding to other points together.

( also take notice of the typo, it should be: 

> ...set the values of a point by adding **two** other points together.

However, I get an error:

```
a = Geom::Point3d.new([0,0,0])
b = Geom::Point3d.new([1,1,1])
c=a+b

==> Error: #<ArgumentError: Cannot convert argument to Geom::Vector3d>
<main>:in `+'
<main>:in `<main>'
SketchUp:1:in `eval'
```

**Comment by DanRathbun** [comment]
I remember this doc error being discussed in the past. (I wish it would get fixed sometime soon.)

Ken, you can just add an array `[1,1,1]` to `a` to get point `c`, ...
or do `c = a + b.to_a`
