### ISSUE TITLE
Possibility to export actual scene opened in SketchUp (new c sdk api)

### ISSUE THREAD

**Issue by zsacul** [SketchUp/api-issue-tracker#119]
Is there a possibility to export actual state of the scene opened in SketchUp in the new api?
In previous (deprecated) api that was possible by passing ISkpDocument* pointer.
Now it seems we can export only scene saved previously to file, or am I missing something?

Could you please add this possibility before removing deprecated api?

**Comment by thomthom** [comment]
You mean accessing scene properties where the user haven't invoked the Update command on it?

**Comment by zsacul** [comment]
That is exactly as Dan said, we want to get access to the actual scene state without saving it to file (previous api allowed that).

**Comment by jiminy-billy-bob** [comment]
This?

```
SUModelRef GetActiveModel() {
  VALUE sketchup = rb_define_module("Sketchup");
  VALUE model = rb_funcall(sketchup, rb_intern("active_model"), 0);
  VALUE address = rb_funcall(model, rb_intern("skpdoc"), 1, Qtrue);
  return SUModelFromExisting(NUM2SIZET(address));
}
```

**Comment by zsacul** [comment]
> return SUModelFromExisting(NUM2SIZET(address));
Wow, that looks very interesting, is there a way to do same in c++
without using rb_funcall and rb_intern?

I was trying:
model_ = SUModelFromExisting((uintptr_t)ptr);
on skpdoc passed from ruby as void * ptr to c++ dll 
Fiddle::TYPE_VOIDP type of passed pointer on ruby side...

I think the problem is I do not know what NUM2SIZET is doing...

**Comment by thomthom** [comment]
> Wow, that looks very interesting, is there a way to do same in c++ without using rb_funcall and rb_intern?

I don't know much about the old C++ SDK. It was on its way out before I joined the team.

Why are you trying to avoid `rb_funcall` and `rb_intern`? As far as I was aware `model.skpdoc` was the only way to get the model pointer.

> I think the problem is I do not know what `NUM2SIZET` is doing...

This site is very handy to look up Ruby source identifiers: https://webwallet.reddcoin.com/mri/ident

`NUM2SIZET`
https://webwallet.reddcoin.com/mri/source/include/ruby/ruby.h#735

```
model_ = SUModelFromExisting((uintptr_t)ptr);
on skpdoc passed from ruby as void * ptr to c++ dll
Fiddle::TYPE_VOIDP type of passed pointer on ruby side...
```
I'm not sure if I follow what you describe here. Did you try to take the pointer intended for the C++ SDK and pass into the C API?

As jiminy-billy-bob demonstrated, by  passing in `true` to `skpdoc` you get a pointer reference for the C API.

(So was this what you were looking for in the C API? A way to get the live model? Did you mean "scene" as in "model"?)

**Comment by DanRathbun** [comment]
Has anyone looked at the migration document that is distributed with the SDK to see if it needs more lessons added ?

**Comment by zsacul** [comment]
> Why are you trying to avoid rb_funcall and rb_intern? As far as I was aware model.skpdoc was the only way to get the model pointer.

I am trying not to add new dependencies.

> Has anyone looked at the migration document that is distributed with the SDK to see if it needs more lessons added ?

I did but is seems to be a bit outdated, it says: "The model can be loaded from a file or created from scratch in memory." Now it can :).

> I'm not sure if I follow what you describe here. Did you try to take the pointer intended for the C++ SDK and pass into the C API?

OMG I just realized skpdoc is a function, when I pass true I got valid pointer and it started to work!
**Thank you all very, very much!**

Now I am in the middle of movement into new API, I will let you know if it works and if anything is missing. As far it looks a way better and probably will allow to write texture cache (finally).

**Comment by thomthom** [comment]
> I am trying not to add new dependencies.

But weren't you already using `model.skpdoc` to obtain the model pointer for the C++ SDK you were using? If you did, then you'd already be using Ruby, and `rb_funcall` etc is part of that.

Or were you using some other means?

**Comment by thomthom** [comment]
> I did but is seems to be a bit outdated, it says: "The model can be loaded from a file or created from scratch in memory." Now it can :).

Yea, we haven't really made `model.skpdoc` official. We'll probably do that next release. Or maybe even a pure C function to obtain the C API model pointer. (Though we'll leave `model.skpdoc` in for compatibility.)

**Comment by zsacul** [comment]
> But weren't you already using model.skpdoc to obtain the model pointer for the C++ SDK you were using? If you did, then you'd already be using Ruby, and rb_funcall etc is part of that.

I am not using Ruby C Extension at all, just passing model.skpdoc(true) on ruby plugin side, and getting void* on c++ dll.

**Comment by thomthom** [comment]
Aah! Gotcha. Using Ruby'd Fiddle to make the bridge to your C++ dll. Didn't think of that.
