### ISSUE TITLE
Include content from Tool::draw() to view.write_image()

### ISSUE THREAD

**Issue by SoapSkinBubble** [SketchUp/api-issue-tracker#124]
Please include the following in SketchUp

Description: For extensions which show specific features without modifying the actual model by using the Tool::draw() method, it is a highly needed feature to export this view as a rendered picture including this added OpenGL content. We would recommend an additional option flag in the View::write_image() method, which enables the user to choose to do this.

Usecase examples:
Postprocessing, Simulation, Analysis, Data views

![screen](https://user-images.githubusercontent.com/5636213/45484694-46a32400-b755-11e8-9fff-89402b300554.png)

**Comment by DanRathbun** [comment]
Is this accomplished with the new `:source => :framebuffer` argument addition for `Sketchup::View#write_image` ?

And how can his work since v7, but be marked as fixed in 19.2 ?

**Comment by thomthom** [comment]
> Is this accomplished with the new :source => :framebuffer argument addition for Sketchup::View#write_image ?

> And how can his work since v7, but be marked as fixed in 19.2 ?
It was in the SU2019.2 project because we fixed the docs. We run a script to close out all issues that mark it with the recent fix version. For documentation issues that can lead to situations like this.
