### ISSUE TITLE
view.write_image doesn't raise error upon too many arguments

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#138]
http://ruby.sketchup.com/Sketchup/View.html#write_image-instance_method

API user reported this (assuming the last boolean was transparency.)

```ruby
model = Sketchup.active_model
view = model.active_view
view.write_image "C:/temp/write_image.png", 640, 480, false, 0.9, true
```

**Comment by thomthom** [comment]
Logged as SU-41151

**Comment by DanRathbun** [comment]
Does Ruby generally raise exceptions for extra arguments ?

**Comment by MSP-Greg** [comment]
Yes.  Normally, msg like
```
: wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by DanRathbun** [comment]
I seem to recall many of the API methods do not do this. Likely those with variable argument counts (ie, method overrides.) Probably those that collect the args into an array and pass them over to the C-side, and are from the early API releases.

**Comment by thomthom** [comment]
Yea, Dan is spot on,, there are several places where SU doesn't raise `ArgumentErrors` over too many arguments.

Typically this is the case when the method have optional arguments.

https://silverhammermba.github.io/emberb/c/#methods

When there's a fixed set of arguments the C implementation is straight forward:

```c
/* normal mandatory args (can have up to 16 args not counting self) */
VALUE my_method(VALUE self, VALUE arg1, VALUE arg2)
{
	/* ... */
}
```
```
void init_my_class() {
  cFoo = rb_define_class("Foo", rb_cObject);
  rb_define_method(cFoo, "my_method", my_method, 2);
}
```

Note that `self` is always present, the signature for a method with no arguments are:

```c
VALUE my_method(VALUE self)
{
	/* ... */
}
```
```c
void init_my_class() {
  cFoo = rb_define_class("Foo", rb_cObject);
  rb_define_method(cFoo, "my_method", my_method, 0);
}
```

In the cases of fixed set of arguments Ruby takes care of the checking of number of arguments automatically.

But when there is a variable set of arguments they are defined as such:

```c
void init_my_class() {
  cFoo = rb_define_class("Foo", rb_cObject);
  rb_define_method(cFoo, "my_method", my_method, -1);
}
```

The implementing method is then:
```c
VALUE my_method(int argc, VALUE* argv, VALUE self)
{
	/* ... */
}
```

Some of the older code then keeps checking `argc` like this:

```c
if (argc > 2) {
  VALUE arg3 = argv[2];
}
```

Normally there will be an check to see if there are too many. But some times it's left out.

I'm not sure if the method was there back in the early days, but now there is `rb_scan_args` which
https://silverhammermba.github.io/emberb/c/#parsing-arguments

This ensures optional arguments, overloads, blocks etc are checked and handled consistently. And that is what newer API code uses. We've been cleaning up as we go along - whenever possible. If the manual checking raised an error of the "wrong" type then we lean towards not changing it, in case someone has a catch that relies on it.

One could argue the same in the case of adding new errors that wasn't there. But in this case we've had reports saying the method wasn't working - where in reality they assumed it took more arguments that it really did. We think it's less likely that API users will call a method with too many arguments and still get expected correct result.

**Comment by DanRathbun** [comment]
... so open an issue when these are found?

**Comment by thomthom** [comment]
Sure. They won't be high priority, but they are quick and easy to fix. We try to grab a handful of these types of issues now and then.
