### ISSUE TITLE
Sketchup::ComponentInstance#make_unique does not return Boolean

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#154]
**`Sketchup::ComponentInstance#make_unique`** does not return Boolean as the doc say.

http://ruby.sketchup.com/Sketchup/ComponentInstance.html#make_unique-instance_method

It is unclear whether a reference to the new instance is returned or not. 

(Group#make_unique clearly says it returns the newly unique instance.)
http://ruby.sketchup.com/Sketchup/Group.html#make_unique-instance_method

**Comment by DanRathbun** [comment]
> **Dan said** ...
... also neither say exactly what happens when uniquing is **not** needed.
Ie, there is only one instance in the model.
>
>Is the call ignored, and the same old reference to the original receiver returned ?

This has not been addressed in the doc update.

**Comment by thomthom** [comment]
Sorry, missed the additional comment. I logged a new issue to track the remaining documentation improvements.
