### ISSUE TITLE
Clarify Geom.linear_combination

### ISSUE THREAD

**Issue by jonsketch** [SketchUp/api-issue-tracker#164]
Internal request: SU-29270

Clarify the use of _percentage_ within Geom.linear_combination

**Comment by Eneroth3** [comment]
Has this already been done since this issue was logged? To me the docs looks quite clear.

I can't find any use involving a percentage though. Is the request to document `weight1` as `percentage` and `weight2` as `1 - percentage` in an example?

**Comment by thomthom** [comment]
Yea, I'm not sure what this was about. Percentage doesn't make sense.

**Comment by thomthom** [comment]
Ah, there was an edit in 2017 that removed "percentage". This is fixed a long time ago.

**Comment by DanRathbun** [comment]
Well the method still could use clarification. I never understood how it works.
In testing, the Float value for `weight1` has no bearing upon the output at all that I can determine.
Set `weight1` to `0.0` or `1,234.0` and it doesn't matter. It is all the value of `weight2` that determines the output along the line through the two points.

Unless I'm not seeing the obvious.

**Comment by thomthom** [comment]
Maybe we should add some examples that shows input and output.

Both weights do have an effect. What this method do is: `(pt1 * weight1) + (pt2 * weight2)`.

So both inputs are added together after having a weight applied to them.

```
Geom.linear_combination(2.0, [1, 2, 3], 1.0, [0, 0, 0]).to_a
[2.0, 4.0, 6.0]

Geom.linear_combination(2.0, [1, 2, 3], 1.0, [1, 1, 1]).to_a
[3.0, 5.0, 7.0]

Geom.linear_combination(0.5, [1, 2, 3], 1.0, [0, 0, 0]).to_a
[0.5, 1.0, 1.5]
```

**Comment by DanRathbun** [comment]
>  What this method do is: `(pt1 * weight1) + (pt2 * weight2)`

Oh yea, put that in the docs please! The examples **do** help.

I now understand that I'd likely not have a need for this method. 
It doesn't really do what I thought I'd use it for, which is to get a point along line between two points. 

So say I want a point midway between 2 points .. (`[2,2,2]` and `[10,10,10]`). I'd think that ...
```ruby
Geom.linear_combination(1.0, [2, 2, 2], 0.5, [10, 10, 10])
#=> (7", 7", 7")
```
... would give me what I'd want (`[6,6,6]`). **But it doesn't.**

So I'd end up using [`Geom::Point3d#offset`](https://ruby.sketchup.com/Geom/Point3d.html#offset-instance_method) ...
```ruby
mid_pt = pt1.offset( pt1.vector_to(pt2), pt1.distance(pt2) * 0.5 )
```
... which is far more straightforward.

**Comment by Eneroth3** [comment]
You could set the first param to 0.5 if you want that to be the weight of the point.

```ruby
Geom.linear_combination(0.5, [2, 2, 2], 0.5, [10, 10, 10])
#=> (6", 6", 6")
```

**Comment by thomthom** [comment]
> It doesn't really do what I thought I'd use it for, which is to get a point along line between two points.

I can do that;

```
module Example

Geom.linear_combination(0.5, points.first, 0.5, points.last)
```

**Comment by thomthom** [comment]
It can do that, but you need to ensure the total of the two weights equal to `1.0`

```
module Example
  # @param [Geom::Point3d] pt1
  # @param [Geom::Point3d] pt2
  # @param [Float] offset  Interpolation offset between 0.0 and 1.0 where 0.0 is `pt1` and 1.0 is pt2
  # @return [Geom::Point3d]
  def self.point_between(pt1, pt2, offset)
   raise ArgumentError if offset < 0.0 || offset > 1.0 # TODO: Should compare with tolerance to account for floating point noise
    w1 = offset
    w2 = 1.0 - w1
    Geom.linear_combination(w1, pt1 ,w2, pt2)
  end
end
```

I'm guessing that `Geom.linear_combination` was added to the API as it is more flexible than just a simple blend between two points/vectors. But I agree that examples of common scenarios of usage is good to have included.
