### ISSUE TITLE
Ruby Console fails with some non-ascii characters ("Š")

### ISSUE THREAD

**Issue by Nazz78** [SketchUp/api-issue-tracker#17]
1. SketchUp/LayOut Version: SU 2018
2. OS Platform: Windows

When using "Š" character, SketchUp Ruby fails flat.

```ruby
puts "ABCŠ "
# Error: #<SyntaxError: <main>: invalid multibyte char (UTF-8)
# <main>: unterminated string meets end of file>
# SketchUp:1:in `eval'

print "ABCŠ123456"
# Error: SketchUp:1:in `eval'
```

Reported also in [centercode SU-0396](https://sketchup.centercode.com/project/feedback/view.html?cap=9318978b6fb44764b3ee0a485bba96cb&uf=6edc588980364520a025781aed5e8d40&new=1&ifps=-898&f=%7B615e224c-56b4-4a52-a29e-672d637b1000%7D&t=0&fti=2&d=%7B96d472ce-b2ca-4d23-94f8-699d81efe8fa%7D).

**Comment by thomthom** [comment]
Can you attach a sample file please? I'm suspecting that the file isn't actually saved in UTF-8.

**Comment by Nazz78** [comment]
There is no file, the error pops up if you try to run it in Ruby Console. But it doesn't in SU 2017.

**Comment by DanRathbun** [comment]
There is also no problem with the example under SU 2016.

@Nazz78, try the following at the console in both SU2017 and SU2018 & reports results (in a **```text** block.)
```ruby
puts "\n"<<'Sketchup version  : ' << Sketchup.version
puts 'External encoding : ' << Encoding.default_external.inspect
puts 'Internal encoding : ' << Encoding.default_internal.inspect
```
As an example for SU2016, I get:
```text
Sketchup version  : 16.1.1449
External encoding : #<Encoding:UTF-8>
Internal encoding : nil
```

**Comment by Nazz78** [comment]
Hi Dan, these are my results (running on Windows 10)
```
Sketchup version  : 17.2.2555
External encoding : #<Encoding:UTF-8>
Internal encoding : nil
```

```
Sketchup version  : 18.0.16975
External encoding : #<Encoding:UTF-8>
Internal encoding : nil
```

**Comment by DanRathbun** [comment]
Okay, thanks, ... looks the same as always.

**(1a)** For SU2018, did you cut and paste the failing text from some other application window ?
**(1b)**  ... or did you type it directly into the console using the keyboard ?

What do you get when you type these at the console(s) ?
```ruby
__ENCODING__
```
```ruby
Encoding.find("filesystem")
```
```ruby
Encoding.find("locale")
```
?

-----

I'm also wondering if the `%x` execute strings are broken again ?
```ruby
puts %x{dir}.gsub("\n","\n\r")
```
... should output the current working directory listing in the Ruby Console.

?

**Comment by Nazz78** [comment]
I get an error in any case, if I input it manually or if I copy/paste it.

In both, SU 17 and 18 I get the same result:
```
__ENCODING__
Encoding.find("filesystem")
Encoding.find("locale")
=> Windows-1252
```
Executing ```puts %x{dir}.gsub("\n","\n\r")``` just blinks the command prompt and that's it.

**Comment by DanRathbun** [comment]
> In both, SU 17 and 18 I get the same result:

Okay, there is a difference from SU2016 where **`__ENCODING__`** returns **`"UTF-8"`** just after launch with only the **`"Tools"`** folder and the default stuff from **`"RubyStdLib"`** loaded.

And the **`%x`** (backtick) execute strings work fine. 
(I can't believe they broke it AGAIN. It was broke for SU2014 I think.)

**Comment by thomthom** [comment]
I can reproduce `#<SyntaxError: <main>: invalid multibyte char (UTF-8)` on my machine as well when I use Norwegian characters in the Ruby Console. I'm surprised no one (not even I) ran into this before.

**Comment by Nazz78** [comment]
I guess it's because if ran in loaded script, this problem doesn't seem to appear!?

**Comment by DanRathbun** [comment]
> I get an error in any case, if I input it manually or if I copy/paste it.

I think the console gets it's input from STDIN.
What do you get at the console typing:
```ruby
STDIN.external_encoding
```
?

If you get "Windows-1252", you could try ...
```ruby
STDIN.set_encoding("UTF-8")
```
and try again.

**Comment by Nazz78** [comment]
No luck, it's UTF-8 already... :-)

**Comment by DanRathbun** [comment]
## **Here is an Encoding Report generator script.**

You drop the `"enc.rb"` file in the default **HOME** folder ("~/Documents") ,,,
and then from SketchUp's console type ...
```ruby
load 'enc.rb'
```
[enc.zip](https://github.com/SketchUp/api-issue-tracker/files/1582854/enc.zip)

It shows the difference when **`Encoding.default_internal`** is not set (**`nil`**) and set to `"UTF-8"`, as well as setting **`STDIN`** encoding to `"UTF-8"` in the 2nd pass.

@thomthom, It should be obvious that **`Encoding.default_internal`** should be set when the Ruby interpreter is FIRST loaded, so that [**`String#encode()`**](http://ruby-doc.org/core-2.0.0/String.html#method-i-encode) can be used to convert to internal (script) encoding, **INSTEAD** of doing hacks like, at top of ...
https://github.com/SketchUp/htmldialog-inputbox/blob/master/src/input_box.rb
```ruby
  file = __FILE__.dup
  # Account for Ruby encoding bug under Windows.
  file.force_encoding('UTF-8') if file.respond_to?(:force_encoding)
```
**INSTEAD** you just do ...
```ruby
  file = __FILE__.encode
```
P.S. it is NOT necessary to do **`dup`** as each time **`__FILE__`** is called it returns a NEW String instance object.
```ruby
__FILE__.__id__
#=> 90762440
__FILE__.__id__
#=> 90761820
__FILE__.__id__
#=> 90761260
__FILE__.__id__ == __FILE__.__id__
#=> false
__FILE__.equal?( __FILE__ )
#=> false
```

**Comment by DanRathbun** [comment]
> No luck, it's UTF-8 already... :-)

DARN. SO much for the easy fix ... :sadface:

**Comment by thomthom** [comment]
Logged as SU-38424

**Comment by AntonSynytsia** [comment]
Is this bug still present in SU2018? Because when I paste this into Ruby console, the string is converted into questions marks:

```ruby
str = "Здорово"
# => "?????"
str.encoding
# => "UTF-8"
```
I don't get any issues with this in SU2017.

**Comment by Nazz78** [comment]
@AntonSynytsia - precisely, this is SU 2018 bug.

**Comment by DanRathbun** [comment]
@thomthom Reported in the public Ruby API forums that Unicode path support is again broken in SU2018.

The APPDATA paths and Gem paths are not working. Is this part of the same regression ?

**Comment by Nazz78** [comment]
When testing Modelur with SketchUp 2018, we  found no difference from 2017 in this respect. But we didn't get into any detailed testing...
