### ISSUE TITLE
Module: Sketchup::Licensing (tutorial link incorrect)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#171]
Module: [`Sketchup::Licensing`](http://ruby.sketchup.com/Sketchup/Licensing.html)

In "Overview" section, 2 line:
> See the **_Licensing Tutorial_** for more details.

The bad link is:
 "`http://ruby.sketchup.com/tutorial_licensing`"

The correct link is: 
"[`https://extensions.sketchup.com/en/developer_center/tutorial_licensing`](https://extensions.sketchup.com/en/developer_center/tutorial_licensing)"

-----

_Ref: public forum post:_ 
https://forums.sketchup.com/t/licensing-tutorial-link-broken-404/37493

**Comment by DanRathbun** [comment]
NOTE: The link was corrected, and is now redirecting to the appropriate folder in the GitHub API Tutorial project.

**Comment by DanRathbun** [comment]
Please **reopen** as this issue was never fixed.

The link in the class docstring for the [`Sketchup::Licensing`](https://ruby.sketchup.com/Sketchup/Licensing.html) module is STILL a bad URL.
It needs to be changed **from:**
> For more details, see: [**Developer Center Licensing Tutorial**](https://extensions.sketchup.com/en/developer_center/tutorial_licensing)

**to:**

> For an example, see the ["Hello License" example](https://github.com/SketchUp/sketchup-ruby-api-tutorials/tree/master/examples/99_license) of the [SketchUp Ruby API Tutorials](https://github.com/SketchUp/sketchup-ruby-api-tutorials) repository.

~

**Comment by Eneroth3** [comment]
This issue appears to have been corrected.
