### ISSUE TITLE
Undocumented behaviour of tool event return value

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#176]
The return value for onKeyDown in the Tool interface on Windows is used by SketchUp to determine whether the event should be stopped or propagate. For instance, a tool using Alt as modifier key must have the return value set to false when pressing Alt to avoid focus being moved to the menu bar.

A typical onKeyDown for a tool using Alt could look like this:

```ruby
def onKeyDown(key, repeat, flags, view)
  // Do stuff here...

  # Prevent default key action in order to stop Alt from changing focus to menu.
  key == VK_ALT
end
```
However this use of the return value isn't mentioned in the documentation. If this is an intended behavior that is expected to work in future SketchUp versions, it would be good if the documentation clearly stated that.

The current behavior is a bit odd, suggesting this may not be intentional. Setting the return value to true prevents the menu bar on Windows from being selected by pressing Alt, and prevents text from being written to the VCB. However it doesn't prevent shortcuts from being used.

Also I have not been able to test this on Mac. Does the behavior differ, and if so how?

**Comment by Eneroth3** [comment]
Here's a simple snippet to test how SketchUp behaves when the return value is true.

```ruby
class TestTool
  
  def onKeyDown(*args)
    true
  end
  
  def enableVCB?
    true
  end
  
end

Sketchup.active_model.select_tool(TestTool.new)
```

**Comment by thomthom** [comment]
Yea, this have been catching me by surprise as well. Especially since Ruby implicitly return last value.

**Comment by Eneroth3** [comment]
I've been thinking about writing a FR for the ability to block shortcuts too, but with the implicit return value a lot of extensions could suddenly break all shortcuts accidentally.

Anyhow, do you have any more info on to what degree the current behavior is intended and safe to rely on?

**Comment by Eneroth3** [comment]
I just noticed that a truthy return value from onKeyDown also prevents onCancel from being called when pressing escape. I think this quirk really needs to be mentioned in the API, as it can be virtually impossible to make a tool reset on Esc without knowing this.
