### ISSUE TITLE
Mouse wheel in Tool interface

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#178]
In many situations it could be useful to have an extension listen to mouse wheel, e.g. to set values or scroll within your own interface (if drawn to the viewport, not a separate window).

There are currently [hacks ](https://github.com/SketchUp/api-issue-tracker/issues/176)to achieve this by using either getExtents or suspend/resume to intercept camera zoom, and then reset the camera before SketchUp has gotten to drawing the view, but it's hard to pull of and makes for unstable and hard to maintain code.

It would be useful with a proper way of listening to the mouse wheel from within a tool, e.g. a onMouseWheel method taking direction, mouse position and flags as parameters. The return value could determine whether SketchUp should zoom as normally or not. For instance scrolling while inside a control drawn to the view could affect that control, while scrolling outside of it would zoom. Or scrolling while holding a modifier key could be interpreted as input to the plugin, while scrolling without holding the key would zoom as normally.

**Comment by DanRathbun** [comment]
```ruby
onMouseWheel( key, flags, x, y, view )
```
... where **`key`** is either `VK_UP`, `VP_DOWN`, (or for mice with horizontal scrolling ... `VK_LEFT`, or `VK_RIGHT`.)

**?**

**Comment by Eneroth3** [comment]
Yes, something like that. I think it makes more sense to call the first parameter direction though, as it isn't a key. New constants with more descriptive names, like SCROLL_UP would also be more readable than re-using the arrow key identifiers.

To take natural scroll into account there could maybe be 4 constants for each axis: 2 that are the absolute direction, and 2 that are "virtual" direction (being swapped when using natural scroll). This way the developer could chose between referencing the absolute direction, or the system dependent direction, based on what makes sense in each case. This would be consistent to how COPY_MODIFIER_KEY and VK_CONTROL are different constants, depending on whether you are referring to the actual Ctrl key or whatever key SketchUp uses for Copy.

I have no experience with natural scroll myself so I'm not sure what the best implementation for this is.

**Comment by Matherone** [comment]
+1. 

A native API method that recognises mouse wheel input would be great. It allows for setting a tool input variable without changing cursor location. 

This would be very handy in cases where geometry does not need to be inferenced. Just one example: growing and shrinking selections of quadded geometry.

We would employ mouse wheel input in several upcoming plugins.

**Comment by thomthom** [comment]
@Matherone - this is now possible with SU2019.2.

We'd love to see what you make of it!

**Comment by Matherone** [comment]
Thank you very much. We will try to incorporate this in an upcoming public extension.
