### ISSUE TITLE
UI::HtmlDialog not playing MP4 video, UI::WebDialog does

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#185]
Reference forum thread: https://forums.sketchup.com/t/ui-htmldialog-not-playing-mp4-video-ui-webdialog-does/83255

> I am trying to play a MP4 video in HTML with [UI::HtmlDialog](http://ruby.sketchup.com/UI/HtmlDialog.html) using the HTML5 standard way to embed it:
> 
>     <video width="1280" height="720" controls>
>       <source src="movie.mp4" type="video/mp4">
>     </video>
> 
> The video is not embedded properly, and I have to convert it to .ogg to make it work. This was working correctly with the deprecated [UI::WebDialog](http://ruby.sketchup.com/UI/WebDialog.html), so I guess there is any problem either with the codecs or with the HTML5 usage.

> yeh,
> 
> CEF in SU v18 loads an empty player for mp4’s…
> 
> drop the mp4 in the zip into Sketchup.temp_dir so that it’s relative to the [not yet created] html, and it won’t play…
> 
> add the .ogv and that will play…
> 
> anyone of you used ffmpeg2theora windows?
> 
> I used brew install ffmpeg2theora on the mac…
> 
> it’s very fast but drops the last few frames on this short clips…

```ruby
dlg = UI::HtmlDialog.new(
	dialog_title:    'local mp4 or ogv?',
	preferences_key: 'com.local.mp4',
	scrollable:       true,
	resizable:        true,
	width:            800,
	height:           450,
	style:            UI::HtmlDialog::STYLE_WINDOW
)

  html = <<-HTML
	<!DOCTYPE html> 
	<html> 
	<body> 
	<video width="400" controls autoplay>
		<source src="pencil.mp4" type="video/mp4" />
		<source src="pencil.ogv" type="video/ogg" />
	</video>
	</body> 
	</html>
	HTML

  dlg.set_html(html)
  dlg.center
  dlg.show
```

[pencil.zip](https://github.com/SketchUp/api-issue-tracker/files/2675809/pencil.zip)

**Comment by taustin73** [comment]
Logged SU-41957

**Comment by DanRathbun** [comment]
Can we have a "wont fix" reason for the record?

**Comment by nickAtSketchUp** [comment]
Trimble Inc. does not have licensing rights for redistributing these video codecs to all our customers
