### ISSUE TITLE
Include CEF versions in API documentation

### ISSUE THREAD

**Issue by Aerilius** [SketchUp/api-issue-tracker#192]
In the context of https://github.com/SketchUp/api-issue-tracker/issues/98 (which is about accessing CEF version through code), all major CEF/Chromium versions used in public SketchUp releases should be listed within the [overview section of HtmlDialog](http://ruby.sketchup.com/UI/HtmlDialog.html).

Reason:
- Since developing UIs for SketchUp makes use of the Web APIs, these are "part" of the SketchUp API and developers need to know which Web API features and versions they are allowed to target.
- Chromium often supports features years before the ECMAScript standard leaves Draft status. If SketchUp 2018 supports a feature, it does make a difference if 2017 didn't support it yet.

Something like:

    SketchUp 2017    Chromium ##.#.####.#   (ECMAScript####)

It should be relatively less effort since it does not require changes to the API itself, only the documentation.

**Comment by DanRathbun** [comment]
FTR, I support this and asked for it in the referenced issue [#98, post 5](https://github.com/SketchUp/api-issue-tracker/issues/98#issuecomment-397466154) ...

> If he checked Chrome docs and found it supported URI embedded credentials up until a certain version, then if **at the simplest, the API docs for UI::HtmlDialog (or even the API release notes) had some mention of a versioning, a person could make a decision.**

**Comment by Eneroth3** [comment]
Logged as SKEXT-2908

@Aerilius, is the minor, path and build number important, or is it the major version with its new features that matter?

**Comment by Aerilius** [comment]
It's not an issue for me, I had just brought it up from the forums at that time.

I'd probably document major and minor (feature) version of a software, not patch and build numbers. With Chrome's fast release schedule, probably major is enough.

**Comment by DanRathbun** [comment]
> @Aerilius  : ... _all major CEF/Chromium versions used in public SketchUp releases should be listed within the [overview section of HtmlDialog](http://ruby.sketchup.com/UI/HtmlDialog.html). ... With Chrome's fast release schedule, probably major is enough._

**This has been achieved**. There is now a table in the class **Overview** section listing CEF major versions since SU2017.0.

However the table is full width of the page and does not look that great. I'd vote to change this to a bulleted list.

_Ex:_
>HtmlDialog uses the following versions of CEF (Chromium Embedded Framework):
> * **SketchUp 2021.1** : CEF 88
> * **SketchUp 2019.0** : CEF 64
> * **SketchUp 2018.0** : CEF 56
> * **SketchUp 2017.0** : CEF 52

The list would take up less space and require less vertical scrolling to get further down the page to the method links.

~

**Comment by Eneroth3** [comment]
Fixed in SketchUp 2021.1.
