### ISSUE TITLE
Sketchup::ComponentInstance#make_unique documentation clarifications

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#197]
https://github.com/SketchUp/api-issue-tracker/issues/154#issuecomment-350517665

> ... also neither say exactly what happens when uniquing is **not** needed.
> Ie, there is only one instance in the model.
> 
> Is the call ignored, and the same old reference to the original receiver returned ?

**Comment by DanRathbun** [comment]
Clarification also applies to `Group#make_unique` which clearly says it returns the newly unique instance.
http://ruby.sketchup.com/Sketchup/Group.html#make_unique-instance_method

... however coders report that the reference does **not** seem to change as the docs **imply**.

It **does** make sense that the reference is reused (or remains the same) as when a unique is done the old reference would be invalid, and when there is only 1 instance, the group is unique by itself and no definition cloning need be done, so the reference is valid even for a no-op.

REF forum topic: https://forums.sketchup.com/t/instancepath-and-make-unique/141626
