### ISSUE TITLE
Document that Sketchup::PickHelper instances are reused

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#198]
Reference:

https://github.com/thomthom/true-bend/issues/24
https://forums.sketchup.com/t/truebend-re-defined-method-for-pick-segment-points/87777/13

`Sketchup::PickHelper` objects are reused per view. `view.pick_helper` does not return a fresh `PickHelper`.
This should be clarified in the documentation along with a note that instances of this class should not be extended or otherwise modified.

**Comment by Eneroth3** [comment]
I'm thinking that rather making a note in the documentation of this method, there could maybe be a more comprehensive document of what objects are safe to extend and which ones are not. This would include all Entity objects (I think) put not points, vectors and transformations returned by the API.

**Comment by thomthom** [comment]
Yea, `Sketchup::Entity` is reused via the object manager we have. All others should be fine - except it turned out that `Sketchup::PickHelper` had its own management.

**Comment by DanRathbun** [comment]
Isn’t there a way to mark Singleton classes as singleton in YARD ?

**Comment by thomthom** [comment]
Not nativity. But it's possible to add custom tags, and then add custom tag handlers. So it's possible to introduce a new tag that the template understands and then add some formatting/text.

**Comment by DanRathbun** [comment]
> Not nativity.

I might have been thinking of the `@abstract` tag.

The `@!parse` directive looks interesting. This would likely cause YARD to add in methods that the SketchUp API does not ...
```ruby
class Sketchup::PickHelper
  # @!parse include Singleton
end
```
The `@!parse` tag can also parse C snippet comments. [See docs](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#parse).

> But it's possible to add custom tags, and then add custom tag handlers. So it's possible to introduce a new tag that the template understands and then add some formatting/text.

Probably the best path in the long run. An `@note` might suffice in the short term.

**Comment by thomthom** [comment]
Saying that `Entity` or `View` is a `Singleton` is misleading - because that mix-in is a pattern where you obtain the singleton instance via a `.instance` method on the class. That's not the case for the SU API "singletons". Their constructor is part of another class. So we need to find another way to document this, like with custom tags.

**Comment by DanRathbun** [comment]
I implied this above ...

>This would likely cause YARD to add in methods that the SketchUp API does not ...

The `#instance` method was the main one I meant.

> Their constructor is part of another class. So we need to find another way to document this, like with custom tags.

And I agreed above custom tags are likely the best idea.

HOWEVER, they are not just objects generated via factory methods that hide a constructor, they are actual **singleton** objects exposed via a getter method. (Ie, the result of the getter is never a new factory generated instance, it is always the same object per model.)
