### ISSUE TITLE
OSX bugsplat on exit

### ISSUE THREAD

**Issue by Nazz78** [SketchUp/api-issue-tracker#2]
SketchUp Version: 2014, 2015, 2016, 2017
OS Platform: OS X

When user exits SketchUp on OS X it sometimes (not always) bugsplats, which is pretty annoying. It seems that problem is related to open WebDialogs.

Some developers have solved the problem by calling `kill!` command inside onQuit method. But this can cause problems for any extension that might come after that and need to do something before close, eg. release network license seat. Seems that David Edwards has better solution by closing the WebDialog using javascript. I'm waiting for his pattern which I'll publish here once received.

**Comment by SoapSkin** [comment]
If Dialog callback **_on_close_** set the Dialog to an Empy Page
like **_set_html("`<b>_</b>`")_**
there is no **bugsplat on Exit**

**Comment by thomthom** [comment]
This is valid for `UI::WebDialog` or `UI::HtmlDialog`?

**Comment by SoapSkinBubble** [comment]
This is valid for UI::WebDialog

**Comment by thomthom** [comment]
Logged as SU-38302

**Comment by thomthom** [comment]
We've not been able to reproduce this on SU2018, only on SU2017 M3 and older versions. Marking this one as fixed. Let us know if you still observe this.
