### ISSUE TITLE
Clarify what coordinate system bounds are relative to

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#202]
### [**`Drawingelement # bounds()`**](http://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method)

For a **group**, there is a wrapper method named **local_bounds**, whose description notes the difference in the **bounds** method between a component instance and definition. (When it really should _also_ be noted in the **bounds** method description proper. Ie, this superclass `#bounds` method.)

So the description needs to explain when it returns transformed and untransformed bounding boxes, and should include a link to **[`Group # local_bounds()`][http://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method]**.

AND / OR ... add an override method YARD directive so that the [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html) class gets it's own method docstring.

----
_Originally [posted to the public forum](https://forums.sketchup.com/t/ruby-api-documentation-errors-suggestions/10958/21) in August of 2015 ..._

----

**Expanded in subsequent [post](https://github.com/SketchUp/api-issue-tracker/issues/202#issuecomment-707819926)**:
> So with this basis, let me try to explain the issue(s) again:
> 
> 1. I used the docstring for the [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) method "**as a reference example**" that does a **very good job** in explaining the difference between instance transformed bounds versus definition untransformed bounds.
> 2. I point out the situation that the [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) does not do this and **fails** to mention transformation at all! Ie, it should follow the example of [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) and inform the reader that it returns a transformed bounds.
>    It should also (as [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) does,) mention to the reader how they can get an untransformed bounds for the drawing element object of interest.
> 3. The [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html) class _**could**_ have a method entry for it's "overridden" (or particular untransformed) `#bounds` method, which has different behavior when called on other **true** [`Sketchup::Drawingelement`](https://ruby.sketchup.com/Sketchup/Drawingelement.html) subclass instance objects.
>    This definition method docstring should explain (as [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) does,) that the returned bounds is untransformed or always uses the `IDENTITY` transform.
>    In fact, it could "parrot" much of what [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) docstring says.
>    If this cannot be done "cleanly", then [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) needs to have a better docstring that explains how it returns different transformation behavior depending upon whether it is called upon a definition or an instance object.
> 
> So, in conclusion of how things are **now**, ... a coder needing to know what [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html)`#bounds` does, needs to be pointed to [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) for the explanation (since the former is not documented.)
> **It is poor practice to document the behavior in a "wrapper method" and not even document the real method.**
> Pointing them to [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) makes them "none the wiser".

**... also listed the methods that should have their descriptions complementary ...**

> Either copy what `#local_bounds` says and edit it, or come up with better explanations for the following methods, so that they all "jive" and mesh with the "spirit" of the API, it's coordinate systems and transformations applied. ...
> 
> * `Model#bounds`
> * `Drawingelement#bounds`
> * `Group#local_bounds`
> * `ComponentDefintion#bounds`
> * `ComponentDefintion#invalidate_bounds`

~

**Comment by Eneroth3** [comment]
I'm confused what the problem is. The general rule is that the bounds is in the context the DrawingElement is placed. 
 `ComponentDefinition` is something of an exception as it doesn't exist in a drawing context (I'd argue it shouldn't really be a DrawingElement). `Group#bounds` is however consistent to `Edge#bounds`, `Face#bounds` etc.

To me `Group#localbounds` is the odd one out and appears to be a leftover from before `Group#definition` was implemented, and the API "pretended" groups weren't related to components. I'm thinking it may be a good idea to deprecate this method in favor of `definition.bounds`.

**Comment by DanRathbun** [comment]
> I'm confused what the problem is.

This issue was logged because there is/was confusion by coders reading the API (many of them did not or do not have the same level of experience that you do now have understanding the API and it's "written tricks".) So if you are confused, just imagine the coder who is relatively new to the SketchUp API and SKP model structure.

> To me [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) is the odd one out and appears to be a leftover from before [`Group#definition`](https://ruby.sketchup.com/Sketchup/Group.html#definition-instance_method) was implemented, and the API "pretended" groups weren't related to components. 

**TRUE**

> `ComponentDefinition` is something of an exception as it doesn't exist in a drawing context (I'd argue it shouldn't really be a `DrawingElement`). 

**AGREED**.
And this is part of the problem that resulted in **this issue** being opened as well as another on `ComponentDefinition#material=`.

> _**Aside**: See Issue 19 : [ComponentDefinition material assignment has weird behavior](https://github.com/SketchUp/api-issue-tracker/issues/19)_

Most (I think) of the `DrawingElement` methods inherited by `ComponentDefinition` are noops. Ie, `#erase!` does not delete a definition object. The material setter and getter do not work as one would think. [_See link to issue above_.]
Most of the inherited methods apply to instance objects only. (ie, visibility methods, shadow properties, etc.)

It appears that (from my perspective, and previous conversation with Thomas,) that the `ComponentDefinition` class was "made to look" like it descends from `DrawingElement`, so that it could share either the definition of the `#bounds` method, or it's documentation (as I will say below **hasn't** been beneficial.)

>  I'm thinking it may be a good idea to deprecate this method in favor of **`group.definition.bounds`**.

You are missing the true points of this issue (although I have problem deprecating. _See footnote_.) 
For example we cannot create a link to [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html)`#bounds`
**Because it is not documented !**

Instead the docs imply (and Ruby introspection indicates) that [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html) inherits [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method).
**But in practice the definition class acts as though it has it's own overridden `#bounds` instance method.**

> _**Aside**: I wonder if in the C++ code .. if the Definition class is really a Drawingelement subclass ?_

So with this basis, let me try to explain the issue(s) again:

1. I used the docstring for the [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) method "**as a reference example**" that does a **very good job** in explaining the difference between instance transformed bounds versus definition untransformed bounds.

2. I point out the situation that the [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) does not do this and **fails** to mention transformation at all! Ie, it should follow the example of [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) and inform the reader that it returns a transformed bounds.
It should also (as [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) does,) mention to the reader how they can get an untransformed bounds for the drawing element object of interest.

3. The [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html) class _**could**_ have a method entry for it's "overridden" (or particular untransformed) `#bounds` method, which has different behavior when called on other **true** [`Sketchup::Drawingelement`](https://ruby.sketchup.com/Sketchup/Drawingelement.html) subclass instance objects.
This definition method docstring should explain (as [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) does,) that the returned bounds is untransformed or always uses the `IDENTITY` transform.
In fact, it could "parrot" much of what [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) docstring says.
If this cannot be done "cleanly", then [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) needs to have a better docstring that explains how it returns different transformation behavior depending upon whether it is called upon a definition or an instance object.

So, in conclusion of how things are **now**, ... a coder needing to know what [`Sketchup::ComponentDefinition`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html)`#bounds` does, needs to be pointed to [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) for the explanation (since the former is not documented.)
**It is poor practice to document the behavior in a "wrapper method" and not even document the real method.**
Pointing them to [`Sketchup::Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method) makes them "none the wiser".

**Has this cleared up the confusion over the confusion about the confusing API method docs ?**

----

Lastly, I don't care one way or the others, if [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) is deprecated, but to do so, you need to point to the replacement which needs to be documented properly (as in task 3, above.)
I do know that [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) is used in many places throughout DC code, and likely many extension that predate 2015 release.

I never cared much for the method name `"local_bounds"` as `"untransformed_bounds"` seems more descriptive.

~

**Comment by Eneroth3** [comment]
Some of this confusion seem to be a matter of perspective. I've never though of bounds as being transformed or untransformed, but to be relative to a certain coordinate system. At some point everything is transformed to global coordinates (and then screen coordinates), so it's really just different ways to think of the same thing. For "true" `DrawingElements` this would be the coordinate system the of the parent container, and for definition it is the definition's own internal coordinate system.

I agree it would be useful to document `ComponentDefinition#bounds` separately, and both `#bounds` methods could clarify what coordinate system they use.

I don't think however any more attention should be drawn to `Group#local_bounds` by liking to it and compare other methods to it. This method is in my opinion better to hide away as it breaks the pattern and confuses what bounds should be relative to.

I also agree the naming is confusing. `Group#bounds` returns bounds in the local coordinates the Group instance is placed in while `Group#local_bounds` return bounds local to the group's component definition. To me none is inherently more local than the other.  it's a question to what degree you think of a `Group` as having a definition and to what degree you pretend it contains its content "locally", as the API originally wanted you to think. To me this is another reason to deprecate the method.

Normally deprecating something means there is a clear plan to remove it, but in the SketchUp Ruby API a lot of things have been deprecated and then just left as they are for backward compatibility. @thomthom, are you okay with deprecating `Group#local_bounds` in favor of `group.definition.bounds`?

**Comment by DanRathbun** [comment]
> _I've never though of bounds as being transformed or untransformed, but to be relative to a certain coordinate system._

It is not just that bounds is relative to coordinate systems, the bounds also shrink and grow according to the rotational or scaling transform applied.

I draw your attention to the recently added methods in the LayOut API ...
* [`Layout::Entity#drawing_bounds`](https://ruby.sketchup.com/Layout/Entity.html#drawing_bounds-instance_method)
* [`Layout::Entity#untransformed_bounds`](https://ruby.sketchup.com/Layout/Entity.html#untransformed_bounds-instance_method)

> _I also agree the naming is confusing. ... To me none is inherently more local than the other._

Re, naming conventions, I suspect they came from OpenGL conventions. 

> _I don't think however any more attention should be drawn to `Group#local_bounds` by _linking_ to it_ ...

Fine, that was 1 idea, followed by an OR **and another idea**. (I really only said that because that is what I've had to do in the forum, when a new coder needed to know what the difference between `#bounds` and `#local_bounds` was, or what `ComponentDefintion#bounds` meant.)

Either copy what `#local_bounds` says and edit it, or come up with better explanations for the following methods, so that they all "jive" and mesh with the "spirit" of the API, it's coordinate systems and transformations applied. ...
* `Model#bounds`
* `Drawingelement#bounds`
* `Group#local_bounds`
* `ComponentDefintion#bounds`
* `ComponentDefintion#invalidate_bounds`

----

As a separate task, it would be nice if you or Thomas could author an extra article in the doc's Files section, on
*  "Transformations and Coordinate Systems in the SketchUp DOM".

I mean we cannot expect that the API dictionary should have tutorial like text embedded within it. But it is okay to put a "See Also" link to such extra files. I'm fairly certain you've already written most of it as forum replies. Andreas also has written some good forum posts on it as well.

~

**Comment by Eneroth3** [comment]
>> I've never though of bounds as being transformed or untransformed, but to be relative to a certain coordinate system.
>
> It is not just that bounds is relative to coordinate systems, the bounds also shrink and grow according to the rotational or scaling transform applied.

That's what I mean by being relative to a certain coordinate system.

The instance's bounds being relative to the parent's coordinate system (in this case the model itself):

![2020-10-15_12h35_18](https://user-images.githubusercontent.com/5631725/96112671-4dc42f80-0ee3-11eb-849a-03a636d82d14.png)

The definition's bounds being relative the definition's own coordinate system:

![2020-10-15_12h35_48](https://user-images.githubusercontent.com/5631725/96112681-53ba1080-0ee3-11eb-9b6e-554284f7e2db.png)

**Comment by DanRathbun** [comment]
Hey look! Nice images for your tutorial. ;)

**Comment by thomthom** [comment]
I'm very much in favor of the documentation using more images to describe concepts and results. Particularly in cases like this.

**Comment by DanRathbun** [comment]
Would y'all agree that this issue's caption should be changed to something like:
"API methods re: bounds should be improved and complimentary"

?

**Comment by Eneroth3** [comment]
"Clarify what coordinate system bounds are relative to" is what I'm calling the commit internally.

**Comment by DanRathbun** [comment]
NOTE: Partially fixed with the 2021.0 release.

Although `ComponentDefinition#bounds` did not get it's own independent docstring, it did get a mention in [`Drawingelement#bounds`](https://ruby.sketchup.com/Sketchup/Drawingelement.html#bounds-instance_method).

I am also disappointed that all mention of transforming has been removed. Bounding Boxes can also be transformed. Ie, the bounds of instances (or groups) differ from their definition's untransformed bounds in that the transformed bounds can have differing height, width, and length, as well as coordinates for their centers and corners that have differing distances from the BB origin than their definition's bounds.

> @Eneroth3 _said:_ Some of this confusion seem to be a matter of perspective. I've never though of bounds as being transformed or untransformed, but to be relative to a certain coordinate system.

Well, see here I disagree with your perspective. I feel it is flawed, and that more internal discussion would be in order with senior members of the SketchUp programming staff in this regard. You obviously do not wish to believe me, perhaps you can get some input from Andrew ? He would not have named the [`Layout::Entity#untransformed_bounds`](https://ruby.sketchup.com/Layout/Entity.html#untransformed_bounds-instance_method) getter and setter methods such if bounds could not be subject to transformations.

The changes you've made (deleted mention of "untransformed state") to [`Group#local_bounds`](https://ruby.sketchup.com/Sketchup/Group.html#local_bounds-instance_method) have made it more confusing than it was.
