### ISSUE TITLE
Improve documentation on Pro only API methods

### ISSUE THREAD

**Issue by Nazz78** [SketchUp/api-issue-tracker#208]
# SketchUp Ruby API Issue

When trying to use `group1.intersect(group2)` Sketchup returns `ArgumentError: 'intersect' is a Pro feature only`. This (and other Pro only API methods) should be clearly marked in the API documentation!

![intersect_pro_only](https://user-images.githubusercontent.com/4271863/53097146-0c6a5980-3521-11e9-8df2-439292b7198b.png)

Example:
1. In SketchUp Make create two intersecting groups.
2. Run
```ruby
entities = Sketchup.active_model.entities
group1 = entities[0]
group2 = entities[1]
result = group1.intersect(group2)
```

**Comment by DanRathbun** [comment]
Did this apply only to the [`Sketchup::Group`](https://ruby.sketchup.com/Sketchup/Group.html) and [`Sketchup::ComponentInstance`](https://ruby.sketchup.com/Sketchup/ComponentInstance.html) methods for boolean operations, viz:

* `#intersect
* `#split`
* `#subtract`
* `#trim`
* `#union`
