### ISSUE TITLE
Faulty header in some web-browsers

### ISSUE THREAD

**Issue by TIGrant** [SketchUp/api-issue-tracker#209]
See here: https://sketchucation.com/forums/viewtopic.php?p=645845#p645845

Someone has added a Trimble linked image to the right-hand end of the main-page's top-banner.
That image https://www.sketchup.com/sites/developers.sketchup.com/files/core/trimble-logo-white.png is not found, and as a result the default place-holder is making the top-banner deeper because the default place-holder is larger.
As a result the top part of the main page is covered over by the top-banner...
The broken-link place-holder in Firefox and IE are quite large, in Edge and Chrome they are much smaller and they avoid this 'overlapping'.

**Comment by thomthom** [comment]
URL for image that I think is the same or similar: https://developer.sketchup.com/sites/help.sketchup.com/files/core/trimble-logo-white.png

**Comment by TIGrant** [comment]
Can someone with super-powers... copy that PNG over into the location mentioned in my post.
Or edit the html code so the PNG you show is found...
Either way, then the issue is resolved !

**Comment by thomthom** [comment]
The favicon also appear to be gone: https://help.sketchup.com/sites/all/themes/sketch_help/favicon.ico

**Comment by thomthom** [comment]
Documentation regenerated with new URLs. Might require Refresh or Force Refresh to see the updates.
