### ISSUE TITLE
Sketchup::Camera#fov= documentation incorrectly says argument is in millimeters 

### ISSUE THREAD

**Issue by bhyoung** [SketchUp/api-issue-tracker#211]
# API Issues Only

# Bug Reports: None.

Reference:
  1. SketchUp/LayOut Version: All
  2. OS Platform: Windows and Mac

Describe briefly what you are doing and what is happening.
The camera.fov= setter is treating input arguments with units of degrees, but the API documents the argument units as being in millimeters:
http://ruby.sketchup.com/Sketchup/Camera.html

Describe what the expected result is.

Start up Sketchup and open a model, that is in full view. Do not adjust zoom level from the start up default. Type the following into the console:
```
Sketchup.active_model.active_view.camera.fov= 50.mm
```
The expected result is a minor change in zoom level or field of view because a focal length of 50 millimeters is near normal human field of view.

Actual result: Camera zooms excessively.

To determine what the FOV was actually set to in degrees, type the following:

```
Sketchup.active_model.active_view.camera.fov
```
Returns a simple floating point value of 1.96, which is documented as being in degrees and that getter return values units is documented correctly.

Attach any relevant files: None

# Feature Requests

Change API setter description from:
   The fov= method sets the field of view, in millimeters, for a Camera.
TO:
   The fov= method sets the field of view, in degrees, for a Camera.

**Comment by thomthom** [comment]
I'm afraid that we cannot change the API at this point. That would break existing extensions that rely on the existing behaviour. 

If you want a way to set the field of view via degrees that would have to be done via a new method.

**Comment by thomthom** [comment]
Oh - I'm sorry. I see you meant that the documentation needed updating because the setter actually already works in degrees.

**Comment by Eneroth3** [comment]
Already fixed.

**Comment by DanRathbun** [comment]
Except that in **my** browser the doc issue is **not fixed**.

The [`Camera#fov=`](https://ruby.sketchup.com/Sketchup/Camera.html#fov=-instance_method) method **still erroneously** states that the argument is in millimetres **instead** of the correct degrees.

----

Isn't it more proper to let @thomthom close these with a linked commit ?
