### ISSUE TITLE
SU2019 - Windows - hard coded path?

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#218]
While checking into #216, I created another SU folder and loaded Ruby 2.7.0 into it, just to see if the issue was related to the standard Ruby install.  The first two folders in PATH are:

```
C:\Program Files\SketchUp\SketchUp 2019_2\Tools\RubyStdLib\platform_specific
C:\Program Files\SketchUp\SketchUp 2019\
```

I assume the 2nd entry is hardcoded.  Shouldn't this match the first?

Re #216, both 2.5.1 & 2.7.0 behaved the same.  I tried several ways to grab the io from a spawned cmd, and none worked, although **all worked** in stand-alone Ruby.  As mentioned, this was from a normal shortcut, starting SU from a command window, io worked as expected...

**Comment by thomthom** [comment]
I don't think it's hard coded to program files. But it's probably picking up the installation path. Running copies of SketchUp from locations the installer didn't install it to isn't something we support.

I think I'll close this one. But if you see cases of the paths not reflecting the path SketchUp was installed to then please reopen this.

**Comment by DanRathbun** [comment]
> I don't think it's hard coded to program files. But it's probably picking up the installation path.

**FYI** the path is located here in the registry on MS Windows platforms ...

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\SketchUp\SketchUp 2019\InstallLocation`

So tweaking this attribute value when testing would (_we would hope_) help have things run normally as if the application was installed to the test path.
