### ISSUE TITLE
SU2019 - Windows - Missing dll's

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#219]
Below is the list of dll's that should be included with Ruby, as these are required by the extension standard libraries.  They are the dll's included in the following MSYS2/MinGW packages - gcc-libs, gdbm, libffi, openssl, readline, and zlib.  Note these are from a current build, the version numbers may vary...

```
libasprintf-0.dll
libatomic-1.dll
libbz2-1.dll
libcharset-1.dll
libcrypto-1_1-x64.dll
libexpat-1.dll
libffi-6.dll
libgcc_s_seh-1.dll
libgdbm-6.dll
libgdbm_compat-4.dll
libgettextlib-0-19-8-1.dll
libgettextpo-0.dll
libgettextsrc-0-19-8-1.dll
libgmp-10.dll
libgmpxx-4.dll
libgomp-1.dll
libhistory7.dll
libiconv-2.dll
libintl-8.dll
libminizip-1.dll
libp11-kit-0.dll
libquadmath-0.dll
libreadline7.dll
libssl-1_1-x64.dll
libssp-0.dll
libstdc++-6.dll
libtasn1-6.dll
libtermcap-0.dll
libwinpthread-1.dll
zlib1.dll
```

**Comment by thomthom** [comment]
Any GLP libraries was omitted due to licensing restrictions. If I recall correctly, most of those were related to CLI functionality.

Are you seeing missing functionality beyond the GPL and CLI related functions?
