### ISSUE TITLE
Request for threaded Progress Bar

### ISSUE THREAD

**Issue by Whaat** [SketchUp/api-issue-tracker#220]
We all know the issue.  There's is no easy way to create a true progress bar / window through Ruby as it won't be updated until the Ruby current Ruby process has completed.

We need a proper progress window that Ruby can send updates to and that we can poll for user interaction.

This is such an important feature, it would improve the user experience of so many extensions.

**Comment by kengey** [comment]
#360 duplicate (by me, sorry)
