### ISSUE TITLE
Layout::Document#save throws error if the file is already open in LayOut ?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#221]
### API Release Notes Documentation Issue

In the Release Notes document ...
under "**What's new in SketchUp 2019 M0**"
within section "**LayOut Ruby API for SketchUp**"
we have ...
> * Added [**`Layout::Document#save`**](http://ruby.sketchup.com/Layout/Document.html#save-instance_method) will now throw an error if the file is already open in LayOut

**This makes little sense.**

**Perhaps it was meant to indicate a change to the [`::open`](http://ruby.sketchup.com/Layout/Document.html#open-class_method) class method ?**

**Comment by ackarkka** [comment]
> ### API Release Notes Documentation Issue
> In the Release Notes document ...
> under "**What's new in SketchUp 2019 M0**"
> within section "**LayOut Ruby API for SketchUp**"
> we have ...
> 
> > * Added [**`Layout::Document#save`**](http://ruby.sketchup.com/Layout/Document.html#save-instance_method) will now throw an error if the file is already open in LayOut
> 
> **This makes little sense.**
> 
> **Perhaps it was meant to indicate a change to the [`::open`](http://ruby.sketchup.com/Layout/Document.html#open-class_method) class method ?**

Nope, this is new behavior for the LayOut Ruby API for SketchUp. The use case for this is a SketchUp extension that attempts to save to a LayOut file that is already opened in LayOut. Previously the save would succeed, but the user wouldn't see the change if the file was already open in LayOut. They could then save any changes they had made in the file to disk, demolishing the changes that the SketchUp extension had made.

**Comment by DanRathbun** [comment]
Okay then this information needs to be added to the documentation, and what class exception is raised ?

This also brings up the idea that a query method will be needed to ask if a document object is actually open in LayOut. (The code would need to check for running LayOut processes and ask them what their file path is for comparison.)

**Comment by DanRathbun** [comment]
The exception should be an **`IOError`** not an **`ArgumentError`** on a failed save !
