### ISSUE TITLE
openpanel and savepanel wildcard handling on mac...

### ISSUE THREAD

**Issue by driven** [SketchUp/api-issue-tracker#232]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version:
2. OS Platform:

Describe briefly what you are doing and what is happening.

Describe what the expected result is.

```ruby
# Complete reprodusible code snippet. (Important!)
```

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by driven** [comment]
when porting to mac, many window developers use the same code for open and save panels that they use for windows which includes  a wildcard in the third param...

mac's simply ignore this for open panel but bugs plat if a save panel...

![open_save_panel_differences](https://user-images.githubusercontent.com/227987/55038411-aa69ac00-5018-11e9-9e2a-44719b1e0e81.gif)

link to forum where I found Garry's bug...

https://forums.sketchup.com/t/simple-dxf-cnc-exporter/88725

john

**Comment by taustin73** [comment]
SU-44314
