### ISSUE TITLE
Document FrameChangeObserver interface

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#236]
It's difficult to find in the `Sketchup::Pages` documentation. Better do document this purely abstract interface like we do with the Tool interface.

**Comment by DanRathbun** [comment]
@thomthom WE did this **YEARS** ago. I was the one who authored the abstract class page. You and Jim checked it over, I made changes and you pulled it into the stubs repo.

http://ruby.sketchup.com/Sketchup/FrameChangeObserver.html
