### ISSUE TITLE
Correct documentation for Sketchup::Menu#set_validation_proc

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#239]
I was looking for a way to disable (gray out) a whole submenu when all its entries are invalid, rather than disable them all individually.

There is a [UI::Menu#set_validation_proc](http://ruby.sketchup.com/Sketchup/Menu.html#set_validation_proc-instance_method) method, but it's documentation appears to be wrong. According to the documentation the first parameter is `menu (String) — A string name of the menu to add.` but according to my tests and the code example the expected parameter is an integer ID of a menu item to use the validation proc for. It seems the documentation is just copied from #add_item.

This whole class documentation is rather confusing as it refer to menu *items* simply as menus in the parameter names.

If possible, a way to attach a validation proc to a menu itself, not one of its entries, would be much appreciated.

**Comment by thomthom** [comment]
Yes, the documentation is just plain wrong for that method.

You are correct though, you pass inn the handle you get from `add_menu`.

**Comment by thomthom** [comment]
> If possible, a way to attach a validation proc to a menu itself, not one of its entries, would be much appreciated.

I'm not sure I understand what you mean by that?

**Comment by Eneroth3** [comment]
I'd like to set a validation proc for the submenu itself, not a child entry, to make e.g. gray out the whole submenu.

**Comment by DanRathbun** [comment]
Uh ... there is **NO** such class as `UI::Menu`. It is actually [`Sketchup::Menu`](http://ruby.sketchup.com/Sketchup/Menu.html)

> You are correct though, you pass in the handle you get from `add_menu`.

There is **NO** such method as **`add_menu`** in the API.

It is actually the [`Sketchup::Menu#add_item`](http://ruby.sketchup.com/Sketchup/Menu.html#add_item-instance_method) method that returns the integer ID.

And whilst on this subject, I notice another related error in [`Sketchup::Menu#add_item`](http://ruby.sketchup.com/Sketchup/Menu.html#add_item-instance_method) method documentation.

The first overload has the 1st argument named "menu" when it should be "menu_text".
The parameter description is also incorrect (ie, "The name of the menu to add." _which belongs to the [`#add_submenu`](http://ruby.sketchup.com/Sketchup/Menu.html#add_submenu-instance_method) method_,) and should be "The menu text for the item.")

----

The [`Sketchup::Menu#add_item`](http://ruby.sketchup.com/Sketchup/Menu.html#add_item-instance_method) method documentation also needs work as the "command" parameter has no description.

**Comment by DanRathbun** [comment]
Noticed this **again** today. Need to Ruby Stubs script fixed so Devs can help fix these dumb long-standing errors.
