### ISSUE TITLE
Add custom YARD tags

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#241]
Ref: https://github.com/lsegal/yard/issues/1227#issuecomment-467969223

* Add `@bug` tag to make it easier to highlight known bugs. Separate them from `@note`. This can allow YARD to extract these tags and make a list - which in turn might be useful for RuboCop. Maybe the tags can denote what versions are affected.

* Add `@category` tag to allow for a new view where classes/modules are grouped by category. Similar to the old API docs.

Reference to old categories: https://web.archive.org/web/20120311205755/https://developers.google.com/sketchup/docs/classes

**Comment by Eneroth3** [comment]
@bug is already implemented. @category may be covered by #199, although it doesn't go into details about implementation. Should I close this?

**Comment by DanRathbun** [comment]
(P.S. Please do not use "at names" unless notifiying a GitHub member. YARD tag names should be wrapped in single backquotes. You've "pinged" two members who likely have nothing to do with the SketchUp API.)

**Comment by Eneroth3** [comment]
Maybe related to this guy? https://www.wired.com/story/null-license-plate-landed-one-hacker-ticket-hell/

**Comment by thomthom** [comment]
`@category` isn't complete. Lets leave this as a reminder to get that finished.

**Comment by thomthom** [comment]
Ah, I see #199 is a ticket dedicated for the categories. Ok. lets keep that open and close this.
