### ISSUE TITLE
[FR] Glue component instance to other instance

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#248]
From the SketchUp UI you can attach a gluing component onto another component. This could be highly useful if you e.g. want a vase to move along with a table, without being a part of that table. The problem is that it isn't exposed to the Ruby API.

ComponentInstance#glued_to can return a ComponentInstance but #glued_to= only accept faces.

![2019-04-16_12h10_42](https://user-images.githubusercontent.com/5631725/56201563-6da23b00-6041-11e9-80fd-cda9f3eab4ae.gif)

**Comment by DanRathbun** [comment]
Didn't Neil already open an issue ?

https://github.com/SketchUp/api-issue-tracker/issues/111

**Comment by Eneroth3** [comment]
Woops; duplicate of #111

**Comment by thomthom** [comment]
Yea, we want to add `InstancePath` support to more areas of the API - like this one.
