### ISSUE TITLE
Unicode characters doesn't display correct in the Ruby Console

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#253]
Observing in SketchUp 2019 M1

![image](https://user-images.githubusercontent.com/192418/56855555-0772bd80-6949-11e9-8656-f9549d154ec4.png)

Appear to be an incomplete fix for the Unicode regression in SketchUp 2018:

![image](https://user-images.githubusercontent.com/192418/56855572-40ab2d80-6949-11e9-8d46-3db23644707f.png)

Expected behaviour is last seen in SketchUp 2017:

![image](https://user-images.githubusercontent.com/192418/56855578-60daec80-6949-11e9-886c-fbfa93444e47.png)

**Comment by DanRathbun** [comment]
_REF:_ Issue [#17 : Ruby Console fails with some non-ascii characters ("Š")](https://github.com/SketchUp/api-issue-tracker/issues/17)

**Comment by Eneroth3** [comment]
Just found a very odd behavior. Using puts makes correct characters show even if they don't do otherwise.

```ruby
"CleanUp³"
# => CleanUpￂﾳ

puts "CleanUp³"
#=> CleanUp³
```

**Comment by taustin73** [comment]
SU-44311
