### ISSUE TITLE
Loading non SKP definitions through API

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#254]
Currently the SketchUp Ruby API allows for [loading ComponentDefinition objects from external SKP files](https://ruby.sketchup.com/Sketchup/DefinitionList.html#load-instance_method), and [use importers to load other supported formats](https://ruby.sketchup.com/Sketchup/Model.html#import-instance_method) and have the user place the component manually with Place tool. To my knowledge the latter can't be done without user interaction.

It would however be very useful if you could use the importers to only load a ComponentDefinition to the DefintionList, without any UI. this would essentially allow for extension to have live links to non-skp references. One use case would be an extension that lets the user crop DWGs and later reload them when updated, while retaining the cropping.

I've had a brief look at the interface for third party importers (headers/sketchupapi/import_export/modelexporterplugin.h) and suspects these could also be supported as they essentially converts the imported file and save it to a temporary location, and let SketchUp handle Place tool activation.

![2019-05-03_12h13_48](https://user-images.githubusercontent.com/5631725/57131541-fdafe680-6d9c-11e9-8149-3be3306cb420.png)

Not sure if this should be logged separately, but another thing I've noticed is that imported components are associated with these temp paths, not the path of of the non-skp source. From a  user point of view this temp path makes little sense and probably shouldn't be exposed, while it could be useful to locate the external non-skp source. Perhaps this could even be regarded a bug. I was thinking the import feature could override the component path after import.

**Comment by Eneroth3** [comment]
Id' be glad if the component path could be re-associated with the non-skp file after import, even if the other things are implemented at a later stage. Eneroth reference manager lets the user navigate to linked files, and currently it just leads you to the temp folder. Even emptying the path after import would in my view be cleaner.

![2019-05-03_12h18_34](https://user-images.githubusercontent.com/5631725/57131873-0fde5480-6d9e-11e9-8e85-98b64e285f99.png)

**Comment by thomthom** [comment]
Yea - we have the same challenge with the Trimble Connect extension. It allows for references of any format SketchUp support. And the inconsistent handling of undo and Place Component activation is a pain.

**Comment by thomthom** [comment]
> Not sure if this should be logged separately, but another thing I've noticed is that imported components are associated with these temp paths, not the path of of the non-skp source. From a user point of view this temp path makes little sense and probably shouldn't be exposed, while it could be useful to locate the external non-skp source. Perhaps this could even be regarded a bug. I was thinking the import feature could override the component path after import.

Please log this separately.  Makes dealing with logged issues much easier if each refer to a single scenario.

**Comment by Eneroth3** [comment]
Will do! Generally I'm very keen on keeping things separate but on this occasion I was unsure how integrated this was to the rest.

**Comment by DanRathbun** [comment]
> Currently the SketchUp Ruby API allows for loading ComponentDefinition objects from external SKP files, and use importers to load other supported formats and have the user place the component manually with Place tool. **To my knowledge the latter can't be done without user interaction**.

It _might_ be done with a "Send ESC" hack. See my old example in the forum ...

https://forums.sketchup.com/t/example-import-a-3ds-using-a-specific-transform-cross-platform/23425

**Comment by Eneroth3** [comment]
Logged as SKEXT-2872

**Comment by DanRathbun** [comment]
@thomthom : I believe this has been satisfied in release **2021.1** ...

* [`Sketchup::DefinitionList#import`](https://ruby.sketchup.com/Sketchup/DefinitionList.html#import-instance_method)
