### ISSUE TITLE
Clarify documentation for how glue-to behavior works

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#256]
Reference forum thread: https://forums.sketchup.com/t/setting-snapto-behavior-in-component-definition-has-no-effect-on-the-ui/94817

Summary:

It's not easy to determine how the properties of `Sketchup::Behavior` should be configured to match the UI properties.

For instance:
![image](https://user-images.githubusercontent.com/192418/57219924-defa5b80-6ff9-11e9-8275-6ccbe2bacae3.png)

Switching from `None` to any of the other values in the UI actually changes two properties in `Sketchup::Behavior`; `#snapto=` and `#is2d=` . The former users different terminology from the UI and the latter is simply non-intuitive.

* The class itself should have better explanation on how these properties correlate with the UI behaviour.
* The properties should have clear references to their related pairs.

**Comment by Eneroth3** [comment]
Writing out a warning to the console when trying to change snapping without having gluing enabled could also be very useful. Raising might be more idiomatic but could break existing code that expects a silent failure.

**Comment by DanRathbun** [comment]
I also like [Christina's idea of aliases](https://forums.sketchup.com/t/setting-snapto-behavior-in-component-definition-has-no-effect-on-the-ui/94817/14): `gluable?` for `is2d?`, and `gluable=` for `is2d=`.

**Comment by thomthom** [comment]
> Writing out a warning to the console when trying to change snapping without having gluing enabled could also be very useful. 

This might be something suited for rubocop-sketchup.

**Comment by Eneroth3** [comment]
> This might be something suited for rubocop-sketchup.

Is it possible with static code analysis to know reliably if gluing has been enabled when setting snapto? A tool that sets the snappping might very well check that glue to is enabled in a calling method somewhere else in the code base.

**Comment by thomthom** [comment]
As I was typing I realized that it's likely that this check would be noisy. So a runtime warning is probably better.

I looked in the source code, and both `snapto` and `cuts_opening` needs the `is2d` flag enabled.

**Comment by DanRathbun** [comment]
And another coder fails prey to this poor documentation ...
https://forums.sketchup.com/t/batch-edit-component-glue-to/115513

**Comment by DanRathbun** [comment]
Really, really strongly desiring Julia's `#gluable?` and `#gluable=` aliases for the [`Behvaior`](http://ruby.sketchup.com/Sketchup/Behavior.html) class.

**Comment by DanRathbun** [comment]
There needs to a way to disable warnings though like how rubocop rules can be ignored with a config file.

**Comment by DanRathbun** [comment]
I still feel better docs and aliasing the `is2d` methods as `gluable` would prevent most confusion, without the "noise" of console warnings.

**Comment by Eneroth3** [comment]
If you close the Ruby console you wont see warnings written to it.
