### ISSUE TITLE
Document Tool interface as an abstract class

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#257]
The FrameChangeObserver is documented as abstract with what appears to be the YARD `@abstract` keyword. This makes a special textbox with rounded corners show up, saying the class is abstract.

![2019-05-07_20h33_36](https://user-images.githubusercontent.com/5631725/57324172-a6e13e80-7107-11e9-9d12-09cab1e77933.png)

For consistency it would be good if the abstract Tool class was tagged similarly. Being able to recognize this visual cue could be beneficial not the least to new developers.

**Comment by DanRathbun** [comment]
_FYI_, Copied and your text and image to [an additional new issue](https://github.com/SketchUp/api-issue-tracker/issues/259) for the [`Sketchup::Animation`](http://ruby.sketchup.com/Sketchup/Animation.html) class, as it needs the same treatment.
