### ISSUE TITLE
Ruby API Documentation for #move!(transform) argument

### ISSUE THREAD

**Issue by bhyoung** [SketchUp/api-issue-tracker#264]
References:

1. Ruby API: http://ruby.sketchup.com/Sketchup/Group.html#move!-instance_method
2. Ruby API: http://ruby.sketchup.com/Sketchup/ComponentInstance.html#move!-instance_method
3. https://forums.sketchup.com/t/move-relative-vs-absolute-positioning/31899/2
4. https://forums.sketchup.com/t/ruby-api-documentation-errors-suggestions/10958/18

*Note: This is for Sketchup Ruby API Documentation text change only.*

# Documentation Bug

1. Sketchup version: All
2. Operating System: N/A (issue not against software, but online Ruby API documentation)

Group and ComponentInstance method "move!" is currently (as of April 2019) implying that the argument is applied to the existing transformation. The example below is for ComponentInstance "move!":

     The move! method is the same as the transform! method, except that it
     does not record the move as an undo operation.

     This method is useful for moving entities inside of an animation or page transition.

That is not correct, it assigns a new transformation. Change text to the following:

     The move! method is the same as the transform= method, except that it
     does not record the move as an undo operation.

     This method is useful for moving entities inside of an animation or page transition.

**Comment by DanRathbun** [comment]
_Psst! You cannot reveal private messages in Discourse forums._

It was discussed publicly here (by yourself):

https://forums.sketchup.com/t/move-relative-vs-absolute-positioning/31899/3

**Comment by bhyoung** [comment]
Sketchup API-Issue-Tracker issue #264 reference #3 replaced with forum
response link instead of private message.
