### ISSUE TITLE
DWG import option, “:preserve_origin” can not be overwrite in ruby

### ISSUE THREAD

**Issue by saedrna** [SketchUp/api-issue-tracker#268]
# Bug Reports

Please include the following:

1. SketchUp/LayOut Version : Sketchup 2018:
2. OS Platform: Win64

Describe briefly what you are doing and what is happening.
The Model.import now supports options as a map, but the :preserve_origin option can not overwrite the manually set option in `File->Import->Options` for DWG files.

Describe what the expected result is.

```ruby
options={:units => "m", :preserve_origin => true}
Sketchup.active_model.import("C:/path/to/dwg", options)
```
When set the option manually to false, the ` :preserve_origin => true` can not overwrite it.
Attach any relevant files.

[2014.zip](https://github.com/SketchUp/api-issue-tracker/files/3251612/2014.zip)

**Comment by thomthom** [comment]
I'm not able to reproduce.  Using SU2018 the DWG imported same way it does when using the UI

![ImportDwgPreserveOrigin](https://user-images.githubusercontent.com/192418/58874666-b08ba100-86c9-11e9-8d9b-ece361f25d30.gif)

But it's so far from the origin that I had to delete the scale component and then Zoom Extent to find it.
Even then, the model isn't really usable that those coordinates, you see that the lines start to jitter:

![FarFromOrigin](https://user-images.githubusercontent.com/192418/58874745-e03aa900-86c9-11e9-8941-e8081995ea73.gif)

Like Revit, SketchUp expects you to geo locate the origin of the model and have the geometry centered around the origin. It's not made to display things at world coordinates.

With a geo located model you can use `model.point_to_utm` to convert the model's local X,Y,Z coordinates to world coordinates: http://ruby.sketchup.com/Sketchup/Model.html#point_to_utm-instance_method

**Comment by saedrna** [comment]
Is this a windows only bug？ I will remove other plugins to isolate the problem tomorrow. 

The large coordinate is intended, because my plugins manage an offset to make all the coords consistent, I use an observer to reverse the large coordinate.

**Comment by saedrna** [comment]
I have deactivate all the addons, still have the same problem, see the pics (sorry for the language problem, but I hope you get the idea)
![import](https://user-images.githubusercontent.com/3850191/58890478-456bba00-871d-11e9-9274-905572db7303.gif)

**Comment by saedrna** [comment]
I have attach a screen record to compare it (sorry for the language problem, hope you get the idea)
![import](https://user-images.githubusercontent.com/3850191/58891043-61bc2680-871e-11e9-870d-44c868e362fd.gif)

**Comment by saedrna** [comment]
Also tested with a freshly installed SketchUp 2019.
![import19](https://user-images.githubusercontent.com/3850191/58892666-36870680-8721-11e9-8def-e90d2f7c43ce.gif)

**Comment by saedrna** [comment]
The default one in `C:/Program Files/Sketchup/Sketchup 2019`

**Comment by thomthom** [comment]
This only happens when using Ruby?
Using the UI preserves the origin fine for you?

**Comment by saedrna** [comment]
Yes, it seems that option is always using the one set by the UI dialog

**Comment by thomthom** [comment]
Yea, I see the same thing now - only the `preserve_origin` option is ignored - using whatever is set in the UI. On both Windows and Mac, in SU2018-2019.1.

**Comment by thomthom** [comment]
Logged as SU-43065
