### ISSUE TITLE
Allow a Sketchup::Model#import :transform option 

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#271]
### SketchUp Ruby API Feature Request

Allow a [`Sketchup::Model#import`](http://ruby.sketchup.com/Sketchup/Model.html#import-instance_method) `:transform` hash option so coders can import directly to a 3D point bypassing the GUI insertion (instance Move) tool.

Currently coders are forced into an ESC sendkey hack (for **non-skp** files) ...

https://forums.sketchup.com/t/example-import-a-3ds-using-a-specific-transform-cross-platform/23425

----

Coders have been asking for this simple enhancement for years ...

https://forums.sketchup.com/t/ruby-api-model-importtopoint/18747 - DEC 2015

https://forums.sketchup.com/t/how-to-import-skp-to-a-3dpoint-why-is-it-stuck-on-my-mouse/18746 - DEC 2015

https://forums.sketchup.com/t/suggests-for-import/171985/4 - AUG 2021

... _etc_. ...

**Comment by thomthom** [comment]
I think it would be more generic and flexible if import created a new component definition only, leaving the insertion of an instance entirely to the API user.

**Comment by DanRathbun** [comment]
But that would drastically change the current workflow that automatically creates a new instance attached to the cursor with the MoveTool active.

And it also would mean adding a new hash option like `:place_instance = false` (`true` being the historical default.)

IMO, just having a `:transform` option is much more in keeping with the current method's usage.

----

Secondly, the loading of **non-SKP** file's into the `DefinitionList` should be an instance method on that class, not the model object. So, **if you must**, then ALSO extend the definitions collection's `#load` and `#load_from_url` methods with the common "under the hood" functionality to import 3rd party file formats.

**Comment by thomthom** [comment]
Yea, the whole import/load API need a clean look. Getting the option to tell `model.import` to not place an instance would be a good start. But with that we can then enhance `DefinitionList` as you say to allow for creation of only a new definition.

**Comment by DanRathbun** [comment]
> But with that we can then enhance `DefinitionList` as you say to allow for creation of only a new definition.

Julia [@Eneroth3](https://github.com/Eneroth3) pointed out today that she has already filed (and you've logged) the enhancement for the `DefinitionList` class to load non-SKP file formats as new definitions.

_SEE:_ #254 

So, this should be a separate but related (bundled) FR to specifically extend the [`Sketchup::Model#import`](http://ruby.sketchup.com/Sketchup/Model.html#import-instance_method) method. A transform argument should (like my ESC key hack example,) allow a `Geom::Transformation` or any object that can be used to create a new one "on-the-fly" such as a point, a vector, or array of at least 3 coordinates (implying a translation point.)

**Comment by DanRathbun** [comment]
@thomthom I call your attention to a forum comment you made in Jan of 2015 ...
https://forums.sketchup.com/t/script-not-waiting-after-importing/5353/2

**Comment by DanRathbun** [comment]
TIG mentions in the forum that a geolocated component SKP can also short-circuit the user place component tool on `model#import` (which sometimes can cause a BugSplat!)
https://forums.sketchup.com/t/bug-splat-problem-in-sketchup-2019/97110/8

It might be that some users may wish to suppress this geolocating when the `:transform` argument is given.

**Comment by DanRathbun** [comment]
> I think it would be more generic and flexible if import created a new component definition only, leaving the insertion of an instance entirely to the API user.

And so Thomas' idea has been implemented for 2021.1 as [`DefinitionList#import`](https://ruby.sketchup.com/Sketchup/DefinitionList.html). Doing so satisfied Issue #254 but not **this** issue.

----

Another [forum requester](https://forums.sketchup.com/t/suggests-for-import/171985) (for a transform argument) states that there is a huge time difference with [`DefinitionList#load`](https://ruby.sketchup.com/Sketchup/DefinitionList.html#load-instance_method) and [`DefinitionList#import`](https://ruby.sketchup.com/Sketchup/DefinitionList.html) versus [`Model#import`](http://ruby.sketchup.com/Sketchup/Model.html#import-instance_method).

**Comment by thomthom** [comment]
> Another forum requester (for a transform argument) states that there is a huge time difference with DefinitionList#load and DefinitionList#import versus Model#import.

Then I'd say the appropriate response to that is to look at the performance of `DefinitionList#load` and `DefinitionList#import`. Adding transform option to `model.import` doesn't seem meaningful to me.

**Comment by Eneroth3** [comment]
> Let us talk about the geolocated model problem for a minute. `model.import` automatically short-circuits manual placement and transforms the instance based upon geo-location.

`model.import` just triggers whatever behavior the UI is using. Today the it automatically places the component based on geo-location (if found). Tomorrow it there may be a popup asking what placement the user prefers. To me this is an argument to move away from it and use low level API methods with a clear and stable behavior.

Rather than having `model#import` do more things, it's better to have several small re-usable methods that can be combined as desired.

**Comment by thomthom** [comment]
> Rather than having model#import do more things, it's better to have several small re-usable methods that can be combined as desired.

+1 model#import is too tied up in invoking higher level UI logic.

**Comment by Eneroth3** [comment]
The same result can be achieved with with #254. Closing this.

**Comment by DanRathbun** [comment]
> @Eneroth3  _`model.import` just triggers whatever behavior the UI is using. Today it automatically places the component based on geo-location (if found). Tomorrow it there may be a popup asking what placement the user prefers. To me this is an argument to move away from it and use low level API methods with a clear and stable behavior._

> @thomthom : `_model#import` is too tied up in invoking higher level UI logic._

Okay ... **objectively** I cannot argue against this position.

The [guy](https://forums.sketchup.com/t/suggests-for-import/171985) who brought all this up again admits he is still running SU2019.  He seems to be satisfied with the ESC key "hack" I had posted years ago in the forum.

I had asked him specifically to compare the new `DefinitionLIst#import` against `Model#import`, and he indicated the former was still too slow in a large model. (But I've again asked how he could have really tested the new method.)

I find it strange that `Model#import` would be faster. Wouldn't the API seek to use the same core code for all 3 methods ?

**Comment by thomthom** [comment]
> I find it strange that Model#import would be faster. Wouldn't the API seek to use the same core code for all 3 methods ?

Yes, it would be unexpected. So without a good example to demonstrate this we don't really have much to go on.
