### ISSUE TITLE
SUMeshHelperRef on MacOS does not capture "cut opening" components

### ISSUE THREAD

**Issue by chegarty3** [SketchUp/api-issue-tracker#273]
Using C API, an SUMeshHelperRef created with SUMeshHelperCreate does not correctly handle "cut opening" components.
```
        SUMeshHelperRef polymesh = SU_INVALID;
	SUMeshHelperCreate(&polymesh, face);

	size_t vertex_count = 0, poly_count = 0;
	SUMeshHelperGetNumVertices(polymesh, &vertex_count);
	SUMeshHelperGetNumTriangles(polymesh, &poly_count);
```
[cut wall test 2017.zip](https://github.com/SketchUp/api-issue-tracker/files/3273431/cut.wall.test.2017.zip)

For a simple rectangle face (skp attached) with a simple rectangle opening.
On Windows 10 the result correctly produces 8 vertices and 8 triangles that represent a cut in a simple face.
On MacOS, the result produces 4 vertices and 2 triangles representing only the uncut face and no representation of the cut at all.

**Comment by thomthom** [comment]
See my comment in #274:

https://github.com/SketchUp/api-issue-tracker/issues/274#issuecomment-502083405
