### ISSUE TITLE
Documentation suggesting use of hard-coded values when there are constants available

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#277]
In the Ruby Importer interface documentation [load_file ](http://ruby.sketchup.com/Sketchup/Importer.html#load_file-instance_method)has a few explicitly listed return values. A better practice is to use the constants that you can easily tell what they mean from their names when reading the code, and the method documentation should reference these.

I'm quite sure there are more places like this in the documentation.

**Comment by DanRathbun** [comment]
... and mention might be made that the [`Sketchup::Importer`](http://ruby.sketchup.com/Sketchup/Importer.html#constant_summary) class constants are inherited if the coder's class is a subclass. So then there'd be no need for full qualification, just the local constant name can be used.

The class' main example's `load_file` method ...
```ruby
  # This method is called by SketchUp after the user has selected a file
  # to import. This is where you do the real work of opening and
  # processing the file.
  def load_file(file_path, status)
    UI.messagebox(file_path)
    return ImportSuccess # 0 is the code for a successful import
  end
end
```

The `load_file` method's example ...
```ruby
def load_file(file_path, status)
  # Here is where you would open the file and process it.
  UI.messagebox(file_path)
  return ImportSuccess # 0 is the code for a successful import
end
```

The `load_file` method's **Returns** string should have a link to the constants section **instead** of saying "See above". Ie ...
http://ruby.sketchup.com/Sketchup/Importer.html#constant_summary

**Comment by thomthom** [comment]
Yea - magic values are not good. All docs should be updated to use them whenever possible. And if any are missing there should be new constants added.

**Comment by Eneroth3** [comment]
This might be a bug and not just a documentation issue. The class constants and the magic numbers defined in the instance method documentation do not match :( .

#load_file method documentation

- 0 = Import Success (no additional dialog shown)
- 1 = Import Failed (no additional dialog shown)
- 2 = Import Cancelled by User (SketchUp will show a "cancelled" dialog)
- 4 = Import File not Found (SketchUp will show a "not found" dialog)
- 5 = SketchUp version not supported (no additional dialog shown)


Class constant summary

Sketchup::Importer::ImportSuccess # => 0
Sketchup::Importer::ImportFail # => 1
Sketchup::Importer::ImportCanceled # => 2
Sketchup::Importer::ImporterNotFound # => 3 (Dos not match the documentation above!)
Sketchup::Importer::ImportFileNotFound # => 4 (Dos not match the documentation above!)

I'm not sure what values SketchUp expects from this interface.

**Comment by thomthom** [comment]
Then it's probably the #load_file documentation that is wrong. (Maybe it was correct at some point, but that's why we should be using named identifiers instead of magic numbers.)

**Comment by Eneroth3** [comment]
I've taken another look here and I must have had an off by one error when reading these before.

#load_file accepts a status code that has no constant while the class constant summary includes a value that to me appears to be for internal use.

I don't know if `Sketchup::Importer::ImporterNotFound` should be removed from the docs. For the 5 status code I'm not sure what is best either. Maybe it's best to add the constant but marking it as a 202X addition? I don't know if SU even handles this status code any differently from 2, or if it was added so it could be implemented in the future.

I'm also a bit confused about the UX design here. If the user presses cancel, why would you want a message telling them they cancelled? They already know that. If I were to implement this API myself, I'd probably make sure to return `Sketchup::Importer::ImportFail` on user cancellation, even if it's outside the API contract, just to get rid of a weird popup message.

**Comment by thomthom** [comment]
I agree, `Sketchup::Importer::ImporterNotFound` doesn't seem meaningful for API users. We should probably remove that. (At the very least hide it.)

The other values are valid and the docs should refer to them instead of magic values.

Value `5` the docs refer to is bogus, no internal status code that uses such a value. Maybe it was something in the past, but I'm not seeing anything in today's source.
