### ISSUE TITLE
ComponentDefinition#save taking version parameter

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#28]
Model.save takes two parameters, the path and the SketchUp version for the file. It would be highly appreciated if ComponentDefintiion.save_as also could take a version argument.

This would allow for developing tools that helps users share data, even if they are on different versions.  Currently users may be reluctant to update until everyone else they work with has done so.

**Comment by thomthom** [comment]
Logged as SU-38575

**Comment by Whaat** [comment]
I also would very much like to see this feature added to the API.  It would allow creation of a simple script to perform a batch save of all components as an older version of SketchUp.  This is very useful for people who create component libraries for SketchUp users who may all be using different SketchUp versions.

**Comment by DanRathbun** [comment]
Implemented in 2022.0 (API 10.0) release:

* Ruby API: [`Sketchup::ComponentDefinition#save_as`](https://ruby.sketchup.com/Sketchup/ComponentDefinition.html#save_as-instance_method) - added `version` argument

* C API: [`SUComponentDefinitionSaveToFile()`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_component_definition_ref.html#a98735078e64bf09c9f6ff04d295b9b88) - initial implementation
