### ISSUE TITLE
UI::Notification always shows 2 buttons when only 1 is called for

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#280]
#### Bug Report

1. SketchUp/LayOut Version: 2018
2. OS Platform: Windows 10

`UI::Notification` always shows 2 buttons when only 1 is called for.

Expect only one button to show when calling for only 1 button.

```ruby
  notification = UI::Notification.new(
    Sketchup.extensions[0],
    "This is test notification with a sample warning.",
  )
  notification.on_accept("OK") do |notification, title|
    puts "Sample output message to console."
  end
  notification.show
```

**Comment by Eneroth3** [comment]
It can also show 0 buttons.

```ruby
 notification = UI::Notification.new(
    Sketchup.extensions[0],
    "This is test notification with a sample warning.",
  )
  notification.show
```

**Comment by DanRathbun** [comment]
No buttons should not be an issue. (Meaning, it is one of the class' paradigms.)
The message just shows and then slides away when the timer runs out. (Setting the timer is a request that is separately logged and tracked.

**Comment by DanRathbun** [comment]
Again, this was fixed prior to 2019.2 sometime. And release notes still do not mention it.

**Comment by thomthom** [comment]
These fixes where made by the client team without the API team knowing they where fixed. We only just verified it was fixed for the SU2019.2 release and our script that closes out marks issues with the latest release.

**Comment by thomthom** [comment]
Anyone recall if it was fixed in SU2019.0 or SU2019.1?
