### ISSUE TITLE
Sketchup::Edge.faces returns empty array, not false

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#284]
see https://msp-greg.github.io/su/Sketchup/Edge.html#faces-instance_method

The lines in the comment:

https://github.com/SketchUp/ruby-api-stubs/blob/master/lib/sketchup-api-stubs/stubs/Sketchup/Edge.rb#L170-L171

A quick check with SU2019 showed that a line with no faces returns an empty array, not false

**Comment by DanRathbun** [comment]
Official docs link:
http://ruby.sketchup.com/Sketchup/Edge.html#faces-instance_method

Checked using ...
```ruby
edge = Sketchup.active_model.entities.add_line([0,0,0],[100,100,0])
faces = edge.faces
faces.inspect
```
Checked 2016: returns empty array
Checked 2017: returns empty array
Checked 2018: returns empty array
Checked 2019: returns empty array

----
