### ISSUE TITLE
SUModelCreateFromFile in ruby extension shows Validity Check dialog

### ISSUE THREAD

**Issue by kengey** [SketchUp/api-issue-tracker#285]
I am creating a ruby c extension that in return links in the c sdk (2019) to open external .skp files. It seems that from time to time a dialog pops up stating there were errors in the opened model, but, that "everything is OK now"...

![image](https://user-images.githubusercontent.com/5702720/60341719-c0885f00-99af-11e9-8298-7147aba55cde.png)

There seem to be a few errors with the persistent ids:
![image](https://user-images.githubusercontent.com/5702720/60341706-b49c9d00-99af-11e9-8970-631001beecc0.png)

I was wondering if there is a way to suppress that dialog? Although my SketchUp settings indicate that new models should not be checked for errors..
![image](https://user-images.githubusercontent.com/5702720/60341782-f1689400-99af-11e9-866c-7e3d4377004b.png)

The dialog is shown immediatly after calling `SUModelCreateFromFile`, or actually, during the call to that function.
```c
SUResult result;
SUModelRef model = SU_INVALID;
result = SUModelCreateFromFile(&model, skpFilePath.c_str());
```

Is there a separate setting in the SDK to suppress that dialog?

**Comment by kengey** [comment]
It seems this was caused by my also linking in `sketchup.lib`. Removing this link made the dialog disappear.

**Comment by thomthom** [comment]
> It seems this was caused by me also linking in sketchup.lib. Removing this link made the dialog disappear.

When using the C API you should use `sketchup.lib`. You should *not* link against SketchUpAPI.lib for the live C API. That will lead to unexpected behavior, quite likely crashes.

**Comment by DanRathbun** [comment]
Ref https://github.com/SketchUp/api-issue-tracker/issues/291 for the Ruby API.
