### ISSUE TITLE
 sketchup 2019 SDK Don't work with UE4 project

### ISSUE THREAD

**Issue by ogking** [SketchUp/api-issue-tracker#286]
Bug Reports
1. SketchUp/LayOut Version:  sketchup 2019 SDK
2. OS Platform: win10 64bit

Describe briefly what you are doing and what is happening.
I want to use sketchup 2019 SDK in UE4 to operate skp files by the CAPI, which I have done successfully with 2018 SDK. when I update sdk with 2019, it went all right when i compile my ue4 project. But when I Run it, it crashes with error like belows:
LogWindows:   Missing import: skecthup.exe
LogWindows:   Missing import: CONCRT140.dll

Please be free to contact me with my gmail : 799972@gmail.com for my test project

**Comment by ogking** [comment]
My company for pay for the right answer

**Comment by ogking** [comment]
Below is what I get when I debug with Dependency Walker, I will be happy if anyone give some hints 
![image](https://user-images.githubusercontent.com/10610965/60708865-9e5b8780-9f41-11e9-9e8b-a55120de1955.png)

**Comment by ogking** [comment]
I did this by myself......

**Comment by prachtan** [comment]
Did you used a proper lib? there are two libs, for LiveCAPI _(that is designed for plugins worked with SketchUp - `sketchup.lib`)_ and "stand-alone" version `SketchUpAPI.lib` of CAPI which is dynamically linked with `SketchUpAPI.dll` and `SketchUpCommonPreferences.dll` (both dlls are required.
