### ISSUE TITLE
View#guess_target extremely slow on Mac

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#299]
`t = Time.now; Sketchup.active_model.active_view.guess_target; Time.now - t`

On Windows this line of code reports it takes 0.005291 or so seconds to find what the user is looking at in a moderately sized model (~100 000 faces). On Mac however this takes around 1.5 seconds for the same model, nearly 300 times as long.

I'm implementing some custom camera tools and the target, or distance to it, is required for defining the pan and zoom speeds. Using a fixed value is not an option as it would make the camera appear to stand still when panning around a big object or be super fast around a small one.

More or less the same operation is used within native Zoom tool but with no noticeable delay, suggesting this is a bug and not the just computer being slow.

Using SketchUp 2018 on a MacBook Pro with macOS High Sierra Version 10.13.6.

**Comment by Eneroth3** [comment]
Good news: This appears to be fixed in SketchUp 2019!

**Comment by thomthom** [comment]
Interesting... that's a significant difference... But glad it's fixed!
