### ISSUE TITLE
Its not ideal that SUMaterialInput require vertex references

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#319]
https://forums.sketchup.com/t/supoint2d-uv-coords-4-only-support-4-uv-coords/101281/4?u=tt_su

There is a design quirk with the C API what IMO makes it a bit more challenging to work with textures than the Ruby API.

The Ruby API doesn’t force you to provide 3d world points that match the vertices of the face - they just need to be on the plane of the face.

The C API for some reason (this function was added before my time) expects the input points to be anchored to the vertices of the face. This forces some extra calculations to be made in some cases to position the texture exactly where you want.

If you are writing an importer from another format what provide UV coordinates you can use just the first four and discard the rest. SketchUp computes the transformation matrix based on those four points. The catch is that you could have cases where the first four vertices of a face might be co-linear. So to be robust you want to pick a set of points that doesn’t form a degenerate triangle or quadrilateral.

It would be good to have a way to define UV mapping in the C API that was more akin to the Ruby API and the UI in that the 3d world point only has to be on the plane of the face. (Ruby API will project any point to the plane.)

**Comment by DanRathbun** [comment]
Implemented via a new struct [`SUMaterialPositionInput`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_material_position_input.html) which supersedes the now deprecated [`SUMaterialInput`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_material_input.html) struct.
