### ISSUE TITLE
SULoopInputEdgeSetSmooth affects the whole face loop

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#322]
I think I recently found a bug in `SUGeometryInput` when setting the smooth flag.

https://github.com/thomthom/assimp/blob/8c5e6a6906f611fcb1267d8fed66b61d3b25c987/code/SKP/SkpExporter.cpp#L492-L495

https://github.com/thomthom/assimp/blob/8c5e6a6906f611fcb1267d8fed66b61d3b25c987/code/SKP/SkpExporter.cpp#L419-L431

I ended having to do a post-pass to correct it.

**Comment by taustin73** [comment]
SKOR-11817

**Comment by thomthom** [comment]
No bug in the API. It was an error on the user-side. The different behaviour of SULoopInputEdgeSetSoft lead to the confusion.
