### ISSUE TITLE
Layout::SketchUpModel#bounds= method missing

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#325]
#### LayOut Ruby API Issue

**[`Layout::SketchUpModel`](http://ruby.sketchup.com/Layout/SketchUpModel.html) has no _obvious_ method to resize the viewport bounds once created**.

I'm not sure but can this be done (since it is a `Layout::Entity` subclass object,) using the [`#untransformed_bounds=`](http://ruby.sketchup.com/Layout/Entity.html#untransformed_bounds=-instance_method) method ?

----

If not, the only workaround would be to recreate the [`Layout::SketchUpModel`](http://ruby.sketchup.com/Layout/SketchUpModel.html) object, IF the path can be known.
Ie ...
```ruby
doc = Layout::Document.open("C:/path/to/document.layout")
this_page = doc.pages.first
entities  = this_page.nonshared_entities
old_model = entities.grep(Layout::SketchUpModel).first
old_bounds = old_model.bounds
new_bounds = Geom::Bounds2d.new(
  old_bounds.upper_left.x, old_bounds.upper_left.y,
  old_bounds.width + 0.5,  old_bounds.height + 0.5
)
new_model = Layout::SketchUpModel.new( old_model.path, new_bounds )
layer = old_model.layer_instance
doc.remove_entity(old_model)
doc.add_entity( new_model, layer, this_page )
model.render if model.render_needed?
doc.save
```
... however, there currently is no `#path` method for the [`Layout::SketchUpModel`](http://ruby.sketchup.com/Layout/SketchUpModel.html) object.

* [Issue #324: Layout::SketchUpModel#path method missing](https://github.com/SketchUp/api-issue-tracker/issues/324)

**Comment by taustin73** [comment]
SU-44283

**Comment by ackarkka** [comment]
The proper way to transform an entity such as a [Layout::SketchupModel](http://ruby.sketchup.com/Layout/SketchUpModel.html) is with the [transform!](http://ruby.sketchup.com/Layout/Entity.html#transform!-instance_method) method.

**Comment by thomthom** [comment]
@ackarkka  - does this mean we consider it a "wont-fix"?
It would fit SketchUp API as well, where bounds are read-only. And you change it via `transform` or `transformation=`.

**Comment by ackarkka** [comment]
Yes, I would consider this a wont-fix.

**Comment by DanRathbun** [comment]
> The proper way to transform an entity such as a **`Layout::SketchupModel`** is with the **`transform!`** method.

Doh! Didn't notice this.

> It would fit SketchUp API as well, where bounds are read-only. And you change it via `transform` or `transformation=`.

Y'all never answered the general question what and why is there an [`#untransformed_bounds=`](http://ruby.sketchup.com/Layout/Entity.html#untransformed_bounds=-instance_method) setter method and what is it for.

Secondly would it be wise to then change this request to a documentation issue, so as to add a note to the `Layout::SketchupModel` class introduction that the `#transform!` method should be used to change the location and size of the viewport.

**Comment by DanRathbun** [comment]
@thomthom Please reopen and label as documentation to add a paragraph to the class introduction pointing readers to `#transform!` for resizing a viewport's bounds.
