### ISSUE TITLE
Why does Sketchup::Entities#transform_entities() return boolean ?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#327]
#### SketchUp Ruby API Question

**Why does [`Sketchup::Entities#transform_entities()`](http://ruby.sketchup.com/Sketchup/Entities.html#transform_entities-instance_method) return boolean ?**

Under what condition does it return **`true`** ?
Why would it ever return **`false`** ?

**A method like this should just return the collection object for call chaining.**

Any errors should raise exceptions that can be trapped with a **`rescue`** clause.

~

> **UPDATE**: The result of discussion below is that the **`false`** return reason should be added to the documentation.
> But it is thought to be too late to change return type for this method.

!

**Comment by thomthom** [comment]
It'll return false if:

* if `sub_entities` parameter is empty

...that appear to be it.

**Comment by DanRathbun** [comment]
**That is SILLY!** That should raise an **`ArgumentError`**.
 No one is going to write code that omits a required parameter.

And it should as I said just return the collection to allow call chaining. 
Changing this should not effect any code "in the wild".

Please log this as either a bug or enhancement.

**Comment by thomthom** [comment]
> No one is going to write code that omits a required parameter.
I meant that the `sub_entities` array is empty - which is a plausible scenario that shouldn't raise an error.

**Comment by DanRathbun** [comment]
**I disagree!** An empty array is the same as an empty parameter list (the method can take either a list or an array of the expected object types.)
Other places (methods) in the API an error is raised when an empty array is passed and the method expects objects in the array, or a single argument to be the type of object expected.

So either an `ArgumentError` or a `TypeError`.

It is not "Rubyish" to use boolean returns like this instead of errors.
In fact, this is the scenario where bang methods are used.
Ie, `Sketchup::Entities#transform_entities!` would return the changed object, or `nil` if unchanged. Whereas the non-banged method always returns the collection object.

Anyway, if you want to allow lazy coding that can transform a set of entities if populated, or silent do nothing if the set is empty, then **fine** let it silently do nothing, and return the collection object. 

**It makes no good coding sense to return boolean as a coder can just test their set of entities before the call, and know if the set is empty that the call will do nothing.**

Again, the Ruby way to return a notification of "nothing done" is via a banged edition of the method.

**Comment by thomthom** [comment]
There's a bunch of inconsistencies from common Ruby convention. But we're more of less stuck with it now.

There is some wiggle room though, the boolean return value doesn't appear to be that useful so making the methods return itself for chaining probably would be fine.

But adding errors to empty arrays at this point might break things. Someone might be doing a grep for selected faces to transform and currently that's a harmless noop. Not unlikely some extension have such a scenario.

Regardless of how seemingly small an inert a change is there is always a chance someone is using it in some way that you didn't expect. That increase the risk factor for such changes when managing an API.

**Comment by DanRathbun** [comment]
Also (documentation wise) the **transform** argument will take a `Geom::Vector3d` or a 3 element `Array` object as an implied translational transformation.

Would it be beneficial to document this in such methods that allow this, or a more general note in vector and array class overview paragraphs ?

**Comment by thomthom** [comment]
> Also (documentation wise) the transform argument will take a Geom::Vector3d or a 3 element Array object as an implied translational transformation.
>
> Would it be beneficial to document this in such methods that allow this, or a more general note in vector and array class overview paragraphs ?

I think this is best to be documented in the Point3d and Vector3d class documentation. Perhaps in some general concept page.

Adding the array variant overload to all signatures makes the documentation very noisy very quickly. Also makes the signature harder to read:

```ruby
# @param [Geom::Vector3d, Array(Numeric, Numeric, Numeric)] param_name Some possibly verbose description here
# @param [Array<Geom::Vector3d, Array(Numeric, Numeric, Numeric)>] param_name Some possibly verbose description here
```

In which case I think it's easier to read the purpose of the param by omitting the implicit array conversions:

```ruby
# @param [Geom::Vector3d] param_name Some possibly verbose description here
# @param [Array<Geom::Vector3d>] param_name Some possibly verbose description here
```

**Comment by DanRathbun** [comment]
Created new issue. (See link referenced above.)
