### ISSUE TITLE
Update SelectionObserver documentation

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#330]
Documentation needs updates about events which are claimed to be unused - but in reality used by Ruby. 

There's also been some typos in the events called, should fill in this information.

**Comment by DanRathbun** [comment]
What was specifically updated ? (I do not see any change.)

In addition, the problems described in forum topic:
https://forums.sketchup.com/t/observers-and-the-outliner/143429
... are still present. (Ie the note in [`#onSelectionAdded`](https://ruby.sketchup.com/Sketchup/SelectionObserver.html#onSelectionAdded-instance_method) is erroneous for **single** items selected with the Outliner.)

**Comment by thomthom** [comment]
Here is the diff: https://github.com/SketchUp/ruby-api-docs/commit/55e53650edbb5733e3e38495b8f7efd73e6fca01#diff-f1cac1c7e20ebd43bb50da020afe386feb6c43a29e836056dad089104f52f4dd

Would you mind filing a new issue for `onSelectionAdded` event? (I don't recall the details right now)

**Comment by DanRathbun** [comment]
> Would you mind filing a new issue for `onSelectionAdded` event? (I don't recall the details right now)

Logged Issue #603
