### ISSUE TITLE
SU 2018 Tools\RubyStdLib\platform_specific\cacert.pem from when?

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#34]
Cert dates - Wed Sep  3 03:12:03 2014?  Really?

Three times a day, ssl folder in ruby_trunk.7z on [Appveyor](https://ci.appveyor.com/project/MSP-Greg/ruby-loco/build/artifacts).  Time stamp as of this post was `2018-01-25 03:12:13 UTC` in build `ruby 2.6.0dev (2018-01-25 trunk 62035) [x64-mingw32]`

Thanks, Greg

**Comment by thomthom** [comment]
I recall that wen we updated to Ruby 2.2 we originally updated the cart file. But we found, close to release, that HTTPS calls failed. Not sure why, but the old cert file continued to work.

**Comment by MSP-Greg** [comment]
Odd.  That shouldn't happen.  I'll close.

**Comment by thomthom** [comment]
Yea, it's strange. I would like to revisit and understand what is going on though.

**Comment by MSP-Greg** [comment]
@thomthom

As mentioned elsewhere, RubyInstaller/MSYS Ruby builds do not correctly set `OpenSSL::X509::DEFAULT_CERT_FILE`.  Newer MSYS2 OpenSSL packages/dll's (used by RubyInstaller2/MSYS2 builds, including ruby-loco) set this to a folder relative to the exe running the OpenSSL dll's.

When in SU, try `require 'openssl' ; OpenSSL::X509::DEFAULT_CERT_FILE`, and you'll see the path to the OpenSSL package that was used when Ruby OpenSSL was built.  Obviously, not portable...

So, the only option is to set `ENV['SSL_CERT_FILE']` to its path.

For a look at how various Appveyor Ruby versions are configured, see https://ci.appveyor.com/project/MSP-Greg/appveyor-ruby.  You'll notice that all the old builds have 'file not found' for `X509::DEFAULT_CERT_FILE`.

Thanks, Greg

**Comment by MSP-Greg** [comment]
Sorry for the above post, as one might say I had the wrong hat on.

First of all, regardless of issue with OpenSSL functioning correctly, SU should ship with a current pem file, a it is a 'trusted' file and is used to verify connections.

Regarding  the other ssl issues, these may be Windows specific.

**Brief Summary of 'Ruby for Windows'**

Ruby core is essentially a set of C files written to run on Linux or derivatives.   Over time, they have been made compatible with MSVC, so the core files can be compiled (and recently, fully tested) using Microsoft build tools.

Ruby is not the only language meant to run on Linux, so along the way, 'build translation and package' systems developed that allowed Linux code to be built on Windows.  MSYS / MinGW / MSYS2 are all systems that allow one to accomplish this.  These systems are composed of runtime files, compilers, and packages (like OpenSSL) that can be used when building/compiling.

I believe all of the Ruby 2.x versions used in SU have been what I refer to as RubyInstaller builds.  these used the MSYS system for building, and used proprietary packages.  The last build RubyInstaller release was Ruby 2.3.3, released in Dec 2016.

MSYS2 is the successor to MSYS.  Several people started working on Ruby build systems using MSYS2, and out of that came RubyInstaller2, which is used for the current Ruby releases, and ruby-loco, which builds trunk and is used for testing.  These systems largely rely on existing MSYS2 packages, so maintenance is shared by a community larger than just the Ruby community.

It is my hope that the Trimble team will consider using an MSYS2 Ruby build for the next release of SU Windows, as the newer releases are now being tested and monitored by the ruby-core team.

I haven't gone crazy digging into old posts, but the older RubyInstaller builds had so many testing issues that the resources weren't available to get thru finding and fixing them.

Again, sorry for throwing out all the (possibly unfamiliar) terms.  I'm rather active in the 'Ruby Windows build community', and also spend time trying to make Ruby (and Ruby gems) function better, with a emphasis on Windows...

As to why I'm here - I was introduced to Ruby via SketchUp 8, and today, from a builder's perspective, embedded Ruby has a set of issues that don't exist in stand-alone.

Thanks, Greg

**Comment by BugraBarin** [comment]
Thanks Greg, lots of useful info there that I didn't know. Is this where we should get the new builds then?
[](https://github.com/oneclick/rubyinstaller2)

Getting newer versions of Ruby to be embedded in an app like SketchUp has been a frustrating experience with lots of unsavory workarounds. As a result, lots of things just don't work in SketchUp since most things in Ruby appear to have been designed for a console-based scripting environment (understandably). We aren't experts in building Ruby so we appreciate all the help.

**Comment by MSP-Greg** [comment]
I'd like to hope that things are better now, but since you're using the ABI more than the API, jumping versions may prove trying...

The short answer is current standard releases are available https://rubyinstaller.org/

I suspect so, but I thought I'd confirm, are you 'user' bugra at forums.sketchup.com?

Thanks, Greg

**Comment by BugraBarin** [comment]
> I suspect so, but I thought I'd confirm, are you 'user' bugra at forums.sketchup.com?

I sure am. I am not on the API team these days but I worked on the initial Ruby upgrade to 2.0 so I'm familiar with the pain points.
thanks!

**Comment by MSP-Greg** [comment]
> As a result, lots of things just don't work in SketchUp since most things in Ruby appear to have been designed for a console-based scripting environment (understandably).

Familiar with that.  From my involvement with trunk testing, I got very familiar with test code.  Much of the command-line oriented ruby code is tested within script, as opposed to 'shelling out', which requires spinning up another ruby instance.  There are often issues with trapping io, and I've run into them using some things in SU (and its console).  Then again, the test code often uses io mapping.

So, if one really needs to get what would normally be command line functionality running in script, test code is a good place to look for pointers...

**Comment by thomthom** [comment]
Logged as SU-38584
