### ISSUE TITLE
Request for documentation of SketchUp's Validity Check rules

### ISSUE THREAD

**Issue by rickmas** [SketchUp/api-issue-tracker#343]
I would like to be able to refer to a list of documented rules in use by SketchUp's validity checker.  This documentation would provide information for developers to be able to create geometry without triggering the various validation errors.

For example, I was not aware that you can't have two curve loops connected by one vertex.  If you attempt this scenario, SketchUp's Validity Check will 'fix' this by removing the curve attributes from edges of one of the loops.

I've provided more detail (including a coding example) for this scenario in the [community forum](https://forums.sketchup.com/t/are-there-documented-rules-for-creating-joining-geometry-via-ruby-script/105029).

Currently when a validity check is triggered, you'll need to decipher the message and spend a considerable amount of time depending on your project size to figure out the root cause.  Once you determine the root cause, you then need to dream up a bunch of scenarios to deduce what will or won't trigger the validity issue and create test cases to validate.  All this could be avoided if we simply knew what was allowed/not-allowed.

**Comment by thomthom** [comment]
That would be a massive document and a real challenge to keep up to date.

However, there shouldn't be any need for this as the APIs should not allow you to create invalid state in the model. Instead I think we should be focusing on fixing reports of scenarios that can create invalid model state.

**Comment by thomthom** [comment]
@rickmas  Can you make sure to file separate tickets for any scenario you have found that might trigger invalid models?

**Comment by rickmas** [comment]
@thomthom , yes, I will do that AND should I assume going forward that anytime the validity checker finds an issue that this is a potential bug?  

I admit that I was assuming that my scenario was a 'by design' type issue and so I was trying to work around it and all similar issues which was why I wanted the documentation.  However, if these are bugs then I agree with you that the validity check rule documentation is not necessary.

I will log another issue shortly for the scenario I initially brought up in the community forum.

**Comment by thomthom** [comment]
> I assume going forward that anytime the validity checker finds an issue that this is a potential bug?

Yes. SketchUp shouldn't let you create invalid models from the UI or the API. However it's in place because it can correct malformed models caused by bugs in older SketchUp versions. And it also acts as a sanity filter to detect existing bugs by making sure the model is in an expected state.
