### ISSUE TITLE
let CEF run in its own thread

### ISSUE THREAD

**Issue by kengey** [SketchUp/api-issue-tracker#347]
Not a real issue, more a feature request: Wondering how hard it would be to let CEF run in its own thread. It would solve so many UX issues.

**Comment by thomthom** [comment]
Each CEF window has its own process. You can see this on Windows for instance by observing the `sketchup_webhelper.exe` processes.

Can you elaborate more on what the issue is? We need to have context for changes we do to be able to verify the approach is actually solving the issue.

**Comment by kengey** [comment]
Ok. I noticed that, a large model that slows down sketchup's own animation, also slows down animation in an HtmlDialog. Would there be some mutex that syncs both threads? If you open the standard 3d warehouse dialog, open the ruby console and `sleep 50 `, then the HtmlDialog becomes unresponsive to.

**Comment by thomthom** [comment]
Yea, there probably is a message pump that cause what you observe.

The underlying use case here is creating a progress bar/indicator?

**Comment by kengey** [comment]
> The underlying use case here is creating a progress bar/indicator?

Correct, that was my underlying use case. But it should improve overall user experience.

**Comment by DanRathbun** [comment]
> Yea, there probably is a message pump that cause what you observe.

On PC it's the `PeekMessage` calls that must be called frequently. When they stop after a timeout setting (in the registry) the Task manager puts the application into "Not responding" mode.

If the HtmlDialog windows are child windows of the SketchUp application window then the slow down and locking are expected.

@thomthom Didn't you add a message peeking function to one of your old libraries ?

**Comment by thomthom** [comment]
It's not the Windows message pump I'm referring to. CEF windows are running in separate processes so there is some process messaging system in play here.

**Comment by kengey** [comment]
seems to be working great in SU22

**Comment by DanRathbun** [comment]
> Maybe that related to the CEF update in SU2022.

FYI: Displaying my CEF version dialog SxS shows that the CEF version is the same as in **2021.1**, ie v88.
So the "fix" label is probably incorrect.
