### ISSUE TITLE
How to make Geometric Helper Functions for C API (discussion)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#353]
#### How to implement Geometric Helper Functions for C API ?

Following along after [Issue #352 : Predefined Geometric Helper Constants](https://github.com/SketchUp/api-issue-tracker/issues/352)

The API could use some helper "getter" functions. These were my first ideas ...

```c
// Examples:


    // Return a new 3D point at the given coordinates.
    struct SUPoint3D SUPoint3D_new(double x, double y, double z) {
        struct SUPoint3D point = { x, y, z };
        return point;
    }

    // Return a new 3D vector given the coordinates.
    struct SUVector3D SUVector3D_new(double x, double y, double z) {
        struct SUVector3D vec = { x, y, z };
        return vec;
    }


    // Return a new 3D vector along the given axis vector of length.
    // Can pass in axis constant or some other SUVector3D.
    struct SUVector3D SUVector3D_len(SUVector3D axis, double length) {
        switch( axis ) {
        case SU_X_AXIS:
            struct SUVector3D vec = { length, 0.0, 0.0 };
            break;
        case SU_Y_AXIS:
            struct SUVector3D vec = { 0.0, length, 0.0 };
            break;
        case SU_Z_AXIS:
            struct SUVector3D vec = { 0.0, 0.0, length };
            break;
        default:
            // copy the given vector and assign new length
            struct SUVector3D vec = axis;
            result = SUVector3DSetLength(&vec, length);
            if (result == SU_ERROR_NONE) { return SU_INVALID; }
        }
        return vec;
    }

    // Return a new unit vector along the given axis vector.
    // Can pass in axis constant or some other SUVector3D.
    struct SUVector3D SUVector3D_unit(SUVector3D axis) {
        switch( axis ) {
        case SU_X_AXIS:
            struct SUVector3D vec = SU_X_AXIS;
            break;
        case SU_Y_AXIS:
            struct SUVector3D vec = SU_Y_AXIS;
            break;
        case SU_Z_AXIS:
            struct SUVector3D vec = SU_Z_AXIS;
            break;
        default:
            // copy the given vector and assign new unit length
            struct SUVector3D vec = axis;
            result = SUVector3DSetLength(&vec, 1.0);
            if (result == SU_ERROR_NONE) { return SU_INVALID; }
        }
        return vec;
    }


    struct SUTransformation SUTransformation_identity() {
        struct SUTransformation identity_3d;
        identity_3d = SU_IDENTITY; // copy members of other struct
        return identity_3d;
    }

```

Any other ideas ?

**Comment by thomthom** [comment]
I'm not seeing the benefit of this:
```cpp
    // Return a new 3D point at the given coordinates.
    struct SUPoint3D SUPoint3D_new(double x, double y, double z) {
        struct SUPoint3D point = { x, y, z };
        return point;
    }
```

Over this:
```cpp
SUPoint3D point{ x, y, z };
```

`SUPoint3D_new` is doing the same thing, but wrapped in a function and also doing an intermediate copy instead of directly initializing the struct.

Same thing for `SUVector3D_new`.

If we have the constants for the identity structs then

```cpp
struct SUTransformation SUTransformation_identity() {
        struct SUTransformation identity_3d;
        identity_3d = SU_IDENTITY; // copy members of other struct
        return identity_3d;
    }
```

**Comment by DanRathbun** [comment]
The idea was that they are "getter functions". Just an idea for completeness. Perhaps not needed.

Ie readability ...
```c
SUTransformation trans = SUTransformation_identity();
```
I realize however that defining and maintaining a function when core C is more concise is desirable.

Perhaps an example in the class heading of the C docs (once the global constants get defined) would suffice to teach new API users how to get and initialize new transforms, points and vectors ?

**Comment by thomthom** [comment]
The switch in this appear redundant:

```cpp
    // Return a new 3D vector along the given axis vector of length.
    // Can pass in axis constant or some other SUVector3D.
    struct SUVector3D SUVector3D_len(SUVector3D axis, double length) {
        switch( axis ) {
        case SU_X_AXIS:
            struct SUVector3D vec = { length, 0.0, 0.0 };
            break;
        case SU_Y_AXIS:
            struct SUVector3D vec = { 0.0, length, 0.0 };
            break;
        case SU_Z_AXIS:
            struct SUVector3D vec = { 0.0, 0.0, length };
            break;
        default:
            // copy the given vector and assign new length
            struct SUVector3D vec = axis;
            result = SUVector3DSetLength(&vec, length);
            if (result == SU_ERROR_NONE) { return SU_INVALID; }
        }
        return vec;
    }
```

This should do the same thing:

```cpp
    // Return a new 3D vector along the given axis vector of length.
    // Can pass in axis constant or some other SUVector3D.
    struct SUVector3D SUVector3D_len(SUVector3D axis, double length) {
         struct SUVector3D vec = axis;
         SUResult result = SUVector3DSetLength(&vec, length);
         if (result == SU_ERROR_NONE) { return SU_INVALID; }
        return vec;
    }
```

And it doesn't seem appropriate to convert all error cores into `SU_INVALID`. And the result isn't even propagated to the caller. Seems to me it's simpler (and gives more information for errors by using the API directly:

```cpp
    SUVector3D vec = SU_X_AXIS;
    SUVector3DSetLength(&vec, length);
```

What I think would be more useful to the C API is the utility methods from the Ruby `Geom` module:
http://ruby.sketchup.com/Geom.html

**Comment by thomthom** [comment]
> Perhaps an example in the class heading of the C docs (once the global constants get defined) would suffice to teach new API users how to get and initialize new transforms, points and vectors ?

Initializing data in C/C++ is rather fundamental to the language which we expect the user to be familiar with. Similar to how we in the Ruby API docs we don't teach the basics of Ruby.

We could benefit by more C API examples, and that might mitigate some of this.

There's also the C++ and C# wrappers that the community is creating. Those makes interacting with the C API more familiar to those coming from Ruby and used to OOP. C++ and C# wrappers also provides some more room to have more utility functions for things like this. 

For instance, a C++ wrapper can provide overloads for functions/methods/constructors that is more convenient to use.

For my own projects I've often copied and pasted some utility functions to do common things, such as getting `std::string` from `SUStringRef`. And I've been wanting to put that into a helper library. And I think that a wrapper (C++) would be a good place for that. Something that is open source and the community can contribute to independent from the C API releases.

**Comment by DanRathbun** [comment]
> and gives more information for errors by using the API directly:

Yea perhaps. I just love OOP and hate the "clunkyness" of C where everything takes 3 to 4 times more statements t accomplish.

I was thinking of one line setter statements ...
```c
SUVector3D my_vec = SUVector3D_len(SU_X_AXIS, 3.14156);
```

BUT You made me realize that if `SU_INVALID` was returned and the code is expecting a `SUVector3D` we get an untrapped error.

**Comment by DanRathbun** [comment]
> There's also the C++ and C# wrappers that the community is creating.

I am definitely interested in a C# wrapper that works exactly like the Ruby API. Ie, factory methods, etc. (It is too weird having objects floating around unattached to parent objects for my OOP tastes.)

The past couple of days I installed VS Community 2019 and was successful in compiling 4 or 5 C# SpaceClaim AddIns. (Unfortunately I haven't yet gotten DesignSpark Mech 4 to load them.)

You and Ken gonna get your wrappers up on GitHub ?

**Comment by DanRathbun** [comment]
@thomthom I'm closing this discussion. Please transfer the enhancement label to Issue #355.
