### ISSUE TITLE
Sketchup::ComponentDefinition # path returns empty string when no path

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#356]
#### [**`Sketchup::ComponentDefinition # path`**](http://ruby.sketchup.com/Sketchup/ComponentDefinition.html#path-instance_method) returns empty string (not **`false`** nor **`nil`**) for definitions without a path.

The docstring says ...
> Returns **`nil`** if it is an internal component.

Also the returns section states ...
>Returns:
>
>(`String`, `false`) — a valid path if successful, `false` if unsuccessful

**Comment by Eneroth3** [comment]
I wonder what the original API designers even meant by unsuccessful. Is an empty string a "successful" return value for an internal component while "unsuccessful" would translate to an exception or the like?

**Comment by DanRathbun** [comment]
The idea of success & failure should not apply to property "getter" methods like this.
I think the guy writing the docs just was pasting the same kind of thing a bunch of times. We see this sprinkled through the API docs. (Often in places where the methods always returned on value or one type of object, like a string.)

**Comment by thomthom** [comment]
> I think the guy writing the docs just was pasting the same kind of thing a bunch of times

That's my guess as well. I've been removing this when updating docs - as least for boolean return values.
