### ISSUE TITLE
[FR] Improved consumable transparency

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#358]
I, probably like many others, prefer to know what I am about to consume before consuming it. There are several ways the transparency of consumables could be improved.

To start with, similar items could be organized into trays based on their similarity, rather than being spread out over multiple trays. Trays could also be labeled based on their contained items. Not mixing the items would likely as a side effect lower the load on the earlier parts of pipeline, as they are likely assembled separately only to then be mixed anyway. Instead of severing these links only to mentally recreate them later, they could be kept throughout the pipeline.

Wrappers could also be excluded on additional consumables for increased transparency, but some developers may also like wrappers so they can be kept on some items. 

Improving transparency could increase the efficiency of consumption, leading to lowering the downtime. In addition to improved transparency, a pre-defined winding order could also increase efficiency as it would lower the collisions rate, but that should maybe be filed as a separate issue.

**Comment by thomthom** [comment]
"Consumables"? I'm don't fully understand what this request is about... Can you clarify?

**Comment by DanRathbun** [comment]
> "Consumables"?

Re, in the SketchUp sense, I'd think "consumables" would be materials, styles, classifications, etc. Things that I usually refer to as **resources**.

Anyway, this seems more like a high level discussion topic then any kind of specific request for a feature or fix.

**Comment by dphdave** [comment]
why do I get this feeling this is actually about food...?!
