### ISSUE TITLE
Resize SketchUp window

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#366]
It would be quite useful with a native cross-platform way to resize the SketchUp window. Personally I use this quite a lot to generate imagery of extensions perfectly matching Extension Warehouse's image requirements.

Currently the Win API or User32.dll can be used on Windows, but on Mac it seems the only way to change the Window size is to hack the plits files and restart SketchUp, or use system level calls that require extended privileges.

I propose a `window` method on either `Model` or `View` that returns a new `Window` object. To start with this object can have a `set_size` method, similar to that of HtmlDialog, but in time it might be extended with maximize, restore, set_position and other functionality that you don't want cluttering the existing classes.

Forum thread: https://forums.sketchup.com/t/resize-window-on-mac/107673

**Comment by DanRathbun** [comment]
> but on Mac it seems the only way to change the Window size ..., or use system level calls that require extended privileges.

Making the system call from within the application process should not require extended privileges. 
From my reading, the Apple Cocoa docs do not imply special privileges are needed.

However, I can understand that when trying to change an application's window metrics from a shell command process, that this would have security hurdles. (This is what I think John ran into.)

**Comment by DanRathbun** [comment]
> _I propose a `window` method on either `Model` or `View` that returns a new `Window` object. To start with this object can have a `set_size` method, similar to that of HtmlDialog, but in time it might be extended with maximize, restore, set_position and other functionality that you don't want cluttering the existing classes._

But it wasn't, ... instead it was just dumped into the (already bloated) [`Sketchup`](https://ruby.sketchup.com/Sketchup.html) module (again, ie ... we've complained about this module being overloaded in the past quite a few times.)

Even goofier, ... the 1st argument is the `model`, when it should have been the last (optional) argument defaulting to [`Sketchup::active_model`](https://ruby.sketchup.com/Sketchup.html#active_model-class_method).

... (end rant.)
