### ISSUE TITLE
InputPoint#face not always on input point

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#372]
Related to #371.

I think the documentation can be a bit more clear that InputPoint#face may return a face that the InptPoint isn't getting its position from. The face may just as well be located somewhere behind an edge or other inference the point is coming crom.

I don't think this is a bug as the face may still be interesting to have, e.g. top pick up a plane similarly yo how Rotate tool does, just that it needs to be clarified.

Steps to reproduce/test:

Run this tool and move the cursor over geometry.
The tool selects the edge and face returned by #edge and #face.

![2019-11-18_15h45_25](https://user-images.githubusercontent.com/5631725/69061984-7ebd8b00-0a1a-11ea-981e-bd82c94bf054.gif)

```ruby
class TestTool
  def initialize
    @ip = Sketchup::InputPoint.new
  end

  def draw(view)
    @ip.draw(view)
  end

  def onMouseMove(_flags, x, y, view)
    @ip.pick(view, x, y)
    view.invalidate
    highlight_entities(@ip)
    Sketchup.status_text = "#{@ip.degrees_of_freedom} degrees of freedom."
  end

  private

  def highlight_entities(ip)
    selection = Sketchup.active_model.selection
    selection.clear
    selection.add(ip.face) if ip.face
    selection.add(ip.edge) if ip.edge
  end
end

Sketchup.active_model.select_tool(TestTool.new)
```

**Comment by DanRathbun** [comment]
Ugh ... the "on" getters are not mutually exclusive.

And I see more complexity with regard to getting the constraint. Ie, if you hover over a midpoint of a face's edge then move into the face, ... there is only 1 degree of freedom yet the point is gotten from a face (ie, `#edge` returns `nil`.)
