### ISSUE TITLE
Inference lock documentation

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#374]
I had been writing plugins for years and even tried re-engineer inference looking before I found how inference can be locked at the View class, automatically drawing all the helper lines with correct stipple and stuff to the viewport and projecting the points precisely as desired.

```ruby
# Showing how Shift can be held down to lock inference to whatever is
# currently hovered.
class InferenceExampleTool
  def initialize
    @ip = Sketchup::InputPoint.new
  end
  
  def draw(view)
    @ip.draw(view)
    view.tooltip = @ip.tooltip
  end

  def onMouseMove(_flags, x, y, view)
    @ip.pick(view, x, y)
    view.invalidate
  end
  
  def onKeyDown(key, _repeat, _flags, view)
    return unless key == CONSTRAIN_MODIFIER_KEY

    view.lock_inference(@ip)
    view.invalidate
  end

  def onKeyUp(key, _repeat, _flags, view)
    return unless key == CONSTRAIN_MODIFIER_KEY

    view.lock_inference
    view.invalidate
  end
end

Sketchup.active_model.select_tool(InferenceExampleTool.new)
```

I just now found how View#lock_inference can take two InputPoints to look to an axis,  typically when pressing the arrow keys.

```ruby
view.lock_inference(
  Sketchup::InputPoint.new(ORIGIN),
  Sketchup::InputPoint.new(Geom::Point3d.new(1, 0, 0))
)
```
To me this isn't very intuitive as I associate InputPoints very much with mouse position input and the variously shaped and colored dots drawn on the InputPoint position, not a line.

I think the documentation has to be imprioved in this area, both with full fledged example and simple descriptions what the parameters mean.

**Comment by Eneroth3** [comment]
Here is my work in progress attempt to a inference lock mixing module for getting a similar behavior to the native tools.

https://github.com/Eneroth3/inference-lock

**Comment by DanRathbun** [comment]
I see the 2nd snippet made it into the docs. How about the example tool class ? Is this for an article on Tools ?

**Comment by thomthom** [comment]
We, we've been talking about adding new examples that demonstrate this.

**Comment by DanRathbun** [comment]
Can you please try to see if the Help Articles can be added from a separate GitHub repo. (I think that they can.)
Then suggestions and content can be given in that repo's Issue list and via PRs.
