### ISSUE TITLE
SUModelGetFonts documentation errors

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#38]
### Bug Report

[**`SUModelGetFonts`**](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/model_8h.html#a3718e8f1db08e68236f59d3e4f430a22) refers to "material/materials" in 3 places, but should say "font/fonts".

http://extensions.sketchup.com/developers/sketchup_c_api/sketchup/model_8h.html#a3718e8f1db08e68236f59d3e4f430a22
_viz:_
> Retrieves all the **_materials_** associated with a model object.
>
>**Since**
>SketchUp 2017, API 5.0
>
>**Parameters**
>[in] | model | The model object.
>[in] | len | The number of **_material_** objects to retrieve.
>[out] | fonts | The font objects retrieved.
>[out] | count | The number of **_material_** objects retrieved.

\* Docstring was copied from the **`SUModelGetMaterial`** function but editing not finished.

**Comment by thomthom** [comment]
Logged as SU-38582

**Comment by DanRathbun** [comment]
@thomthom This has been fixed at some point since, but the issue has not been closed.
Should close here and in Jira #SU-38582.
