### ISSUE TITLE
Documentation Pager#layers does not return a list of hidden layers

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#382]
The documentation for Page#layers states it returns an array of layers hidden in that scene. This is not the case. It returns array of layers that differ from their default scene visibility state for that scene. The documentation of Layer#scene_behavior covers this.

This is how the layer visibility can be checked for a scene.

```ruby
def visible_in_scene?(layer, scene)
  scene.layers.include?(layer) == hidden_by_default?(layer)
end

def hidden_by_default?(layer)
  layer.page_behavior & LAYER_HIDDEN_BY_DEFAULT == LAYER_HIDDEN_BY_DEFAULT
end
```

**Comment by DanRathbun** [comment]
What does the superscript question mark character mean following the return type in the YARD output ?

**Comment by MSP-Greg** [comment]
It can also be nil

**Comment by DanRathbun** [comment]
Thanks, I'll try to remember this.
