### ISSUE TITLE
Definitions modified with the C API keep the same GUID

### ISSUE THREAD

**Issue by jiminy-billy-bob** [SketchUp/api-issue-tracker#385]
https://forums.sketchup.com/t/c-api-modified-definitions-keep-the-same-guid/109895

Modifications applied to a definition (either its entities collection, or its properties like name, behavior, etc) do not trigger a GUID change.

This is a major issue for us, as it messes with the ability to reload modified component with nested groups/components.

**Comment by thomthom** [comment]
I think we had similar issues with model GUID not updating upon save.

**Comment by jinyistyle** [comment]
SKOR-12614

**Comment by Eneroth3** [comment]
This was fixed in SketchUp 2021.1

**Comment by DanRathbun** [comment]
@thomthom I do **not** see this fix being listed in the release notes for **any** 2021 release.

If this **was** fixed please label it appropriately and please add to release notes.

**Comment by thomthom** [comment]
It's mentioned in `version.txt` in the SDK package: 

> Fixed GUID not being regenerated when component definition is edited

Not sure why it wasn't included in https://help.sketchup.com/en/release-notes/sketchup-desktop-20211 - I'll ask around.
