### ISSUE TITLE
C API: No SKM file load and write like Ruby API has.

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#39]
### Non-Parity Report

I noticed the lack of **`SUMaterialWriteToFile()`** `-->` to a **SKM** file type,
 and it's compliment **`SUMaterialCreateFromFile()`** `<--` load from a **SKM** file.

\* This functionality was given to the Ruby API in v2017.

-----

Prompted by public forum thread ...
https://forums.sketchup.com/t/setting-materials-texture-scale/61281
... in which it's noted the C API's lack of a **`SUTextureSetDimensions()`** function.

**Comment by thomthom** [comment]
Logged as SU-38583

**Comment by DanRathbun** [comment]
Implemented in SU2021.1 (API v9.1) as:

* [`SUMaterialWriteToFile`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_material_ref.html#a858fe17085b728b29fd391103b136321)
* [`SUModelLoadMaterial`](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_material_ref.html#a2f91ace048976cb843caef70f3166c11)
