### ISSUE TITLE
Setter methods for Layout::Grid class (spacing and divisions)

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#404]
#### LayOut Ruby and C APIs Issue

I see no (spacing and division) setters for the Ruby [`Layout::Grid`](http://ruby.sketchup.com/Layout/Grid.html) class, nor C API [`LOGridRef`](http://extensions.sketchup.com/developer_center/layout_c_api/layout/grid_8h.html).

**EDIT**: Add a lack of ALL grid property setters ie: major color, minor division color, major visibility, minor division visibility and print toggle (and not only major spacing, and minor divisions.)

How is the grid to be set when a LayOut file is created with the APIs ?

(Using a bunch of templates with predefined grids is "clunky".)

**Comment by Eneroth3** [comment]
Setter methods missing?

![2019-12-12_11h02_45](https://user-images.githubusercontent.com/5631725/70702696-f48ddd00-1cce-11ea-8af9-ec5d3c1d4388.png)

**Comment by thomthom** [comment]
@ackarkka - any particular reason we haven't got setters for these?

**Comment by DanRathbun** [comment]
Pls add "C API" label as well.

**Comment by ackarkka** [comment]
> @ackarkka - any particular reason we haven't got setters for these?

Probably a lack of time, combined with this being perceived as low priority.

**Comment by DanRathbun** [comment]
**EDIT**: Add a lack of ALL grid property setters ie: major color, minor division color, major visibility, minor division visibility and print toggle (and not only major spacing, and minor divisions.)

**Comment by DanRathbun** [comment]
I believe this issue was fixed in LayOut release **2020.1** & API ver **5.1** ?

**Comment by thomthom** [comment]
Looks like the bot didn't run for the SU2020.1 release. Thanks for catching that Dan.
