### ISSUE TITLE
Setting Line Scale for Model does not work properly

### ISSUE THREAD

**Issue by Whaat** [SketchUp/api-issue-tracker#405]
1. SketchUp/LayOut Version: all versions as of today
2. OS Platform: Windows 10

If I set the line weight for a model reference using the API, when I open the Document in Layout, the UI displays the line weight value as set but the rendered model display is not correct (wrong line weight) even though I called the render command as well after setting the line weight.

This issue is a high priority for me as it affects a plugin I am currently working on and may make it impossible to achieve the desired result.

```ruby
def test_line_weight
  model = Sketchup.active_model
  model.save
  skp_path = model.path
  layout_path = File.join(File.dirname(skp_path), "test.layout")
  doc = Layout::Document.new
  bounds = Geom::Bounds2d.new(0, 0, 8.0, 8.0)
  model = Layout::SketchUpModel.new(skp_path, bounds)
  model.render_mode = Layout::SketchUpModel::RASTER_RENDER
  model.line_weight = 0.1
  model.render
  doc.add_entity(model, doc.layers[0], doc.pages[0])
  doc.save(layout_path)
  UI.openURL(layout_path)
end
```
Update Dec 19, 2019: If I first add the model to the document and then change the line weight, it seems to work properly

**Comment by thomthom** [comment]
@ackarkka - any thoughts on this one?

**Comment by DanRathbun** [comment]
I think we solved this in a private thread on the Discourse forum. (I added you to that thread.)

If the order of statements is changed to first add the model viewport to the document, **then** change properties (line weight and render) ... the results are much better.

Another thing I noted is that 1/720th of an inch (0.1pts) is a bit thin of a line weight for testing.

**Comment by Whaat** [comment]
I updated the original issue comment

**Comment by thomthom** [comment]
Relabeled this issue as an documentation issue. The docs could do with improvements to explain the importance of the order adding + modifying entities.

The gist of it, as soon as you create an entity, add it to the model, then make the modifications.

**Comment by Whaat** [comment]
If you look at the current Layout API docs for SketchUpModel (http://ruby.sketchup.com/Layout/SketchUpModel.html), you can see how a new API user would find it confusing. All of the example code shows the methods being applied to a floating 'model' reference that has not yet been added to the Layout Document, which I now realize is not correct.

**Comment by ackarkka** [comment]
Out of curiosity, if you do everything EXCEPT for rendering prior to adding the model to the document, does this still work? That is:
1) Create the Layout::SketchupModel object
2) Modify it by changing the render mode and line weight
3) Add it to the document
4) Render it

If that's the case then we simply have an issue in our render method that currently depends on a document object, which would be a bug.

**Comment by DanRathbun** [comment]
@ackarkka Adam I added you to the private thread in the forum, so you can see what was discussed there.

**Comment by ackarkka** [comment]
We have investigated this and determined what was going on. When a Layout::SketchupModel is not added to a document, the #Render method will render at low quality by default. The settings have all been applied, but the render doesn't look great as a result of that. In order to change the render quality, the model must be added to a document and the render quality settings must be updated through that document's Layout::PageInfo. We will be updating documentation to clarify that, but will not otherwise change this behavior at this time.

**Comment by DanRathbun** [comment]
@ackarkka Adam. if the docs have not yet been updated, then this issue needs to remain open. Thomas closes documentation issues when they specifically have been fixed and he pushes updated docs to GitHub.
