### ISSUE TITLE
Geom::Point2d class overview calls itself Vector2d class 

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#416]
### SketchUp Ruby API Documentation Issue

[`Geom::Point2d`](http://ruby.sketchup.com/Geom/Point2d.html) class overview calls itself [`Vector2d`](http://ruby.sketchup.com/Geom/Vector2d.html) class. Ie, the 1st line of the class' docstring is ...
> The **Vector2d** class allows you to work with a point in 2D space. **Point2d** is basically just a series of values representing x and y coordinates.

**Comment by ackarkka** [comment]
Tracked internally as LO-13494.
