### ISSUE TITLE
Entities class introduction needs mention of group and definitions

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#424]
### SketchUp Ruby API Documentation Issue

The [`Sketchup::Entities`](http://ruby.sketchup.com/Sketchup/Entities.html) class docstring states
> The Entities class is a container class for all entities in a model (it is a collection of Entity objects).

It should mention also that group and component definition's also have entities collections that use this class.

New coders are not aware of this ...
https://forums.sketchup.com/t/inserting-a-group-or-component-with-ruby-api/114936

**Comment by Eneroth3** [comment]
Something like this perhaps?

>  The Entities class is a collection of Entity objects, either in a ComponentDefinition or directly in the Model. A Entities object corresponds to a drawing context in the GUI.

**Comment by DanRathbun** [comment]
Well ordinarily, English uses an "an" instead of "a" directly before a word beginning with a vowel. But this is minor.
