### ISSUE TITLE
SUModelVersion_SU2020 missing

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#438]
In the 2020 SDK SUModelVersion_SU2020  is missing from the SUModelVersion enum. This value is used when you need to explicitly save a model to a certain version.

https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/model_8h.html#ac88f68dadd6541eb55ad30d82126d408

**Comment by jonnyns** [comment]
It is on the C SDK, are you on the Ruby side of things?
![image](https://user-images.githubusercontent.com/11561030/75116045-9b461080-5664-11ea-914d-d8db2a16b67a.png)

**Comment by Eneroth3** [comment]
Ok, it appears to be two problems confusing me. The online documentation lacks this, but I also had missed changing my Additional Include Directories value for the project when I changed the Linker. After fixing my project setup it works!

**Comment by thomthom** [comment]
Doc have now been updated for SketchUp 2020.1.
