### ISSUE TITLE
Are notification actions inheretly positie or negative?

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#484]
The naming of the API method suggests one notification option is positive and one negative. However, is there any hidden functionality enforcing this? For instance, now this isn't the case, but it could make sense for ignoring the notification to count as dismissing it. Can a notification be safely used (if it could be used, see #482) to ask a question that is not a yes or no question?

```ruby
message = "A and B clashes!\n\nKeep A or B?"
notification = UI::Notification.new(Sketchup.extensions[0], message)
notification.on_accept("A") { puts "A" }
notification.on_dismiss("B") { puts "B" }
notification.show
```

**Comment by thomthom** [comment]
No, there is no enforcement of "accept" or "dismiss". They are there are guidance so that if you do have accept and dismiss, the "negative" should appear in a consistent location.

**Comment by Eneroth3** [comment]
More documentation related stuff:

* The docs says the notification appears in the top right of the screen. It does not. Also this is irrelevant information to have in the API contract; saying it appears in the corner of the screen is enough to describe what a notification is.
* There is no info of what icon file types are supported (what file types are supported?)

**Comment by DanRathbun** [comment]
> * There is no info of what icon file types are supported (what file types are supported?)

Also mentioned **twice** in Isssue #281 to no avail. The issue was closed with no update to the docs.

Apparently we need to open specific and **separate** issues for everything.

**Comment by Eneroth3** [comment]
> UI::Notification will not render SVG icons. PNG 48x48 are shown with no issue.

Thanks! I maybe spent an hour in total with SVG with locals and global paths, giving up up and switching to PNGs only to have them weirdly cropped. I made sure to have some excess size for the icon to look crisp on a high DPI machine, but nope.

**Comment by DanRathbun** [comment]
(2 misspelled words in issue title.)

**Comment by DanRathbun** [comment]
So WHY was this closed ? What doc changes were made ? 

I've looked and still see no info on icon types and size.

Was this issue only applied to remove the mention of appearance in "top right corner" ?
