### ISSUE TITLE
UI::Notification - The two buttons always appears

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#487]
If you use **only one** button via _#on_accept_ or _#on_dismiss_, BOTH buttons always appear in the notification box, the second one being empty.

![image](https://user-images.githubusercontent.com/57754157/82991075-6a77cd80-9ffd-11ea-90b8-fc5c07bea015.png)

**Comment by DanRathbun** [comment]
I had reported this in [Issue #280](https://github.com/SketchUp/api-issue-tracker/issues/280) but it was supposed to be fixed in SU v 2019.2 and Thomas closed the issue.

It it a regression ?

**Comment by Fredosixx** [comment]
Actually, I tested on **SU2017** (because I have a notification in this case), so this may have been fixed in later versions.

I will check.

**Comment by Fredosixx** [comment]
On SU2020, this is OK for the buttons

**Comment by DanRathbun** [comment]
I noticed that you are not following the requested format for bug reports. Please do. (SketchUp version, platform and which API are really required information.)

**Comment by thomthom** [comment]
I'm reopening this as a documentation issue, so we can add a comment for when this was fixed.

**Comment by DanRathbun** [comment]
So this was fixed with 2019.0 release? (Issue label needed.)

**Comment by thomthom** [comment]
I'm not sure to be honest, this was probably fixed in the underlying implementation, not by the extensibility team. I'd have to dig to find it, but rather swamped with work right now.

**Comment by DanRathbun** [comment]
I got the release number from the release notes.
