### ISSUE TITLE
UI::Notification - Only 2 lines displayed on Mac

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#488]
Notification seems to use a bigger font on Mac.

As a result, there is only **2 lines displayed max**

![image](https://user-images.githubusercontent.com/57754157/82994517-96498200-a002-11ea-968a-4115b56dc509.png)

On Windows, you can have more lines displayed, usually 3

![image](https://user-images.githubusercontent.com/57754157/83005907-b16fbe00-a011-11ea-8ab7-7816fa3dabdd.png)

More generally, it would be more comfortable if the size of the notification would adjust automatically to the size of the text, up to a reasonable size of course.

**Comment by Fredosixx** [comment]
Actually the problem was on SU2017.

On SU2020 more lines are displayed

**Comment by DanRathbun** [comment]
One of the old issues I logged and that was fixed was that the text was not honoring a newline (`"\n"`) character. So you should now be able to insert line feeds where you wish.

See Issue https://github.com/SketchUp/api-issue-tracker/issues/282

**Comment by thomthom** [comment]
Reopening as documentation issue.

**Comment by Eneroth3** [comment]
What is the current/correct  behavior? Does the notification change size according to its content or is it always 3 lines now?

**Comment by Fredosixx** [comment]
**On SU2017, Windows**: It seems the newline character is ignored

![image](https://user-images.githubusercontent.com/57754157/93081790-1bc76f80-f690-11ea-8e8c-6ec503905a70.png)


**On SU2017, Mac**: display 3 lines max (2 lines if you have buttons)


**On more recent versions (SU2018+), Mac and Windows**, it seems that the notification window adjusts to any number of lines.
![image](https://user-images.githubusercontent.com/57754157/93081677-e91d7700-f68f-11ea-8ee1-fdce67752936.png)

**Comment by Eneroth3** [comment]
Thanks or the clarification!

**Comment by DanRathbun** [comment]
> @thomthom  Reopening as documentation issue.

Couldn't Issue [Issue 304: **Update UI::Notification documention about new line handling**](https://github.com/SketchUp/api-issue-tracker/issues/304) handle this ?

**Comment by Fredosixx** [comment]
By the way, as Dan mentioned, in SU2017 for Windows, you can force the new line by `\r\n`. Apparently just `\n` does not do the job.

**Comment by DanRathbun** [comment]
It was Julia that noticed this. It escaped me. ;)

**Comment by DanRathbun** [comment]
So fixed apparently with the 2018 release ?
