### ISSUE TITLE
Example Scripts extension has disappeared !

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#490]
The "Example Scripts" extension has disappeared from the EW !

There are **numerous** forum posts where we've pointed new coders interested in learning to code custom tools to this extension and it's sample "LineTool.rb" file.

What are we to point interested coders to now ? !!

----

Why do we keep getting these **ugly** surprises with no advanced warnings ??

**Comment by Eneroth3** [comment]
If I remember correctly these examples were uglier than the surprise. Didn't they use global variables and other weird stuff?

That said, a nice a simple starting point with good examples with incremental complexity and showing a variety of concepts would be very good for the developer community.

**Comment by DanRathbun** [comment]
> If I remember correctly these examples were uglier than the surprise. Didn't they use global variables and other weird stuff?

ALL SketchUp extensions and other still present examples use poor coding, incorrect indentation and global variables. So this cannot be the main reason they were removed.

> That said, a nice a simple starting point with good examples with incremental complexity and showing a variety of concepts would be very good for the developer community.

I guess that the line tool example was added to the Tutorials repo here ...
https://github.com/SketchUp/sketchup-ruby-api-tutorials/blob/master/examples/02_custom_tool/ex_custom_tool/main.rb

It would be nice if there was an automatic redirect from the EW extension URL to the GitHub Examples repo. (Otherwise I'll need to search through the forums for everywhere I posted the link to the non-existent extension, and change it to the GitHub repo.)

But also, not all of the example in the old "Example Scripts" extension have been migrated into the "Examples" Tutorials repo.

**Comment by thomthom** [comment]
We did some cleaning up on the SketchUp Team page. Among them using GitHub as the hub for code examples. We want to promote newer cleaner examples over the older ones. We see that a number of the older examples crop up in extension reviews which in some cases end up being cause for rejection since the examples were crafted before the EW requirements where properly established.

Unfortunately we don't have a way to setup redirected for an old page. (That would be nice actually.)

**Comment by DanRathbun** [comment]
Okay then I'll have to do a search and replace the old URLs in my posts.
