### ISSUE TITLE
UI::HtmlDialog - Total mess for dialog sizing

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#492]
For once, the problem seems to be **only on the Windows platform**. On Mac OSX (at least Catalina), it seems to work fine.

1) **Dialog size in Javascript**

```window.outerWidth``` is always equal to ```window.innerWidth```. Same for ```window.outerHeight``` and ```window.innerHeight```. It seems that the CEF browser window is created as a window with NO title bar and frame and then, is not aware it is put into another window. 

As a result, there is absolutely NO WAY to know what are the correct size to use in the Ruby method ```HtmlDialog.set_size()```, given the desired size of the browser content area. By trial and error, I find that the delta in width is 14 and the delta in height in 37. But that's on my laptop, with a given resolution and a scale factor of 1.25. I have no idea whether this is true on another configuration.

2) **On SU2017 specifically (so Make users), it's even worse**. 

If you set the size of the dialog to 250x250 with the Ruby ```set_size()``` method, you get (on my laptop):
```window.outerWidth = window.innerWidth = 295```, so a difference of +45
```window.outerHeight = window.innerWidth = 266```, so a difference of +16

But on a dialog sized 500 x500
```window.outerWidth = window.innerWidth = 607```, so a difference of +107
```window.outerHeight = window.innerWidth = 578```, so a difference of +78

Obviously, the arithmetic does not work, and I have no clue how to relate the ```window.outerWidth``` and ```window.outerHeight``` to the proper size set in Ruby.

3) **```window.resizeTo()``` does not work in any version.**

You have to call back Ruby to execute the ```set_size()``` method. I could leave with that, but this is another sign that the questions of sizing were not overseen.

4) **In SU2017, there are a few other issues**
- the HTML rendering is smaller than in other SU versions (with exact same HTML and CSS code). I don't know if this is related to the UI.scale_factor or a bad version of CEF. For Windows only. Ok with Mac.

SU2017: ![image](https://user-images.githubusercontent.com/57754157/83687114-9beb2d00-a5eb-11ea-8125-0d0695c0d310.png)

SU2020: ![image](https://user-images.githubusercontent.com/57754157/83687182-af969380-a5eb-11ea-8ed7-4a53e7a6693e.png)

- a dialog created with UI::HtmlDialog::STYLE_UTILITY cannot be resized manually, regardless of the ```resizable``` setting

---------------------------

I am really disappointed that the same team that is able to run the whole of Sketchup in any browser is unable to provide a proper API to get the relation between the external size of a dialog box and the inner size of the content area, even more for a designated browser.

I frankly don't know what to do, even formulate a request, which at best would go to SU2021, leaving SU2017 and other versions in the world of approximation and dirty workarounds. I may stay with UI::WebDialog until this is clarified.

At least, I need to crack the logic of SU2017 sizing formulas

**Comment by Fredosixx** [comment]
I finally found the 'logic', if I can use this term. Very weird....

**Comment by Eneroth3** [comment]
Maybe not the solution you are after, but a simple way around this I've found is to allow the dialog to resize and the content along with it. This doesn't work for fancy flyout menus that need to precisely match their content though, but works for most dialogs resembling normal windows.

![2020-06-04_12h09_59](https://user-images.githubusercontent.com/5631725/83744385-56b31380-a65c-11ea-9ce9-7610b4f1c4d3.gif)

For exact sizing I'd recommend not to detect and hard-code any dimensions for the window chrome when making the extension, but find these values on the fly for the computer running the extension. You can achieve this by resizing the window twice, and in between check by how much the size was off in the first iteration. This is the approach I use for Eneroth Viewport Resizer.

**Comment by Fredosixx** [comment]
> Maybe not the solution you are after, but a simple way around this I've found is to allow the dialog to resize and the content along with it

I use % specifications when appropriate, especially for width. For height, it depends, when you have to combine elements which can do with variable height (say lists) and fixed height (say row of buttons). But is some occurrences where you need elements to respect a height/width ratio (typically images), it's more comfortable to compute the layout and then resize the dialog accordingly.


> For exact sizing I'd recommend not to detect and hard-code any dimensions for the window chrome when making the extension, but find these values on the fly for the computer running the extension.

That's my approach too (and doing it once by Sketchup session), but this also means that you need to find out the formula. See in my main post what happens with SU2017 on Windows and you'll see that this is not just adding a delta.

Frankly, I am disappointed, because these are typically worries that a good API would save to us, and also guarantee that this will work in future versions, instead of having every individual developer face the problem and eventually find its own solution. HtmlDialog is the second attempt to Web-based dialog (a very good idea introduced with SU6); so, you would expect that it solves the flaws of the first UI::WebDialog generation.

**Comment by DanRathbun** [comment]
> I am really disappointed that the same team that is able to run the whole of Sketchup in any browser is unable to provide a proper API to get the relation between the external size of a dialog box and the inner size of the content area, even more for a designated browser.

Please do not **assume** (without research) that it was easily possible but was ignored.

As I had mention in issue 430 ...
>Background: The `window` object has limitations from within JavaScript running in a CEF instance, two of which are that the `onfocus` and `onblur` events do not fire for the window (and the Chrome Dev Tools do not show attached EventListeners on the `window` object.)

There are quite a few other limitations where JS DOM method calls are a no-op called from an embedded framework instance. If you search the CEF forums, you'll find that sizing calls on the `window` object are also no-ops.

Ie, in the referenced public forum topic, ...
https://forums.sketchup.com/t/focus-event-on-window-object-from-cef-htmldialog-javascript/115945
... I've already noted that `window.resizeTo()` and `window.resizeBy()` are not allowed by the CEF.

This is why the API's `dialog.set_size` method was implemented, so the window frame size could be size from outside using platform function calls.

So basically, you must stop assuming that all JS DOM calls will be implemented (or work the same) in embedded browser frameworks. It isn't just the CEF. The embedded IEBrowserControl also had security limitations on access to the JS `window` object. (For example `window.owner` is a no-op.)

> Frankly, I am disappointed, because these are typically worries that a good API would save to us, and also guarantee that this will work in future versions, instead of having every individual developer face the problem and eventually find its own solution.

I agree with this philosophy that APIs should seek to provide common solutions for common challenges so that everyone need not "reinvent the wheel" for themselves.

> I frankly don't know what to do, even formulate a request, which at best would go to SU2021, leaving SU2017 and other versions in the world of approximation and dirty workarounds.

One of the main challenges is that older SketchUp versions use both older versions of the CEF and Javascript.

Also ... the difference between outer size and inner size can change at anytime if the user makes preference changes via the system. I currently have my window borders to the minimum 1 pixel, but other users still prefer the 3D Aero style borders which I think are 8 pixel minimum. (So 16 for both borders.)
I also think there may still be issues when users use Aero style on Windows 10. I had issues so abandon that old style even though I liked it. But it was more important to me that the Windows interface worked without bugs in dark mode.

The real answer would be for coders to worry about what the inner size should be, and get the API maintainers to set the outer size transparently so that the inner size is set correctly. (Ie the API polls the platform via OS calls for border sizes and caption height and does the adjustments for extensions transparently.)

From then on the user's sizing the window frame will take over for sizable dialogs. (Ie, the are saved in preferences and restored the next time the dialog is opened.)

**Comment by Fredosixx** [comment]
Dan, that's what I say. This is pretty complex.

This is why it is better done ONCE in the API, by skilled Sketchup developers (who can better leverage the Sketchup and CEF integration code), rather by MANY script writers, less skilled and limited by what Ruby offers to them.

I agree that we are now at the 4th iteration of UI::HtmlDialog (after the 7th of UI::WebDialog) and these issues are still there. This is where I am disappointed. A good idea, but half-baked...

**Comment by MSP-Greg** [comment]
I agree that there should be a better API for this, and also the addition of min/max settings.

I have always been picky about dialog sizing, as I had windows that expanded/collapsed (showing/hiding metdata), dialog font size selection, etc.  The best way I found was using a splash screen, which is still sensitive if the user changes system settings.  They can re-open SU if they do that...

**Comment by DanRathbun** [comment]
> ... and also the addition of min/max settings.

They didn't actually go away. They were moved to named/hash arguments of the class constructor.

* _See:_ [`UI::HtmlDialog#initialize`](https://ruby.sketchup.com/UI/HtmlDialog.html#initialize-instance_method)

**Comment by MSP-Greg** [comment]
> They didn't actually go away.

But if the dialog is already initialized and visible...

**Comment by DanRathbun** [comment]
True. Apparently the devs thought we'd never need to change constraints after the dialog was created.

**Comment by Fredosixx** [comment]
It make sense to have the max and min sizes dynamic as well, with a ```set``` and ```get``` method.

Likewise, Sketchup seems to store the position and size based on a ```preferences_key```. Fine, but then, it would be helpful to have a ```get_size``` and a ```get_position``` method. Because these methods are missing, we are obliged to maintain our own parallel system of storing the size and position based on the ```preferences_key``` (using te ```onResize()``` event).

There are other odysseys **for the Mac version**, which makes things cumbersome, among which:

1. At loading of the window, the difference between ```window.outerHeight``` and ```window.innerHeight``` is wrong (51 px), whereas it is correct (22 px) afterwards. This does not help!

2. At closure, CEF sends a ```onResize()``` event with wrong sizes before the ```onUnload()``` event. Another annoyance.

All this makes the HtmlDialog wobbly when it comes to be accurate on sizing dialogs, which I think is a respect we, authors, owe to the users.

**Comment by thomthom** [comment]
Fredo, is the gist of this issue the ability to size a dialog given the content size (excluding the window frames)?

**Comment by MSP-Greg** [comment]
Since many people probably have work arounds for this, adding system methods that return the window frame dimensional data would be helpful?  That wouldn't be a breaking change...

**Comment by Fredosixx** [comment]
I also found workaround.

But more methods to get data would be welcome, especially if

- we can get the info before showing the dialog

- if the methods are synchronous (currently I can get the information from Javascript, but this implies to execute a script, get the callback called while synchronizing the flow

Information welcome should be
  - Get external size of dialog (as it would be in ```set_size``` method)
  - Framing info and the parameters to compute the external size from the innersize (```window.innerWidth``` and ```window.innerHeight```)
  - get the position of dialog (as it would be in ```set_position``` method)
  - get the size of the screen (we can get it in Javascript, but this implies that the dialog have been displayed)
  - if possible, get the relation between an absolute screen position (in ```HtmlDialog``` world) and the viewport position (in ```Sketchup::Tool``` world). 
  - and indeed, the method to get focus to the main Sketchup window

**Comment by DanRathbun** [comment]
Solved with the v2021.1 release.

Instance methods **added**:
   
* [`UI::htmlDialog#get_content_size`](https://ruby.sketchup.com/UI/HtmlDialog.html#get_content_size-instance_method)
* [`UI::htmlDialog#get_position`](https://ruby.sketchup.com/UI/HtmlDialog.html#get_position-instance_method)
* [`UI::htmlDialog#get_size`](https://ruby.sketchup.com/UI/HtmlDialog.html#get_size-instance_method)
* [`UI::htmlDialog#set_content_size`](https://ruby.sketchup.com/UI/HtmlDialog.html#set_content_size-instance_method)

... and the **addition** of the new [constructor](https://ruby.sketchup.com/UI/HtmlDialog.html#initialize-instance_method) boolean named argument `use_content_size`. The doc for [`#initialize`](https://ruby.sketchup.com/UI/HtmlDialog.html#initialize-instance_method) states:

> _When `use_content_size` is set to `true`, ... `width`, `height`, `min_width`, `max_width`, `min_height`, `max_height` will represent the size of the content area of the window. This excludes the titlebar and the window frame. When `use_content_size` is set to `false` (the default value), the size dimensions will represent the outer frame size._

(@thomthom, the 2021.1 API release notes do not mention the addition of this very important argument.)
