### ISSUE TITLE
SUMeshHelper: problem with tessellation of cut opened faces.

### ISSUE THREAD

**Issue by prachtan** [SketchUp/api-issue-tracker#5]
1). C API / SketchUp 2017 (and newer)
2). Windows

Inconsistency between RubyAPI `face.mesh(7)` and C API `SUMeshHelper`

@thomthom: 
We discussed this during devcamp, C API tessellation of cut opened faces returns wrong number of triangles - problem is probably somewhere in internally cached data.

**Comment by prachtan** [comment]
This can be closed - solved by sdk2018.

**Comment by thomthom** [comment]
Oh, really? How strange. Was it fixed by linking to `sketchup.lib`? (Because you used the C API from within SketchUp?)
