### ISSUE TITLE
Typo in Tool.onRButtonDoubleClick

### ISSUE THREAD

**Issue by MattiaBressanelli** [SketchUp/api-issue-tracker#505]
I think there is a typo in the documentation for Tool.onRButtonDoubleClick. The documentation states onRButtonDoubleClock in the method's title.

No big deal of course, but a very easy fix.

**Comment by thomthom** [comment]
Thanks for reporting!

https://ruby.sketchup.com/Sketchup/Tool.html#onRButtonDoubleClick-instance_method

⏰⏰
