### ISSUE TITLE
C SDK download page has 20.0 application version numbers swapped

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#507]
#### C SDK API Documentation Issue

On Sketchup’s SDK page (https://extensions.sketchup.com/sketchup-sdk) they refer to the latest Windows SDK version as 20.0.362.

**The version numbers for Windows and MacOS are swapped.**

**Comment by DanRathbun** [comment]
Fixed

**Comment by thomthom** [comment]
Ah yes, we got them fixed with the SU2020.2 release.
