### ISSUE TITLE
Undocumented method Face#wi_center

### ISSUE THREAD

**Issue by s-p-b** [SketchUp/api-issue-tracker#510]
There is an undocumented instance method for Sketchup::Face called *wi_center*.
As far as I can tell it takes no arguments (arity 0) and returns the geometric centroid of the face as a Point3D.
Definitely nice to have, but it would be good to have the developer team confirm its intended use and function.

**Comment by DanRathbun** [comment]
What version? I don't see it any version I have.

To me the "wi_" prefix may indicate this has been added by an extension (which is a "no-no".)

**Comment by s-p-b** [comment]
Of course...the culprit is [Wikii's Follow me and keep](http://sketchucation.com/forums/viewtopic.php?p=129504#p129504). 
I will write my own centroid method. Thanks!

**Comment by thomthom** [comment]
While the documentation has plenty of room for improvements it is complete in terms of documenting what is public API. Anything not documented can safely be assumed to be internal.
