### ISSUE TITLE
Sketchup Extensions - Bug for standalone files

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#523]
**Platform**: Windows and Mac
**Sketchup**:  all versions since at least SU2017

**If a ruby file (.rb or .rbe) contains the statement `Sketchup.register_extension`, even if commented out, it is considered as an extension with the name of this file**.

I had the problem with the display of 'top_libFredo6' as an extension in the Extension manager. This was due to the fact that this file contained an old, inactive statement `Sketchup.register_extension` (in comments) from very old times.

This issue was occasionally signaled by users (see [this post](https://forums.sketchup.com/t/sketchucation-extensions/133994/7?u=fredo6)), because this standalone extension is indeed not signed. It took me a while to understand where the problem was coming from.

![image](https://user-images.githubusercontent.com/57754157/91323485-35784400-e7c1-11ea-97b9-1e6e6423efbd.png)

**REQUEST**: Clarify the rules for registering extensions

EDIT: there seems to be some subtlety in all that, as I am now unable to reproduce the problem with a simple configuration of files. I'll try to come up with something when I investigate deeper.

**Comment by thomthom** [comment]
If you can produce an example to reproduce that would be great.

**Comment by thomthom** [comment]
hm... I think SU might take the filename if the root .rb isn't loaded (or it didn't register a `SketchupExtension` instance.. For example, if an extension is blocked from loading due to policy setting then SU doesn't have the full name.
