### ISSUE TITLE
Pages#each documentation and code example improvement

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#525]
##### [`Sketchup::Pages#each`](https://ruby.sketchup.com/Sketchup/Pages.html#each-instance_method)

----

**(1)** Please add a note warning that individual scene pages should not be erased within a block passed to this method, and that an array copy should be used instead ...
```ruby
pages.to_a.each { |page| pages.erase(page) }
```
_REF:_ https://forums.sketchup.com/t/erase-all-scenes-pages/134922

----

**(2)** The code example uses [`UI.messagebox`](https://ruby.sketchup.com/UI.html#messagebox-class_method) within an iterator block. IMO, this is a poor example we should not be encouraging.

Calls to [`UI.messagebox`](https://ruby.sketchup.com/UI.html#messagebox-class_method) (or any model dialog) should **not** be shown in examples within an iterator block and definitely **not** within a timer block.

They also should **not** be shown for verifying code (object creation) or debugging as they can fail silently, leaving the new coder clueless as to what happened. (Show using [`puts`](https://ruby-doc.org/core-2.5.5/Kernel.html#method-i-puts) statements to the console instead.)

For this method, suggest an example that collects strings names and then after the [`#each`](https://ruby.sketchup.com/Sketchup/Pages.html#each-instance_method) block, displays the list of names:
```ruby
model = Sketchup.active_model
pages = model.pages
status = pages.add "Page 1"
status = pages.add "Page 2"
page_names = []

pages.each { |page| page_names << page.name }

text = page_names.join("\n")
UI.messagebox(text, MB_MULTILINE, "Scene Page Names")
```

**Comment by Eneroth3** [comment]
Regarding .1, that applies to more or less every SketchUp API class implementing #each, right?

**Comment by DanRathbun** [comment]
If you look through the referenced forum thread, there is a lot of good "meat" there for a good start on a general tutorial page for SketchUp API ("thinly wrapped" C++) collections. And that is what we we really talking about in that thread, although several also wanted to bring in pure Ruby collections like Arrays. And yes, it applies to both, but the API docs don't document Ruby core classes.

So with regard to API collection classes, **generally**, the advice would apply to any C++ collection exposed to the Ruby API, with any iterator (`#each` etc.) that also either has: a member deletion method (`delete`, `erase`, `remove`, etc.) for the collection, or members that have an `#erase!` or `delete` method.

These are a good list of methods that shold not be called from withing their own `#each` iterator block ...
[`Sketchup::AttributeDictionaries#delete`](https://ruby.sketchup.com/Sketchup/AttributeDictionaries.html#delete-instance_method)
[`Sketchup::AttributeDictionary#delete_key`](https://ruby.sketchup.com/Sketchup/AttributeDictionary.html#delete_key-instance_method)
[`Sketchup::Set#delete`](https://ruby.sketchup.com/Sketchup/Set.html#delete-instance_method)

[`Sketchup::Entities#erase_entities`](https://ruby.sketchup.com/Sketchup/Entities.html#erase_entities-instance_method)
[`Sketchup::Pages.erase`](https://ruby.sketchup.com/Sketchup/Pages.html#erase-instance_method)

[`Sketchup::DefinitionList#remove`](https://ruby.sketchup.com/Sketchup/DefinitionList.html#remove-instance_method)
[`Sketchup::Layers#remove`](https://ruby.sketchup.com/Sketchup/Layers.html#remove-instance_method)
[`Sketchup::Materials#remove`](https://ruby.sketchup.com/Sketchup/Materials.html#remove-instance_method)

Tests on using `remove` within a `selection#each` block fail. (Only 1 object is removed.)
[`Sketchup::Selection#remove`](https://ruby.sketchup.com/Sketchup/Selection.html#remove-instance_method)

[`Layout::AutoTextDefinitions#remove`](https://ruby.sketchup.com/Layout/AutoTextDefinitions.html#remove-instance_method)
[`Layout::Layers#remove`](https://ruby.sketchup.com/Layout/Layers.html#remove-instance_method)
[`Layout::Pages#remove`](https://ruby.sketchup.com/Layout/Pages.html#remove-instance_method)

----

I also tested `Entities#each {|e| e.erase! }` and it seemed to work okay. But only in simple tests of under 40 items.
I'd think this also should apply to the general rule. Save up the items to be erased, and use the bulk `#erase_entities` method afterward.

**Comment by DanRathbun** [comment]
So ... with regard to the warning note. Where to put it ?

a) A the top of every class that has `#each` and a deletion method ?
b) In each of these classes' deletion method docstrings ?

... and ...

Do we put a "Deleting Safely from Collections" section in a "Files" page ... and just link to this section from all the methods ?
... rather than violate the DRY rule and repeat the same warning all those places ?
