### ISSUE TITLE
Document ImageRep

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#536]
I've looked at the ImageRep documentation and to me it raises more questions than it answers. I think it requires some documentation work by someone who knows how it works and why.

There are two examples of the constructor, one loading a file and one not. Since there are no height and width setters, is it even possible to create an "empty" ImageRep and later populate it with data? Or does this exist just in case you want to load an image from file as a later call? If the latter, the example could include a call to load_file.

Is color_at_uv used to get a color from normalized coordinates, where the 0 and 1 are the corners of the image, irregardless its size? It would make sense but could be phrased a bit clearer.

Why is set_data taking bits_per_pixel and row_padding as parameters? Aren't these properties of the ImageRep? Or do you use this method on an "empty" ImageRep with no defined size to draw to it? What does the width and height parameters represent, the size of the rectangle you are drawing with a certain color or the measurements of the image as a whole? Does ImageRep even stoore width and height as parameters or extract it from the raw data on the fly?

There's a note saying the data must be ASCII-8BIT encoded, but no example showing how to encode a color value and get the correct character encoding for the bit string.

An example in the class introduction how to get an ImageRep from a texture would probably also be helpful. I suspect that's a main use case.

**Comment by thomthom** [comment]
> There are two examples of the constructor, one loading a file and one not. Since there are no height and width setters, is it even possible to create an "empty" ImageRep and later populate it with data?

Yes, calling the constructor initializes an imagerep with no image data. This is useful when you want to generate a new image. We can add such description to that constructor for clarification.

> Is color_at_uv used to get a color from normalized coordinates, where the 0 and 1 are the corners of the image, irregardless its size? It would make sense but could be phrased a bit clearer.
No, UVs doesn't have to be normalized to range between 0.0 and 1.0. It can take whatever value you get from the UV helper or mesh object. This example demonstrates its usage: https://github.com/SketchUp/color-at-uv

https://github.com/SketchUp/color-at-uv/blob/964875a10cffe4eeabc2cf1b99b8a33fd1995050/src/Ex_ColorAtUv/main.rb#L185

Note that one would have to normalize UVQ to UV. (Maybe we should have had an API to get color from UVQ....)

> Why is set_data taking bits_per_pixel and row_padding as parameters? Aren't these properties of the ImageRep?
`set_data` discards anything that might already be set in the image rep. It replaces all data.

What does the width and height parameters represent, the size of the rectangle you are drawing with a certain color or the measurements of the image as a whole?
Pixel dimensions of the bitmap. ImageRep works in bitmap space, not in model space.

> There's a note saying the data must be ASCII-8BIT encoded, but no example showing how to encode a color value and get the correct character encoding for the bit string.
Good point. One way is to create the raw string directly, however, I usually create an array of integers and then `array.pack('C*')` (https://github.com/SketchUp/sketchup-colorize-algorithm/blob/5a61af46d69b732b3dd91fec3e49576cf51eab2c/src/ex_colorize/image_rep_helper.rb#L43)

> An example in the class introduction how to get an ImageRep from a texture would probably also be helpful. I suspect that's a main use case.

That is simply `Sketchup::Texture#image_rep`. We should probably expand on how to generate images.

Maybe a simple color adjustment version? Something akin to this example: https://github.com/SketchUp/sketchup-colorize-algorithm

**Comment by Eneroth3** [comment]
> `set_data` discards anything that might already be set in the image rep. It replaces all data.

Oh! This explains so much. Now it makes sense why you can create empty ImageReps (with no dimensions). It also explains why you set the image dimensions here. I thought it drew onto an existing image.

> Good point. One way is to create the raw string directly, however, I usually create an array of integers and then `array.pack('C*')`

An example of `array.pack('C*')` along with a comment explaining what it does with the encoding would be very useful here!

**Comment by DanRathbun** [comment]
The note added to [`#set_data`](https://ruby.sketchup.com/Sketchup/ImageRep.html#set_data-instance_method) used backquotes instead of `+Array#pack(“C*”)+` for monospaced inline code.
