### ISSUE TITLE
enum SUTypedValueType missing Int16 type

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#55]
SDK SU18

https://github.com/TommyKaneko/Sketchup-API-C-Wrapper/issues/33#issuecomment-367948636

There is no `SUTypedValueType_Int16` despite there being a `SUTypedValueGetInt16`

```cpp
/**
@enum SUTypedValueType
@brief The set of types that a \ref SUTypedValueRef can represent.
*/
enum SUTypedValueType {
  SUTypedValueType_Empty = 0,
  SUTypedValueType_Byte,
  SUTypedValueType_Short,
  SUTypedValueType_Int32,
  SUTypedValueType_Float,
  SUTypedValueType_Double,
  SUTypedValueType_Bool,
  SUTypedValueType_Color,
  SUTypedValueType_Time,
  SUTypedValueType_String,
  SUTypedValueType_Vector3D,
  SUTypedValueType_Array
};
```

**Comment by thomthom** [comment]
@BugraBarin, can this be correcting by adding `SUTypedValueType_Int16` at the end of the enum without affecting compatibility?

**Comment by TommyKaneko** [comment]
I think Int16 may be SUTypedValueType_Short ?

**Comment by thomthom** [comment]
You are right. It's just inconsistent naming.

**Comment by BugraBarin** [comment]
Yes, short is the 16-bit signed integer on our platforms. Int16 would have been a better name probably .
