### ISSUE TITLE
CAPI Feature request: SUModelGetGuid

### ISSUE THREAD

**Issue by prachtan** [SketchUp/api-issue-tracker#58]
Sketchup
Windows

RubyAPI exposes [Sketchup.active_model.guid](http://ruby.sketchup.com/Sketchup/Model.html#guid-instance_method). 

There is no options to get this `guid`during importing process through CAPI.

We can pass the model data to our system through SU plugin _(RubyAPI)_ or by importing/parsing _(CAPI)_ SKP file. Through RubyAPI we can get the `active_model.guid` to check if our internal data for the current model are valid or the model was modified and we need to update it. Unfortunately through CAPI this is not possible.

**Comment by thomthom** [comment]
Logged as SU-40223
