### ISSUE TITLE
Unexpected material duplication

### ISSUE THREAD

**Issue by noelwarr** [SketchUp/api-issue-tracker#62]
Sketchup 2017 and 2018 OSX

The following SketchUp model contains a cube and a material named "Glass"
[Magic Duplication.zip](https://github.com/SketchUp/api-issue-tracker/files/1807529/Magic.Duplication.zip)

Painting one of the faces in the scene with the bucket tool and this material will cause it to get duplicated.  Also the following snippet will cause duplication:
```ruby
Sketchup.active_model.materials[0].name = "new_name"
```

As far as I can tell this behavior is only true of materials that are created via the ruby API.
```ruby
Sketchup.active_model.materials.add("this_material_will_get_duplicated")
```

**Comment by thomthom** [comment]
I'm unable to reproduce. When I open your file in SU2018 and run `Sketchup.active_model.materials[0].name = "new_name"` it renames the material without duplication.

Can you test this yourself on a system with no extensions to ensure there are no observer magic interfering?

**Comment by noelwarren** [comment]
The following screen cast demonstrates the issue
http://somup.com/cFeojcVBgn
After recording the screen cast I not only disabled but removed Skatter and V-Ray so that they weren't even present in the extension manager and still the issue is reproducible.

**Comment by jiminy-billy-bob** [comment]
I can't reproduce it either. Have you tried on Windows? This may be OSX only

**Comment by noelwarren** [comment]
As I commented in the very first line, I have only been able to reproduce this with Sketchup 2017 and 2018 on OSX.
I am not the only one able to reproduce this.  Many V-Ray for SketchUp users experience this issue when using our product.

**Comment by thomthom** [comment]
I just tested on SU2018 on Mac and I can reproduce it.

**Comment by thomthom** [comment]
Logged as SU-38870

**Comment by noelwarren** [comment]
Is there any potential workaround for this @thomthom ?
We would love to provide a workable solution for already released SketchUp versions.

**Comment by thomthom** [comment]
I'm not sure. I was away for most of May - not sure what the status of this is. Still catching up.

**Comment by noelwarr** [comment]
Logged in the beta as SU-0277.

**Comment by thomthom** [comment]
@noelwarr can you verify the reproduction steps?

We had one scenario where the material was duplicated in the Material Browser, but not really in the model.

And we had another case where materials (in model) got duplicated after an import.

Seems to be different manifestations of this issue - so I just want to make sure we have the exact steps for the particular scenario you still observe.

**Comment by thomthom** [comment]
Also, can you verify if it's the display of material in the Material Browser that duplicates, or whether it's actual materials in the model duplicating?

**Comment by noelwarren** [comment]
It seems this issue is only partially fixed in 2019.  If you create a material via
`Sketchup.active_model.materials.add("this_material_will_get_duplicated")`
and then apply it to a face, it get's duplicated.  It now only happens once per session/model though.
Please see https://github.com/SketchUp/api-issue-tracker/files/2648766/duplicating_mat.mp4.zip for steps to reproduce

**Comment by noelwarren** [comment]
Also applying opening the initially attached model (https://github.com/SketchUp/api-issue-tracker/files/1807529/Magic.Duplication.zip) and apply the material to the face causes it to be duplicated

**Comment by thomthom** [comment]
Related internal issue: SU-39212

**Comment by thibaut2hd** [comment]
Hi,
Same duplication of material issue happening to me in SketchUp Pro 2019 19.1.173 on MacOS 10.14.5.
Particularly when using VRay for SketchUp (V-Ray for SketchUp 4.00.02 (build 97144), V-Ray NeUI Version 2.1.3), where the material duplicated in SketchUp is also present in the list of VRay materials. Contacted the VRay team who forwarded me here...

Any progress on this bug? The issue has been marked as closed but still clearly a problem in SU 2019...
Cheers,

Thibaut

**Comment by noelwarren** [comment]
This issue appears to be back in 2019.3 RC3

**Comment by thomthom** [comment]
> This issue appears to be back in 2019.3 RC3
Did it become worse?

**Comment by noelwarren** [comment]
It got worse in the sense that other possibly related issues have come up.  If you set a material to be the current one on OSX, a new material is added to the list.  It is logged in centercode as SU-0569

**Comment by DanRathbun** [comment]
@thomthom If this issue is actually not fixed, then it should be **reopened**.

**Comment by thomthom** [comment]
Finally fixed in SU2020.0 (Internal tracking: SU-39212)
