### ISSUE TITLE
Transformation2d.translation is not accurate 

### ISSUE THREAD

**Issue by 3dmod** [SketchUp/api-issue-tracker#630]
I am using the 2D translation method and not an accurate result.

My code as follows is 

```ruby
vector = Geom::Vector2d.new(0, 4.9)
tr = Geom::Transformation2d.translation(vector)
array_n = tr * [1.0, 1.0]
puts array_n
```

I am expecting:
 [1.0, 5.9]

but the result I get is

[1.0, 5.900000095367432]

This may seem close enough but with scaled drawings and dimensioning I need this level of accuracy.

**Comment by DanRathbun** [comment]
This is the result of floating point math on computers.

Use the [`Float#round`](https://ruby-doc.org/core-2.7.1/Float.html#method-i-round) method if you need to.

```ruby
array_n.map! { |n| n.round(1) }
```

> This may seem close enough but with scaled drawings and dimensioning I need this level of accuracy.

**Accurate to one tenth of a microinch ? Really ?**

FYI, SketchUp and LayOut and their APIs have an internal tolerance of only **1 thousandth of an inch**.

**Comment by Eneroth3** [comment]
This is normal numerical impression for floating point operations. The difference is about a 100th of an inch.

https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by 3dmod** [comment]
Thank you I will round the number.

When making a paper space scaled line with the following computed values.
 -4.900000095367432" in  paper space
- 1:120 scale 
- 49'-3/64" Dimension
At best it looks sloppy to a building manufacture. Yes 1 thousandth is not accurate enough.
