### ISSUE TITLE
SUTextureWriteToFile always returns SU_ERROR_SERIALISATION

### ISSUE THREAD

**Issue by u3dreal** [SketchUp/api-issue-tracker#632]
1. SketchUp/LayOut Version: SDK 2019-2021, Python3
2. OS Platform: macOS 10.13,10.15 tested both

Hello all. I’m in the process of updating the sketchup importer for blender to work with version 2.9.
So far all seems to work but the textures. It seems that SUTextureWriteToFile always returns the error. SU_ERROR_SERIALISATION

I even tried not to use a tmp folder and used a folder that exists.

in python:

                tex_name = tex.name.split("/")[-1]
                temp_dir = tempfile.gettempdir()
                skp_fname = self.filepath.split("/")[-1].split(".")[0]
                temp_dir += "/" + skp_fname
                if not os.path.isdir(temp_dir):
                    os.mkdir(temp_dir)
                temp_file_path = os.path.realpath(os.path.join(temp_dir, tex_name))
                skp_log(f"Texture saved temporarily at {temp_file_path}")
                tex.write(temp_file_path)
                img = bpy.data.images.load(temp_file_path)
                img.pack()
                # os.remove(temp_file_path)
                shutil.rmtree(temp_dir)

i do this and the cpython wrapper uses.

                cdef class Texture:
                       cdef SUTextureRef tex_ref
                
                      def __cinit__(self):
                          self.tex_ref.ptr = <void*> 0
                
                      def write(self, filename):
                          py_byte_string = filename.encode('UTF-8')
                          cdef const char* file_path = py_byte_string
                          check_result(SUTextureWriteToFile(self.tex_ref, file_path))

I have the strong suspicion this has to do with string -> byte conversion done in the .pyx
Python3 vs Python2 eventually.

source can be found here.
https://github.com/arindam-m/pyslapi/tree/0.21

Same error in 2021SDKmac and 2020SDKmac and 2019SDKmac

Windows10 works as expected. So this could be a little/big endian problem.

regards u3real

**Comment by thomthom** [comment]
`SUTextureWriteToFile` returned for any reason the file might fail to write. So your speculation about string/byte conversion would be a good guess.

As long as the input path to `SUTextureWriteToFile` is UTF-8 then it should work. Using the function directly via C works, that we can assert. 

If you could provide a way to easily run an example where this occur I could try to step through via the debugger and look for clues to where it fails, as the error code isn't very granular.

Where is your string handling code that might be relevant for the strings passed to the function? 

> Hello all. I’m in the process of updating the sketchup importer for blender to work with version 2.9.

So this used to work at some point? Recently?

(btw, that link in your post leads to a different URL than what the link text suggests)

**Comment by u3dreal** [comment]
Hello Thomthom .. first thanks for the reply.

"As long as the input path to SUTextureWriteToFile is UTF-8"

I think this is done here ..
`py_byte_string = filename.encode('UTF-8')`

could there be a problem with python ? .. i doubt that. I use 3.7.7 for Blender 2.92

"So this used to work at some point? Recently?"

As far as i know it never worked. At least in Blender 2.8+

here is the link to the source.
[https://github.com/arindam-m/pyslapi](url)

I will think of a fast way to reproduce this but i think installing the addon in Blender and importing an .skp with textures is the fastest way.  Could i do some debugging ?? I have gdb installed.

Thanks again for your help !

u3dreal

**Comment by u3dreal** [comment]
OK here is my git of the importer.
[https://github.com/u3dreal/pyslapi?organization=u3dreal&organization=u3dreal](url)

All the python stuff is here 

[https://github.com/u3dreal/pyslapi/blob/master/sketchup_importer/__init__.py](url)

and the .pyx stuff
[https://github.com/u3dreal/pyslapi/tree/master/slapi](url)

more texture here
[https://github.com/u3dreal/pyslapi/blob/master/slapi/model/texture.pxd](url)

i also attached a working ( not the textures ) version and a demo file

regards u3dreal

[sketchup_importer.zip](https://github.com/SketchUp/api-issue-tracker/files/6377930/sketchup_importer.zip)
[001.skp.zip](https://github.com/SketchUp/api-issue-tracker/files/6377982/001.skp.zip)

**Comment by thomthom** [comment]
Thank you. I will try to run this through the debugger tomorrow. (I was planning on stepping through the code in the C API function, which I should be able to do by replacing the SketchUpAPI.dll with a debug build and attach to the Blender process.) I'll report back my finding and we'll see if we can make some sense of what is happening on the python side.

My initial guess it that we might see a mangled UTF-8 string being passed on.

**Comment by thomthom** [comment]
> I will think of a fast way to reproduce this but i think installing the addon in Blender and importing an .skp with textures is the fastest way. Could i do some debugging ??

Meanwhile, if you have time, are you able to debug the python layer? Possibly dump the bytes of the string being passed on to `SUTextureWriteToFile`/`SUTextureWriteOriginalToFile`?

**Comment by u3dreal** [comment]
Ok i forgot the encoding happens here .. it's been a while sorry

[https://github.com/u3dreal/pyslapi/blob/30e9fd2933354884f9e01ace2b3bbda7536e8228/sketchup.pyx#L327](url)

I will just add print statemants there and post the results.

**Comment by u3dreal** [comment]
OK here is the debug lines 

`def write(self, filename):
        print(filename)
        py_byte_string = filename.encode('UTF-8')
        print(py_byte_string)
        cdef const char* file_path = py_byte_string
        print(file_path)
        check_result(SUTextureWriteToFile(self.tex_ref, file_path))`

and the output

`/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine wood medium color texture-seamless.jpg
b'/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine wood medium color texture-seamless.jpg'
b'/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine wood medium color texture-seamless.jpg'`

**Comment by u3dreal** [comment]
Nope when i replace " " with "_" in the filename it does not work either

`/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine_wood_medium_color_texture-seamless.jpg
b'/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine_wood_medium_color_texture-seamless.jpg'
b'/var/folders/zh/g9zxh0gs09v2j_tfw8by4v0r0000gn/T/119_fine_wood_medium_color_texture-seamless.jpg'
SU_ERROR_SERIALIZATION
Python: Traceback (most recent call last):
  File "/Users/drquader/GitHub/Blender_Addons_2020/addons/sketchup_importer/__init__.py", line 977, in execute
    context, **keywords)
  File "/Users/drquader/GitHub/Blender_Addons_2020/addons/sketchup_importer/__init__.py", line 235, in load
    self.write_materials(self.skp_model.materials)
  File "/Users/drquader/GitHub/Blender_Addons_2020/addons/sketchup_importer/__init__.py", line 431, in write_materials
    tex.write(tmp_name)
  File "sketchup.pyx", line 333, in sketchup.Texture.write
  File "sketchup.pyx", line 62, in sketchup.check_result
RuntimeError: Sketchup library giving unexpected results SU_ERROR_SERIALIZATION`

**Comment by u3dreal** [comment]
No my git is for the mac version for now ... but it should work on both. :)

How to install plugin.

Goto Edit->Prefrences-> Addon->Install from file-> select the .zip-> enable addon-> exit prefrenes
or
[https://www.youtube.com/watch?v=LzdoUTvAgXk](url)

Thank you soooo much for your effords !!! I hope we will not find out i made a stupid mistake ...

**Comment by thomthom** [comment]
Things got rather busy this week, I might have to revisit this after the weekend.

**Comment by thomthom** [comment]
> How to install plugin. 

Thank you!

> No my git is for the mac version for now ... but it should work on both. :)

When you say it should work on both, do you mean it will in the future? Or can I grab a Windows version of this now? I'm asking because I work most of my time on Windows and I'm much more familiar with the tools on this platform. If this issue can be replicated on Windows then I'd probably have a much easier time debugging it there.

---

Btw, how are you adding links to your post? They are not working correctly. I went and corrected them yesterday. But look at your newest - the links doesn't go anywhere. You are putting the URL in the section for the title and a "url" title where the URL should be. That being said, you can put the URL directly in the comment without markup and GitHub will make it clickable.

**Comment by thomthom** [comment]
I installed Blender, and the plugin, then tried to import a simple model without any textures. But I saw nothing imported into Blender. Not sure if also that ran into errors... Any place to look for errors/warnings?

**Comment by u3dreal** [comment]
OK  if there are no textures then it should work .. if you like you could share your .skp so i can make clear it works with my exporter .

For errors start Blender from terminal .. that's the best way to get "feedback". Are you on macos ??

**Comment by thomthom** [comment]
I have a Windows machine and a macOS machine, since our product is released on both platforms. But I'm 99% of the time in Windows, so I fumble a bit more when I'm on macOS.

Here's the textureless  file I tried:

[Simple.zip](https://github.com/SketchUp/api-issue-tracker/files/6403727/Simple.zip)

**Comment by u3dreal** [comment]
Here is what happens when i import the simple.skp

`SU | Importing: /Users/drquader/Downloads/Simple.skp
throw CArchiveException: 5
SU_ERROR_SERIALIZATION
SU | Error reading input file: /Users/drquader/Downloads/Simple.skp
SU | Sketchup library giving unexpected results SU_ERROR_SERIALIZATION
`

**Comment by u3dreal** [comment]
i have compiled with SDK 2021 .. maybe wrong version ??

**Comment by thomthom** [comment]
SDK 2021 is the latest one, that should work... that's the latest one and is able to read all older versions. (Unless I created it with a newer dev version - I might have gotten my executables mixed up... I'll check).

Sidenote: are you using the deprecated `SUModelCreateFromFile` or the newer `SUModelCreateFromFileWithStatus`?

**Comment by u3dreal** [comment]
<img width="611" alt="Bildschirmfoto 2021-04-30 um 15 24 06" src="https://user-images.githubusercontent.com/48415446/116701435-30ab0600-a9c8-11eb-9c9e-8a6205ef3514.png">

Looks like yes .. can i just replace the "SUModelCreateFromFile" with "SUModelCreateFromFileWithStatus" ?

Have not really looked into that so far.

**Comment by u3dreal** [comment]
I tried to update to SUModelCreateFromFileWithStatus

[Here are the latest changes](https://github.com/u3dreal/pyslapi/commit/bcda07da8db09fafc1a51d59a8e0bd3edc5476d8)

It does not compile

`MacBook-Pro:pyslapi drquader$ python setup.py build_ext --inplace
running build_ext
cythoning sketchup.pyx to sketchup.cpp

Error compiling Cython file:
------------------------------------------------------------
...
    def from_file(filename):
        res = Model(__skip_init=True)
        py_byte_string = filename.encode('UTF-8')
        cdef const char* f = py_byte_string
        #check_result(SUModelCreateFromFile(&(res.model), f))
        check_result(SUModelCreateFromFileWithStatus(&(res.model), f)) #, status))
                                                   ^
------------------------------------------------------------

sketchup.pyx:959:52: Call with wrong number of arguments (expected 3, got 2)
building 'sketchup' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Iheaders -I/Users/drquader/.pyenv/versions/3.7.7/include/python3.7m -c sketchup.cpp -o build/temp.macosx-10.13-x86_64-3.7/sketchup.o -mmacosx-version-min=10.13 -F.
sketchup.cpp:1:2: error: Do not use this file, it is the result of a failed Cython compilation.
#error Do not use this file, it is the result of a failed Cython compilation.
 ^
1 error generated.
error: command 'clang' failed with exit status 1`

Unfortunatelly i'm not really proficient enough in C / Cython :(

**Comment by u3dreal** [comment]
OK with these changes it is working :) i now use SUModelCreateFromFileWithStatus

[commit](https://github.com/u3dreal/pyslapi/commit/e9288f43879d1065a1158eeac2429c6d933e32e1)

but the simple.skp still does not work

`SU | Importing: /Users/drquader/Downloads/Simple.skp
throw CArchiveException: 5
SU_ERROR_SERIALIZATION
SU | Error reading input file: /Users/drquader/Downloads/Simple.skp
SU | Sketchup library giving unexpected results SU_ERROR_SERIALIZATION`

**Comment by thomthom** [comment]
> Looks like yes .. can i just replace the "SUModelCreateFromFile" with "SUModelCreateFromFileWithStatus" ?

As of SU2021 we changed the internals of the fileformat. We made it such that it would be possible to open a newer version of SKP. However, if you do, you might not be able to read all the data if you are on an older SDK. Whether that is critical for the application is up to the application to decide, that's what the new argument is for; letting you choose to continue or fail.

Thanks for the updated importer. I'll try step through with the debugger and see where it chokes.

**Comment by thomthom** [comment]
After installing a plugin, where are the files located? I'd like to replace SketchUpAPI.frameworkd with a development build.

**Comment by thomthom** [comment]
Btw, I found that after I back-saved the .skp to an older version (SU2017) the Simple test model imported fine. I think the one I gave you was from a dev-build. (But then again, if you used SUModelCreateFromFileWithStatus with the argument that allows it to open newer files that should work.) Maybe my installation of the new version didn't work properly...

[Simple-SU2017.skp.zip](https://github.com/SketchUp/api-issue-tracker/files/6414476/Simple-SU2017.skp.zip)

**Comment by u3dreal** [comment]
Hi Thom you can find the plugins on macOS in /Home/Library/Apllication Support/Blender/2.92/scripts/addons/sketchup-importer.

Another idea would be to unzip the addon -- replace the SDK -- and zip it again before you install.

**Comment by thomthom** [comment]
I figured out where the plugins are installed in Blender. And that to debug third party app (for plugin development) on macOS these days one need to re-sign the application. I'm now able to step through the SketchUpAPI code as it's being run by your plugin in Blender. Lets see what we can find.

**Comment by u3dreal** [comment]
Hmm i thought about signing but it didn't help ... ah maybe it will be necessary on BigSur .. still running HighSierra
Cool all the best for a fast fix :)

**Comment by thomthom** [comment]
> Hmm i thought about signing but it didn't help

The issue with debugging was that Xcode won't let you Attach To Process for an app that has been signed by a third party. I resigned it with a local codesign and then I was good to go to debug.

**Comment by u3dreal** [comment]
Ah OK yes security is key on mac ;)

**Comment by thomthom** [comment]
> Blender although is signed to allow loading unsigned third party libs.
> So as long as the SDK is signed it should work since sketchup.so only loads signed libs.

It wasn't an issue loading the SDK either. It was that I wasn't allowed to attach the debugger to Blender without re-signing.

**Comment by thomthom** [comment]
While debugging I found that the textures are not being loaded properly when the model is loaded by this plugin via Blender. It looks like the plugin isn't calling `SUInitialize` and `SUTerminate`.

I'm not familiar enough with this plugin to test it out myself, but before you start the import, call `SUInitialize` then afterwards call `SUTerminate`.

Can you try that out please?

**Comment by u3dreal** [comment]
OK I will have a look ... but why in h... does it work in windows ... i will check that as well since i only heard it works.
Will have to install windows ... we'll see

**Comment by u3dreal** [comment]
wow i am happy ..

adding two more functions to the sketchup.pyx ( initialize and terminate ) and calling them before and after the import does the trick ...
what can i say.  THANK YOU SO MUCH !!! Perfect Support !!!!

After all this would it be a good idea to provide debug versions of the SDK ??
Thank you again.

**Comment by thomthom** [comment]
> OK I will have a look ... but why in h... does it work in windows ...

Really? That surprises me. The C API really needs `SUInitialize` and `SUTerminate` for it to function properly.

> After all this would it be a good idea to provide debug versions of the SDK ??

You mean with debug symbols? I don't think that would have given you much info in this case. When I found the material not being serialized I was deep in the core code of SketchUp. We cannot provide symbols or source code for that being a proprietary product.

> Thank you again. and again .. so far all the models i tested are working.

I'm glad to hear. And I learned how to debug plugins in third party applications on macOS. :)

**Comment by u3dreal** [comment]
Yes i understand .. thank you !

**Comment by DanRathbun** [comment]
> The C API really needs `SUInitialize` and `SUTerminate` for it to function properly.

I am surprised that you (u3dreal) missed it. It is told you on the C API introduction page in the examples.
This page also has rules for memory management. All C API users should read this page **carefully**.

**Comment by u3dreal** [comment]
Like i said i only wanted to fix the existing addon and did not go into cpython for now ... so i assumend that the cython part was correct since it worked without textures and like a friend told me on windows.

So i had to make myself familiar with the cython code first. I had a look at the api documentation yesterday.
I saw that there was this example which CREARLY states the use of SUInitialize and SUTerminate.

So thank's again for bringing me onto the right track.
