### ISSUE TITLE
SketchUp Extension UX Guidelines page needs oEmbed & OpenGraph tags corrected

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#634]
### SketchUp Ruby API Documentation Issue

**SketchUp Extension UX Guidelines page needs oEmbed & OpenGraph tags corrected.**

https://sketchup.github.io/sketchup-extension-ux-guidelines/

When we paste this URL into the SketchUp forum, it renders as:

> **Homepage | SketchUp Developer**
> Sorry, we were unable to generate a preview for this web page, because the following oEmbed / OpenGraph tags could not be found: description, image

**Comment by thomthom** [comment]
Hm... I'm not sure how much control we have over that, using GitHub pages. Will have to look closer at how they work.

@Eneroth3 - any ideas?

**Comment by Eneroth3** [comment]
A preview could be nice to have but is not actually needed. Links can still be posted just fine, but don't get an image or text automatically shown next to them. There are several other SketchUp websites that doesn't implement these optional interfaces, including our developer center, the Extension Warehouse and 3D Warehouse.

If a preview image is added I don't know which one it would be. Some examples have images, some don't, and there is no single image that represents the page as a whole as you might have for a news article.

**Comment by DanRathbun** [comment]
> Hm... I'm not sure how much control we have over that, using GitHub pages.

This is weird. We had talked about tutorial pages in the past being another project repo, that the API doc YARD template could use to build into the "Files" section.

As a repo, the API gurus could help write articles and examples and open PRs.

I see that the Guidelines are a (relatively) new repo. But is creating a new repo for every article efficient in a maintainability sense ?

Here is the reason the **title** is wrong ... 
**it was copied (from developer.sketchup.com,) but not changed for the guidelines** ...
```html
<!DOCTYPE html>
<!--
  Shamelessly copied html from developer.sketchup.com.
-->
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="https://developer.sketchup.com/sites/developer.sketchup.com/files/Favicon.ico" type="image/vnd.microsoft.icon" />
    <title>Homepage | SketchUp Developer</title>
```

@Eneroth3 I didn't realize there was a repo for the guidelines when I opened an issue in this repo.
Anyway I forked the guidelines repo, edited the "default.html" page, and opened a PR:
https://github.com/SketchUp/sketchup-extension-ux-guidelines/pull/2

> If a preview image is added I don't know which one it would be.

**I doesn't need to be a preview of the page.** 


| For the Ruby API docs oEmbeds / OpenGraph entries, we **currently** are using a ruby in a red circle icon ... | ![160,160](https://ruby.sketchup.com/images/Ruby.svg) | 
| ------ | ------ |
... but the icon for API doc pages as a whole has been changed to the new blue application logo | ----- |

----

**Do y'all think we should update the API icon to have a nice Trimble blue rounded square around the gem instead of a red circle ?**

**Comment by Eneroth3** [comment]
I've commented on the PR.

Regarding the Ruby API icon, we have a blue version used on https://developer.sketchup.com/.

**Comment by DanRathbun** [comment]
> I've commented on the PR.

I don't see a PR comment or any review comments.

> Regarding the Ruby API icon, we have a blue version used on https://developer.sketchup.com/.

Okay, changed the image URLs to the blue Ruby icon and added this change to the PR commits.

**Comment by Eneroth3** [comment]
Forgot submitting the review. Internally we use other tools with another UI for PRs. It should be visible now.

Can you change the icon to the general SU icon? The extension UX project isn't necessarily Ruby specific.

**Comment by DanRathbun** [comment]
> Can you change the icon to the general SU icon?

Oh ... the Application icon, ... yeah can do.

**Comment by DanRathbun** [comment]
> Can you change the icon to the general SU icon?

Oh ... the Application icon, ... yeah can do.

**Comment by DanRathbun** [comment]
Or the favicon that goes in the browser tabs ?

![](https://developer.sketchup.com/sites/developer.sketchup.com/files/Favicon.ico)

**Comment by DanRathbun** [comment]
If the latter, I'd need a URL for a good png. 60x60 for the forum (OpenGraph)
which will be shown 120square on Twitter.

**Comment by Eneroth3** [comment]
I can't find an address to a good icon but I've asked internally. I'm sure we have one somewhere.

Since we don't have a generic extensibility icon, the SketchUp icon is the most appropriate. This isn't really specific to the Extension Warehouse but could be used with any SketchUp extension development, regardless of wherever the result is published.

**Comment by thomthom** [comment]
I think we should use the SketchUp logo for this. EW logo is not accurate representation for these guidelines.

We'll get the image resources when the US office wakes up. As mentioned in my comment, we should host the image resources with this repo. That gives us full control over the URLs and life-time of the assets.

**Comment by DanRathbun** [comment]
Okay ... then I'd suggest putting it somewhere beneath the "assets" folder, so it is kept separate from the content images.

**Comment by Eneroth3** [comment]
Finally got the image!

[SketchUp-Mark-RGB.zip](https://github.com/SketchUp/api-issue-tracker/files/6435315/SketchUp-Mark-RGB.zip)

**Comment by DanRathbun** [comment]
That's a SVG. Is that okay for embedded images in all current browsers ?
(I guess we no longer care about MSIE, since they've switched to Chrome-based Edge.)

**Comment by DanRathbun** [comment]
Okay... now **another decision** for y'all.

What will be the **site name** ?

- [ ] SketchUp Developer Resources
- [ ] SketchUp Developer HandBook
- [ ] SketchUp Developer WebBook
- [ ] SketchUp Developer Knowledgebase
- [ ] SketchUp Developer Documentation
- [ ] SketchUp Developer Help Center
- [ ] SketchUp Developer Center
- [ ] SketchUp Developer Guides

... or something else ?

This goes in the "name" and "site-name" properties.

(The document title goes in the "title" properties.)

Make a choice and then open a new review requesting the change to the PR, please.

**Comment by Eneroth3** [comment]
The name of the site is "SketchUp Extension UX Guidelines" as stated in the PR.

This is a new project of its own, currently consisting of a single page. This is not a part of the Ruby API, the SDK or Extension Warehouse. We do not plan to consolidate it with any other resources (that we do not have) into a new general "Developer Knowledgebase" project or the like.

**Comment by DanRathbun** [comment]
> The name of the site is "SketchUp Extension UX Guidelines" as stated in the PR.

Okay, then it will look a bit weird in the onebox, because this will appear twice, one above the other.

The site name appears first (in regular text) at top left of the box,
then below this the icon and to the right of it, the emboldened document title,
and below the title, the document description.

**Comment by DanRathbun** [comment]
**Okay, made requested changes for y'all in the [PR](https://github.com/SketchUp/sketchup-extension-ux-guidelines/pull/2).**

> _Dan said:_ _The **site name** appears first (in regular text) at top left of the box_, ...

It occurred to whilst mowing the lawn, that even though the "top line" is _meant_ to be a site name, it does not have to be. There is no OpenGraph police that I know of. ;)

GitHub puts a URL in the site name property.

It could just as well be an introduction like: "The SketchUp Extensibility Team presents:", or "Of interest to SketchUp developers:" or "Developers please read and consider following:"(and then below you have the large icon and the emboldened "**SketchUp Extension UX Guidelines**", following below by the description.)

**Comment by DanRathbun** [comment]
**CLOSING** - This was **completed** per the merging (by @thomthom) of the [issue](https://github.com/SketchUp/sketchup-extension-ux-guidelines/pull/2) filed against the guidelines' repository.
