### ISSUE TITLE
model.name 

### ISSUE THREAD

**Issue by mariocha** [SketchUp/api-issue-tracker#636]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/Version:  2021
2. OS Platform: Big Sur

Trying to get the name of the model in my extension
Model is saved with a name.
Closed.
Reopen

```
model = Sketchup.active_model
name = model.name
puts name
```

Does not return anything.

**Comment by Eneroth3** [comment]
Do you specifically set the name field before saving the model? This is the field that corresponds to the component definition name, and isn't the same as the file name.

**Comment by mariocha** [comment]
Ah, ok. I wasn't aware there was 2 possible names.
I found it in Model Info.
Wonder why this is not auto-filed when model is saved.
When would one need it a second name ?

**Comment by DanRathbun** [comment]
**A:** When the model is used as a component.

> _Wonder why this is not auto-filed when model is saved._

The [`model.title`](https://ruby.sketchup.com/Sketchup/Model.html#title-instance_method) which **is** the filename without the **.skp** extension, will be automatically set when the model is saved. Before this it will be an empty String.

**Comment by mariocha** [comment]
Thanks Dan.

**Comment by DanRathbun** [comment]
Your welcome. Also [`model.path`](https://ruby.sketchup.com/Sketchup/Model.html#path-instance_method) is also filled out when the model is saved. Otherwise it is an empty string.

(You can close this issue as it isn't actually an issue.)

**Comment by thomthom** [comment]
Reopening to use it as documentation improvement. This and `model.description` need better explaination.

https://ruby.sketchup.com/Sketchup/Model.html#name-instance_method
https://ruby.sketchup.com/Sketchup/Model.html#description-instance_method

**Comment by mariocha** [comment]
Indeed.
