### ISSUE TITLE
Insert link to UI::HtmlDialog Examples in class Overview section

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#64]
#### API Documentation: **`UI::HtmlDialog`**

Insert link to UI::HtmlDialog Examples in class Overview section.
https://github.com/SketchUp/htmldialog-examples

If those migrating from **`UI::WebDialog`** read the examples from DevCamp 2017, they'll be less likely to be posting the "_HtmlDialog alternative to `get_element_value()`_" threads in the forum.

Also the first sentence could have the word "asynchronously" following the word "interact" so the readers would hopefully get the idea. Or, perhaps even a more blunt statement that informs the readers that the new class does not have synchronous communication at all.

**Comment by thomthom** [comment]
Logged as SU-40218

**Comment by Eneroth3** [comment]
I like the idea of clarifying HtmlDialogs are asynchronous, but maybe not in the first sentence or paragraph as that focuses on what the purpose of the class is. The asynchronous info is mostly relevant to those familiar with WebDialogs but may not say that much to a new developer without any prior expectations of this behavior.

Maybe it's best to add a new paragraph that highlights several differences/benefits from WebDialogs, to help those migrating but also allowing new users to more easily filter this out?
