### ISSUE TITLE
`DefinitionList` does not show links to superclass inherited methods

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#651]
#### SketchUp Ruby API Documentation Issue

**[`DefinitionList`](https://ruby.sketchup.com/Sketchup/DefinitionList.html) does not show links to superclass inherited methods.**

I see in the stubs repo that recent commits are removing the `Sketchup::` prefix qualifications from the superclass stated in the class declarations. In most classes YARD has no issue linking things. 

But for some reason [`DefinitionList`](https://ruby.sketchup.com/Sketchup/DefinitionList.html) page is not linked to [`Entity`](https://ruby.sketchup.com/Sketchup/Entity.html) (at the top of the page,) nor does the section for inherited [`Entity`](https://ruby.sketchup.com/Sketchup/Entity.html) methods show.

**Comment by Eneroth3** [comment]
This might be an issue with what order YARD loads the source file in. Same with #652.
