### ISSUE TITLE
C API: `SUEntitiesGetActiveSectionPlane` not listed with other `SUEntitiesRef` functions

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#656]
#### C API Documentation Issue

**`SUEntitiesGetActiveSectionPlane` not listed with other `SUEntitiesRef` functions.**

**`SUEntitiesGetActiveSectionPlane`** is listed on this page:
[https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/entities_8h.html](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/entities_8h.html)

The rest of the "Interfaces for **`SUEntitiesRef`**" are on this page: [https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_entities_ref.html](https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_entities_ref.html)

----

Why are some functions not listed with others ? 

Do the terms "Member Functions", "Friends" and "Related Functions" have meaning for C, or do they only apply to C++ ?

?

**Comment by thomthom** [comment]
Thanks for catching that.

Because C doesn't have classes, but many C APIs, as SketchUp's, uses prefixes akin to how a class would group things Doxygen offers `@related` where you tie function with `struct`s.
