### ISSUE TITLE
`Sketchup::Model#delete_attribute` undocumented and differs from `Sketchup::Entity#delete_attribute`

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#659]
#### SketchUp Ruby API Issue

`Sketchup::Model#delete_attribute` is undocumented and it's behavior differs from [`Sketchup::Entity#delete_attribute`](https://ruby.sketchup.com/Sketchup/Entity.html#delete_attribute-instance_method).

REF: https://forums.sketchup.com/t/observers-and-deleted-entity-information-work-around/166128/15

Attempts to delete an attribute from an existing non-Trimble dictionary attached to a model object **fail**.

Coders are forced to access the dictionary's [`#delete_key`](https://ruby.sketchup.com/Sketchup/AttributeDictionary.html#delete_key-instance_method) method instead.

**Comment by thomthom** [comment]
`Sketchup::Model` have no `delete_attribute`. This is one of the unfortunate monkey-patches Dynamic Component adds. Extension authors should not rely on it.

Though I'm not sure why it'd act differently, it's implementation also uses `delete_key`:

```ruby
    # Implements delete_attribute to better meld with the Drawingelement class.
    #
    #   Args:
    #     dictionary_name  string name of the dictionary
    #     key  string name of the key to delete
    #
    #   Returns:
    #     nothing
    def delete_attribute(dictionary_name, key)
      begin
        attr_dict = self.attribute_dictionaries[dictionary_name]
        attr_dict.delete_key name
      rescue
      end
    end
```

**Comment by DanRathbun** [comment]
That snippet has an error. 

The `key` arg in the method _vs_ the arg `name` for the `delete_key()` call?

**This explains why the monkey-patch method does not do anything.**
(And further why suppressing exceptions with empty `rescue` clauses is a bad idea.,)

If the DC code relies upon this monkey-patch, then something in DC is likely broken.

**Comment by thomthom** [comment]
> The key arg in the method vs the arg name for the delete_key() call?

Oh yea - didn't notice that!

> If the DC code relies upon this monkey-patch, then something in DC is likely broken.

Yea, that rescue clause is really bad. Wonder if it was used to capture `attribute_dictionaries[dictionary_name]` if the dictionary didn't exist. Intent lost in time.

**Comment by DanRathbun** [comment]
> Wonder if it was used to capture `attribute_dictionaries[dictionary_name]` if the dictionary didn't exist.

Yes that (calling `delete_key` upon `nil`) and if the `attribute_dictionaries` was itself `nil`, then calling `[]` on it would **also** raise a `NoMethodError`.

It's an example of lazy coding.

----

This would be better ...
```ruby
    def delete_attribute(dictionary_name, key)
      attr_dict = self.attribute_dictionary(dictionary_name)
      return nil unless attr_dict
      attr_dict.delete_key(key)
    end
```
