### ISSUE TITLE
SUModelGetNumMaterials / SUModelGetMaterials can't get face (image) material.

### ISSUE THREAD

**Issue by prachtan** [SketchUp/api-issue-tracker#66]
1. SketchUp CAPI 2017 / 2018
2. OS Platform: Windows 10

This issue is probably related to: https://github.com/SketchUp/api-issue-tracker/issues/12

I received this skp file from one of our customer.
Don't know how they exactly did this model _(some external application maybe some SU script/plugin)_

[FaceMaterial.zip](https://github.com/SketchUp/api-issue-tracker/files/1829172/FaceMaterial.zip)

# Feature Requests

Functions `SUModelGetNumMaterials` / `SUModelGetMaterials` should allows us to collect full set of materials used in model _(image-type and layer materials too)_.

Without this, we have to traverse whole scene and examine every single face to collect all used materials.

**Comment by thomthom** [comment]
This is probably as designed - as applying Image materials to other entities cause problems. But I see the  reasoning to be able to access image materials (textures) easily.

**Comment by thomthom** [comment]
Logged as SU-40216

**Comment by thomthom** [comment]
1. Default parameters is not possible in C. That's a C++ feature.
2. So you don't really need this improvement?

**Comment by prachtan** [comment]
1). I'm sorry, I forgot it's C 🤦‍♂️ 

2). Hmm.. I'm not sure if I well understood:

We would like to get list of all used materials in SKP file _(no matter if the material was used by Layer/Image/etc.)_, but It's not necessary for us to know who used the material. We collect a full set of materials and then we export the used textures. Now, we have to go through all the geometry of the scene to make sure all the materials / textures have been collected.

**Comment by thomthom** [comment]
> but It's not necessary for us to know who used the material.
Gotcha. Thanks for clarifying.

So the above suggestion of the two functions would fulfill your needs then?

**Comment by thomthom** [comment]
Btw, why do you need this for layers?

**Comment by prachtan** [comment]
Some of our customers use the _"Color by Layers"_ function.
https://mastersketchup.com/color-by-layer/

**Comment by thomthom** [comment]
> Some of our customers use the _"Color by Layers"_ function.
But layers have colors, not materials. Wouldn't you just iterate the layers and get their colors if they have color by layer enabled?

**Comment by thomthom** [comment]
Ugh.... just saw the link. Forgot you could assign a material... I wonder if that has always been like that. I imagined you only got a color picker...

**Comment by prachtan** [comment]
Yes, there is other issue about this #7 :)

**Comment by thomthom** [comment]
Ah, yea. It's coming back to me know.

That one is tricker - because  the Ruby Object Manager doesn't have an easy way to handle materials that isn't owned my the material manager. But would be worth to consider in context with this issue. Thanks for reminding me.

**Comment by tommash** [comment]
SUModelGetNumAllMaterials()
and
SUModelGetAllMaterials()
are missing in SU2019.2
When one of this functions is used in C Extension, Ruby will not load it:
Error: #<LoadError: 127: The specified procedure could not be found.
