### ISSUE TITLE
Sketchup :: Page#layer_folders & #layers docs issues

### ISSUE THREAD

**Issue by dezmoHU** [SketchUp/api-issue-tracker#673]
[ #layer_folders](https://ruby.sketchup.com/Sketchup/Page.html#layer_folders-instance_method)
[#layers ](https://ruby.sketchup.com/Sketchup/Page.html#layers-instance_method
)
It is incorrectly stated in the documentation which method the returned value depends on.
![image](https://user-images.githubusercontent.com/88205452/127745855-628582fd-6d74-4704-afea-dc64ef0d88c4.png)

![image](https://user-images.githubusercontent.com/88205452/127745858-83f2c3b2-e4c1-441a-8bd7-6e3c7c4a97c9.png)

Correctly: the[ #use_hidden_layers?](https://ruby.sketchup.com/Sketchup/Page.html#use_hidden_layers%3F-instance_method) method must be mentioned.

( Perhaps could be good to mention in the example (Test layer visibility) that the visible_in_scene? method will return error if #use_hidden_layers? returns false. )

My personal usage:
```ruby
def layer_visible_in_page?(layer, page)
  return layer.visible? if page.parent.selected_page == page
  return nil unless page.use_hidden_layers?
  page.layers.include?(layer) == hidden_by_default?(layer)
end

def hidden_by_default?(layer)
  layer.page_behavior & LAYER_HIDDEN_BY_DEFAULT == LAYER_HIDDEN_BY_DEFAULT
end
```

See details:
[SU Forum](https://forums.sketchup.com/t/thoughts-on-class-sketchup-page-mostly-docs-issues/169968?u=dezmo)

**Comment by DanRathbun** [comment]
@dezmoHU Apparently you would need to open a new issue to correct the code example if it's **still** erroneous (as it wasn't done.)

**Comment by dezmoHU** [comment]
There must be a reason why my suggestion was ignored ...

**Comment by DanRathbun** [comment]
> There must be a reason why my suggestion was ignored ...

Likely just workload. Happens often with documentation issues. Lost count of the times I've had to **relog** type issues, etc.
