### ISSUE TITLE
Sketchup :: Page#set_visibility docs issues

### ISSUE THREAD

**Issue by dezmoHU** [SketchUp/api-issue-tracker#674]
[#set_visibility ](https://ruby.sketchup.com/Sketchup/Page.html#set_visibility-instance_method)

The documentation text should be rearranged and typo has to be corrected. Perhaps the Returns needs to be more consistently described.

![image](https://user-images.githubusercontent.com/88205452/127746161-7955d900-5f31-493a-aa01-fd282680499e.png)

See details:
[SU Forum](https://forums.sketchup.com/t/thoughts-on-class-sketchup-page-mostly-docs-issues/169968?u=dezmo)

**Comment by DanRathbun** [comment]
Wow, that's a high version number! Will the Earth still be here in 18,180 years?

**Comment by Eneroth3** [comment]
The version may refer to the method at a whole. I don't know if we tend to keep that at the bottom or move it up to the "original overload". @thomthom?

The other things need fixing.

**Comment by dezmoHU** [comment]
I would prefer to keep documented  what and when added, otherwise the readers have to go and read the release notes all the time. 

( BTW the newly added preference key (:use_content_size) mentioned here
https://github.com/SketchUp/api-issue-tracker/issues/670#issue-956934021
does not get documented from which SU version we can use. )

**Comment by Eneroth3** [comment]
I filed #680 for use_content_size's version not being mentioned in the method docs.

When steamrolling through documentation issues it's good to have things either in the original post or individual issues, so the rest of the conversation doesn't need to be studied.

**Comment by thomthom** [comment]
> The version may refer to the method at a whole. I don't know if we tend to keep that at the bottom or move it up to the "original overload". @thomthom?

Yea, the bottom `@version` is for the method overall. Overloads can have their own version tags because they are sometimes added at different times. YARD has this feature of tags propagating, from class to method to overloads.

**Comment by DanRathbun** [comment]
> When steamrolling through documentation issues it's good to have things either in the original post or individual issues, so the rest of the conversation doesn't need to be studied.

Thomas has said to us multiple times here (in the tracker,) that the entire issue thread **will** be reread when the issue is finally worked on. However, several times mentions of mistakes and etc. that are further down the thread have been overlooked. (So in practice the intention has not matched reality.)

If I am not the opener of an issue, I cannot add things to the original post that need to be considered. So **please** reread the entire issue thread and any external references given before working on API issues.

**Comment by dezmoHU** [comment]
> When steamrolling through documentation issues it's good to have things either in the original post...

I'm so sorry but I can't decide myself what is more important to be included to  my post. If you have power to do, please feel free to edit my post. 

> ..so the rest of the conversation doesn't need to be studied.
So what's the point of further comments then? (I'm just asking it, really without any intention to hurt anyone)

**Comment by Eneroth3** [comment]
> So what's the point of further comments then? (I'm just asking it, really without any intention to hurt anyone)

Further comments can clarify uncertainties, discuss workarounds and more, but in the case of "oh, this reminded me of..."-comments, it's good to log separately so it doesn't get lost in the noise.

**Comment by dezmoHU** [comment]
Oh I see now "steamrolling " = "oh, this reminded me of..." 😉

**Comment by DanRathbun** [comment]
> "oh, this reminded me of..."-comments, it's good to log separately so it doesn't get lost in the noise.

We do this because we want things fixed when y'all are at a certain place in the code. We all wish for a lower number of open issues, bugs and doc mistakes alike.

And I do end up opening a new issue when "things get overlooked".
