### ISSUE TITLE
Sketchup :: LayerFolder#<=> & #== docs issues

### ISSUE THREAD

**Issue by dezmoHU** [SketchUp/api-issue-tracker#678]
[#<=> method](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method)

The example in the documentation does not add folder, but layer.
![image](https://user-images.githubusercontent.com/88205452/127746909-9b2f9f16-4593-44fb-982a-76f18f7a518a.png)

[#== method](https://ruby.sketchup.com/Sketchup/LayerFolder.html#==-instance_method)
![image](https://user-images.githubusercontent.com/88205452/127747039-a9423010-e7e0-49f3-a481-c3c96e3fed6e.png)

Correctly: the [#add_folder(name)](https://ruby.sketchup.com/Sketchup/Layers.html#add_folder-instance_method) method must be used.

**Comment by DanRathbun** [comment]
A statement in the [`<=>`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method) method is not really all that helpful. 
ie:
"_You could use this for sorting if you're building a list of folder names._"

In reality, the implementation of a **`<=>`** operator method for a class and including the [`Comparable`](https://ruby-doc.org/core-2.7.2/Comparable.html) mixin library module, enables comparisons using the conventional comparison operator methods ([`<`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-3C), [`<=`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-3C-3D), [`==`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-3D-3D), [`>=`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-3E-3D), and [`>`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-3E)) and the method [`between?`](https://ruby-doc.org/core-2.7.2/Comparable.html#method-i-between-3F), all using the custom [`<=>`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method) method of the [`LayerFolder`](https://ruby.sketchup.com/Sketchup/LayerFolder.html) class.

In addition, the defining of the custom [`<=>`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method) operator method of the [`LayerFolder`](https://ruby.sketchup.com/Sketchup/LayerFolder.html) class, automatically enables an enumerable collection ([`Array`](https://ruby-doc.org/core-2.7.2/Array.html#method-i-sort) etc.,) consisting of members of that class, to be sorted using the non-block form of [`sort`](https://ruby-doc.org/core-2.7.2/Array.html#method-i-sort) and [`sort!`](https://ruby-doc.org/core-2.7.2/Array.html#method-i-sort-21).
So ...
```ruby
layers = Sketchup.active_model.layers
folder_set = layers.folders # returns an array
sorted_by_name = folder_set.sort
```
No block is needed.

Also, a custom [`<=>`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method) operator method and [`Comparable`](https://ruby-doc.org/core-2.7.2/Comparable.html) mixin library inclusion enables the [`max`](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-max), [`min`](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-min), and [`minmax`](https://ruby-doc.org/core-2.7.2/Enumerable.html#method-i-minmax) methods on enumerable collections of that class.

----

**The main point being that the quoted statement in the documentation obscures the real reason for the existence and benefits of the [`LayerFolder#<=>`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#%3C=%3E-instance_method) method.**

Telling the reader that they could use it to code a task that was automatically and purposefully already implemented by the said method's existence is misleading and could lead new coders to waste time writing sorting methods.

**Comment by dezmoHU** [comment]
Yes Dan, I agree, that this comparation method is more or less make no sense.  

At first, I thought it was given to achieve a similar sort as in the user interface. Kind of "natural" sorting. But, unfortunately it is not like that, as you mentioned it is same as the "normal" Array sort method.
If the comparison will give us similar result as on the UI, then it will be more useful...

Actually this will apply to comparison operator methods of layers e.g.: [Layer.#<=>-instance_method](https://ruby.sketchup.com/Sketchup/Layer.html#%3C=%3E-instance_method) too.


(Sure, the documentation is still buggy...)

**Comment by DanRathbun** [comment]
> ... as you mentioned it is same as the "normal" Array sort method.

**NO** ... I did **not** say this. It is **not** the same. 

> I agree, that this **_comparison_** method is more or less make no sense.

**It does make sense because it is necessary.** I said that the `Array#sort` (and similar core `Enumerable` caparison / sorting methods) **need** a class' **`<=>`** method in order to work when the **`Comparable`** library is mixed in. So this is the reason **why** some API classes must define a **`<=>`** method.

> If the comparison will give us similar result as on the UI, then it will be more useful...

It is implemented correctly now and **cannot** be changed as doing so could break extensions "in the wild".

There is **no** "similar result as the UI" because the UI sort can be changed by the user if they click on the column headings in the inspector list. If a coder needs a special sorting, then they will use the block form of `Array#sort`, not `LayerFolder#<=>` (nor `Layer#<=>`.)

**Comment by dezmoHU** [comment]
Okay, I understand that the class' <=> method needs to be implemented. But couldn’t it be enforced in such a way if the comparison gives a “natural” sorting method?

And again Sorry, I didn't said clearly..what I mean. 😳 (That was one of the reasons I was afraid to register to GitHub)
So, I will try again ;-)

The doc say (both similar for layer and layerfolder):
_The #<=> method is used to compare two layers **based on their names.**_

Let's create a following tags and sort by name on UI 
![image](https://user-images.githubusercontent.com/88205452/127779065-286f9b34-fdb4-476e-9946-cc513e8f5f7a.png)
The sort order is "natural" (do not consider "Untagged" now, because it is special case..)
 1, 2, 3, 22, 23

Because of the above statement of the documentation, I thought it was given to achieve a similar sort order as in the user interface. But not.
```ruby
Sketchup.active_model.layers.sort.map(&:display_name)
```
>["1", "2", "22", "3", "33", "Untagged"]
```ruby
Sketchup.active_model.layers.sort_by{|a,b| a<=>b}.map(&:display_name)
```
>["1", "2", "22", "3", "33", "Untagged"]
________
So as new coder I still need to spend some time writing sorting methods which will give similar result as you get on the UI. 😉
Fortunately there are plenty of example here (on GitHub) or all over in a web.... :-)

**Comment by DanRathbun** [comment]
> _But couldn’t it be enforced in such a way if the comparison gives a “natural” sorting method?_

NO, because it would be a breaking change. 

> _So as new coder I still need to spend some time writing sorting methods which will give similar result as you get on the UI._

Yes, as a new coder, **we all must learn** that the "natural" sort for text strings on computers sorts by ASCII code number.

> _Because of the above statement of the documentation, I thought `<=>` method was given to achieve a similar sort order as in the user interface. But not._

Exactly my point. That statement is misleading. It should be something like:
* "This method is implemented to enable the [`Comparable`](https://ruby-doc.org/core-2.7.2/Comparable.html) library methods (**`<`**, **`<=`**, **`==`**, **`>=`**, **`>`** and **`between?`**) for `LayerFolder` objects, and the [`Enumerable`](https://ruby-doc.org/core-2.7.2/Enumerable.html) library methods (**`max`**, **`min`**, **`minmax`**, **`sort`** and **`sort!`**) for **collections** of `LayerFolder` objects."

> .... _(do not consider "Untagged" now, because it is special case..)_

Your whole idea of matching the UI sort is a special case. "Untagged" is sorted by "U" which follows numeric characters in the ASCII sequence. So basically you must write a special sort that sorts numeric strings separately than word strings.

It has always been thus in computer programming.

**Comment by dezmoHU** [comment]
Thanks a lot Dan, getting more clear now! 😄 
____

> Your whole idea of matching the UI sort is a special case. "Untagged" is sorted by "U" which follows numeric characters in the ASCII sequence. So basically you must write a special sort that sorts numeric strings separately than word strings.

That's right, but I think we have to "handle" the "Untagged"/"Layer0" a little differently, because on the UI the base layer is always at the top of the list,
 I guess we have to do something like this. 
![image](https://user-images.githubusercontent.com/88205452/127966041-8111cb74-ff4b-4a0d-b180-c3e234a5b785.png)


```ruby
LAYER0 ||= Sketchup.version.to_i < 20 ? "Layer0" : "Untagged"
layers = Sketchup.active_model.layers
# Use your favorite sorting method here:
#  (as an example the easiest...)
p names_shorted = layers.sort.map(&:display_name)
# Put the base layer to the "top"
names_shorted.unshift(names_shorted.delete_at(names_shorted.index(LAYER0)))
```
Returns:
> ["100", "2", "22", "3", "33", "Untagged", "Z1"]
> ["Untagged", "100", "2", "22", "3", "33", "Z1"]

_For simplicity of the example, I only used layers now. 
But actually sorting is a bit more complicated when you want to consider the parent-child folder-layer structure. In addition, the layer folder names can be non unique, and in the UI these are seems to be sorted by the child names inside in it (?)
(I may investigate... in another topic on SU forum)_

**Comment by DanRathbun** [comment]
I would think it best that:
```ruby
names_sorted = layers.sort.map(&:display_name)
```
... be done this way ...
```ruby
names_sorted = layers.map(&:display_name).sort
```
... so that it is the display name that is used for the sort.

But here needs to be duck typing to decide whether `display_name` or `name` is used.
```ruby
names_sorted = layers[0].respond_to?(:display_name) ? layers.map(&:display_name).sort : layers.sort
```
The following would work also when a `NoMethodError` happens, but is frowned upon:
```ruby
names_sorted = layers.map(&:display_name).sort rescue layers.sort
```

----

> _But actually sorting is a bit more complicated when you want to consider the parent-child folder-layer structure._

It is actually **not** a structure. ALL layers remain children of the top level model's layers collection.
The `LayerFolder` feature is only a display feature.

But I do understand that sorting layer display names in folder groups adds complexity to a sort algorithm.

----

> Can we assume if this always returns true?
> 
> ```ruby
> Sketchup.active_model.layers.first.name == "Layer0"
> ```
> 
> My studies show that the order of layers follows the time of creation...

That is another "can of worms". See discussion in the following issue:
[Add a #most_recent (or #last) method to some SketchUp collections](https://github.com/SketchUp/api-issue-tracker/issues/272)

**Comment by dezmoHU** [comment]
With my "one liner" codes (again), I did not presented my mind clearly.  😳

My goal was to sort the layers collection, but keep the elements as reference to layer object, and ordered by name .
I used the `.map(&:display_name)` just to display the result in a "readable" form.  Maybe that's how I should have written:
```ruby
layers_sorted = layers.sort #<< this is what I want
names_sorted = layers_sorted.map(&:display_name) # << for print out to console
```

The `.name` and `display_name` method are returns the same string except for the base layer. But because we will handle that separately at the end we can use the the `sort` method which will sort by the name, without "mapping" it before. 

Actually `layers_sorted` above is not exactly what I want. The elements needs to be in "natural" sort order, which can be like this: 

```ruby
layers_nat_sorted = layers.sort{ |a,b|  mynatcompare(a,b, parameters) }

```

Where `#mynatcompare(a,b, parameters)` is a method to return -1, 0, 1 , according to natural order and a  parameter (e.g. case sensitive, locale etc.)
____

> It is actually not a structure. ALL layers remain children of the top level model's layers collection.

Yes, we still have the [#each](https://ruby.sketchup.com/Sketchup/Layers.html#each-instance_method) method is used to iterate through all of the layers in the model, regardless of the displayed structure.

But we do have now:
The [#each_folder](https://ruby.sketchup.com/Sketchup/Layers.html#each_folder-instance_method) method is used to iterate through the folders that are direct children to the layer manager.
The [#each_layer](https://ruby.sketchup.com/Sketchup/Layers.html#each_layer-instance_method) method is used to iterate through the layers that are not inside a layer folder.
These can be used to dig into the hierarchy.  Actually I'm really on it and will post my imagination on SU forum soon, after a little more testing... 😉 

____
_I will  avoid  the "can of worms" for now 😉_

**Comment by DanRathbun** [comment]
Not all issues described in this thread were fixed. The [`#==`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#==-instance_method) code snippet is still incorrect as described in the 1st post.

**Comment by thomthom** [comment]
> Not all issues described in this thread were fixed.

For any remaining issues, please open a new ticket.

**Comment by DanRathbun** [comment]
> * The [`#==`](https://ruby.sketchup.com/Sketchup/LayerFolder.html#==-instance_method) code snippet is still incorrect as described in the 1st post.

Filed new issue as requested ... https://github.com/SketchUp/api-issue-tracker/issues/768
