### ISSUE TITLE
SUComponentDefinitionRelease is not releasing "everything"

### ISSUE THREAD

**Issue by kengey** [SketchUp/api-issue-tracker#69]
1. SketchUp/LayOut Version: Sketchup C SDK 18
2. OS Platform: Windows

Describe briefly what you are doing and what is happening.

1. Create a model and add some components, re-delete all instances and save the model (attached 1.skp).
2. Load the model using the C SDK, release all component definitions with SUComponentDefinitionRelease() and save the model. (attached 1_purged.skp)
3. Open the model with SketchUp. Model statistics clearly shows that there are no definitions. The component browser shows the same. However, file size is still pretty high.
4. Do a manual purge in the component browser. (attached 1_purged_manually.skp)
5. File size is now much smaller than before the manual purge.

Describe what the expected result is.

I would expect the same file size.

Attach any relevant files.

[test_data.zip](https://github.com/SketchUp/api-issue-tracker/files/1833718/test_data.zip)

**Comment by thomthom** [comment]
Logged as SU-40213

**Comment by jinyistyle** [comment]
@kengey 
Have you tried getting all the entities using the SUModelGetNumxxx to gather the count for the entities and then SUModelGetxxx to get the array of entities and then call the appropriate release calls for them.

I noticed that there were 35 groups, which SUModelGetNumComponentDefinitions will not take into account for, so you would have to use SUModelGetNumGroupDefinitions and SUModelGetGroupDefinitions, and likewise use the SUComponentDefinitionRelease on those groups.

The reason for the above behavior is because groups and component definitions at the core are practically the same except one thing which is that a group is a definition that can only have 1 instance in the model, while a component definition can have multiple instances.

**Comment by thomthom** [comment]
> Have you tried getting all the entities using the SUModelGetNumxxx to gather the count for the entities and then SUModelGetxxx to get the array of entities and then call the appropriate release calls for them.

Note that the `Release` functions aren't meant to erase entities that is owned by the model. The only exception is `SUComponentDefinitionRelease` which was changed from just freeing memory to also act as a `Remove`/`Erase` function. Which unfortunately caused inconsistency in the C API and can mislead users to think other `Release` functions can be used the same.

But note the memory management section in the Overview:

> **Memory Management in the SketchUp C API**
> 
> The SketchUp C API does not automatically track and dispose of objects that are created. The API is a C interface, and therefore there are technical limitations to memory management.
> 
> The general rule is that after an object is created using one of the SU*Create*() functions, the object should in some way be attached to the model data hierarchy.
> 
> Some object types can be retrieved directly from an existing object without explicitly calling a create function. In this case, you should not explicitly call the matching release function, as it is already attached to an object.

> **Release the object manually**
> 
> This is done by calling the corresponding SU*Release() function. This is not the typical use case for an object, except for the model itself as well as SUStringRef objects. However, it is possible to create and release many different types of objects explicitly. This is not advised however, because in most cases an active model is necessary for a function to operate properly.

The docs also have warning for the various `Release` functions:

> **SUMaterialRelease**
> 
> Releases a material and its resources.
> 
> The material must not be associated with a parent object such as a face.

> **SUEdgeRelease**
> 
> Releases an edge object.
> 
> The edge object must have been created with SUEdgeCreate and not subsequently associated with a parent object (e.g. SUEntitiesAddEdges).

Some doesn't state it explicitly, but the general rule described in the overview is the default. `Release` should not be used on objects that is owned by the model.

For faces and edges etc (drawing elements), we have `SUEntitiesEraseEntity`. But the C API is currently lacking in functions to remove layers, materials, scenes, styles.

**Comment by kengey** [comment]
hi @jinyistyle  and @thomthom .
My mistake it seems. I was unaware that group(definitions) were kept in the model while their single instance has been deleted from the model, or when a component definition in which they are placed gets purged. After using SUModelGetNumGroupDefinitions and SUModelGetGroupDefinitions and releasing those, the result were exactly as expected.
