### ISSUE TITLE
api traker

### ISSUE THREAD

**Issue by alhmdvray** [SketchUp/api-issue-tracker#705]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version:
2. OS Platform:

Describe briefly what you are doing and what is happening.

Describe what the expected result is.

```ruby
# Complete reprodusible code snippet. (Important!)
```

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by DanRathbun** [comment]
@alhmdvray Fill out the form above **please** !
