### ISSUE TITLE
Closing modal HtmlDialog using Ruby shifts focus away from SketchUp

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#72]
Closing a modal HtmlDialog using the Ruby close method shifts focus to another window than that off SketchUp. The expected behavior would be to focus whatever windows was focused before opening the dialog, whether it was the main SketchUp window or any other window. Closing using the X in the window frame works as expected.

The same behavior can be observed in [htmldialog-inputbox](https://github.com/SketchUp/htmldialog-inputbox)

Tested in SU 2017 and 2018 on Win 8 and win 7.

    def show_dialog
      window = UI::HtmlDialog.new
      window.set_html("<button onclick=\"sketchup.close()\">Close</button>")
      window.add_action_callback('close') { window.close }
      window.center
      window.show_modal
    end

    show_dialog

Edit: Tested on Win 7 too.

**Comment by MSP-Greg** [comment]
Good find, although it kind of implies HtmlDialog adoption is rather low.  I never ported my old plugin to use HTMLDialogs, but previously, all the modal dialogs closed/cancelled with ESC.

I can't check, but wondering if the same issue occurs with MacOS.

Anyway, the attached file (lose the '.txt') seems to activate the SU window by adding a call of `Win32.activate_su_window` immediately after the `window.close` call.  May have some screen flicker...

[win32.rb.txt](https://github.com/SketchUp/api-issue-tracker/files/1846043/win32.rb.txt)

Thanks, Greg

**Comment by Eneroth3** [comment]
I haven't really used HtmlDialogs myself until SU 2018 was released, as I am typically support 2 major versions. It's a bliss not to have to worry about IE/Safari differences, especially when I can't test in a Mac environment, but there are some odd behaviors too. I wonder how many developers are actually using it, and how this issue could have been missed. Perhaps it works as expected on Win 10 and wasn't tested on Win 7 or 8, just a thought.

For the plugin I'm making now I've reverted back to non-modal dialogs (and yield user input rather than returning it) but your code seems useful for cases when modal dialogs are absolutely necessary.

Thanks

**Comment by thomthom** [comment]
> Good find, although it kind of implies HtmlDialog adoption is rather low. 
Or that modal usage is low...

> Perhaps it works as expected on Win 10 and wasn't tested on Win 7 or 8, just a thought.
This is seen on Win10 as well. Though I don't think it's seen on Mac.

This was reported a couple of weeks ago for the first time. We have it logged as SU-38689

**Comment by thomthom** [comment]
SU-38689
