### ISSUE TITLE
DisplaySectionCuts rendering option in C API docs missing

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#736]
https://extensions.sketchup.com/developers/sketchup_c_api/sketchup/struct_s_u_rendering_options_ref.html

![image](https://user-images.githubusercontent.com/192418/141293543-86c33d4c-3b4d-4b8e-a92d-8ee95e20895e.png)

**Comment by DanRathbun** [comment]
This has been already filed and logged as: https://github.com/SketchUp/api-issue-tracker/issues/690
