### ISSUE TITLE
`ComponentDefinition.save_as` changes path without being added to undo stack

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#74]
Not sure if bug or by design.

When a component is saved out to an external file its path changes. However this change is not recorded to the undo stack. I'm expected the path change to be undoable and redoable like any other model change, and to be possible to wrap inside operations.

    # Assuming model's first component is linked to a file, e.g. in Architectural template.
    definition = Sketchup.active_model.definitions.first
    definition.path
    # => "C:/ProgramData/SketchUp/SketchUp 2018/SketchUp/Components/Components Sampler/Stacy.skp" (or something similar)
    
    # Select an arbitrary file location in open panel.
    definition.save_as(UI.savepanel(definition.path))
    definition.path
    # => "C:\Users\Christina Eneroth\Desktop\lol.skp"  (or something similar)
    
    Sketchup.undo
    definition.path
    # => "C:\Users\Christina Eneroth\Desktop\lol.skp"

    # After undo I expect the original path, not the one it was changed to.

This causes issues as saving to a throwaway temporary file is a workaround for allowing SketchUp to load a component from a path already associated with a component in model, rather than just returning the existing component (see #50). If an extension tries to reload a component by 1. saving it out to a throwaway file (typically in a temp folder), 2. load the new component, 3. replace all instances of the old component with the new one and finally 4. purge the old component, all inside an operation, this action can't be fully undone. If the user tries to undo the component is associated with the temporary throwaway file, not its previous path.

Of course this behavior should not be changed merely for the workaround of #50 to work, but I find this behavior in itself quite confusing and unexpected, which is why I started a new issue with a reference rather than commenting on the existing one.

If I as a user modify a component, save it to a new path, undo my changes and reload (Context Menu > Relink...) I would expect it to be associated to the path from before I modified and saved it out. Don't break the Undo stack is one of the first rules in Extension development, and I think it applies here too.

**Comment by thomthom** [comment]
This is probably by design. But might not be expected from the API side.

Maybe there should be a distinction between "save" and "save as"....

**Comment by thomthom** [comment]
Logged as SU-40209

**Comment by Eneroth3** [comment]
After more thinking, this might be the intended (although slightly unorthodox) behavior. Saving out a component associates it with the path to the external file, but saving doesn't "feel" like a model operation so it makes sense in one way not to record it to the undo stack. Also, undoing the save would imply removing the file you saved out, which is not inside the scope of the undo stack.

**Comment by Eneroth3** [comment]
This can be addressed by implementing #480

**Comment by DanRathbun** [comment]
> @Eneroth3  _If I as a user modify a component, save it to a new path, undo my changes and reload (Context Menu > Relink...) I would expect it to be associated to the path from before I modified and saved it out. Don't break the Undo stack is one of the first rules in Extension development, and I think it applies here too._

**This sounds totally reasonable.** 

I think this issue should stay open as it's logged as both a bug and an enhancement and has a Jira issue assigned.
This issue is also about what the issue title states, not about any discussed workarounds.

I think we should let issues marked as bugs be processed by Thomas or the bot. Ie either marked with a fixed or "wont fix" label.

> @thomthom : _This is probably by design. But might not be expected from the API side.
> Maybe there should be a distinction between "save" and "save as"...._

But we do not have a "save" method.

**Comment by thomthom** [comment]
> I think this issue should stay open as it's logged as both a bug and an enhancement

Changing the current behaviour could very well lead to extensions breaking. Don't think it's likely we'd do that. Is there a workflow not addressed by the proposed `save_copy`?

**Comment by DanRathbun** [comment]
Well at least add a note to the method documentation in question that changing the **path** property is not undoable and **does not** set (ie, change) the model's `#modified?` property.

**Comment by DanRathbun** [comment]
So I suppose I will have to open a **new** issue as the warning note described above was not added to the docs.
