### ISSUE TITLE
I can't get the uv mapping of front face when the material in the group

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/api-issue-tracker#747]
I can't get the UV mapping of the front face by SDK when the material in the group.

1. SketchUp Version: SketchUp Pro 2021.1.332
2. OS Platform: Windows 10 x64
3. SDK Version: SDK_WIN_x64_2021-1-332
4. [More info](https://forums.sketchup.com/t/a-question-about-sumaterialpositioninput/184754/5?u=javalitterboy)

**Comment by thomthom** [comment]
This is the same as #746, isn't it?

**Comment by LItterBoy-GB** [comment]
I think it's different. 
Because the material in the group or not face. And the back material of the face is ok.

**Comment by thomthom** [comment]
Ah, I didn't see you referred to a new post in that thread. I was looking at the start of the thread.

**Comment by LItterBoy-GB** [comment]
@thomthom   It's okay. I can't explain it clearly. I will check my code carefully.
