### ISSUE TITLE
Uncaught exception caused by contaminated model

### ISSUE THREAD

**Issue by GreatWhite2018** [SketchUp/api-issue-tracker#749]
When I use API function SUModelCreateFromFileWithStatus to read a contaminated model, a hardware exception happens which can not be caught .

The SketchUp SDK Version is 21.0.339
OS Platform: Windows 10 Enterprise 20H2

The model can be gotten here:https://forums.sketchup.com/t/hardware-exception-caused-by-contaminated-model/184941/3

**Comment by thomthom** [comment]
Thank you for the report. We'll look into it.

Btw, have you tested with the latest SDK version? 21.1.332?

**Comment by GreatWhite2018** [comment]
> Thank you for the report. We'll look into it.
> 
> Btw, have you tested with the latest SDK version? 21.1.332?

No, I have not.

**Comment by thomthom** [comment]
Logged as SKOR-15612
