### ISSUE TITLE
Setting and copying material texture projections on face objects

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#76]
### API Issue

Refer to forum thread ...
https://forums.sketchup.com/t/how-can-i-copy-a-projected-texture-with-ruby-script/65090

The [`Sketchup::Face#set_texture_projection`](http://ruby.sketchup.com/Sketchup/Face.html#set_texture_projection-instance_method) method is marked as deprecated, and noted as never having worked correctly.

There is interest in having it work correctly. 

**Has the idea of fixing it been abandoned all together ?**

For copy projected textured materials, we'd hope something like this would work (eventually.)
```ruby
def copy_projected_face_material(face1,face2)
  unless face1.material.nil?
    frontside = true
    face2.material= face1.material
    face2.set_texture_projection( face1.get_texture_projection(frontside), frontside )
  end
  unless face1.back_material.nil?
    frontside = false
    face2.back_material= face1.back_material
    face2.set_texture_projection( face1.get_texture_projection(frontside), frontside )
  end
  nil
end
```

(**EDIT**: Corrected per sdmitch in public forum thread.)

----

_Related perhaps:_

FR: [C API function to set texture scale](https://github.com/SketchUp/api-issue-tracker/issues/40)

**Comment by DanRathbun** [comment]
Hmm, ... why does it seem to work in some situations ?

I guess this is a documentation issue, where the docs are vague as to why **this** method is considered not to work properly.

**Comment by thomthom** [comment]
> This info needs to be added to the docs to explain and warn coders.
It already have a `@deprecation` tag - what info would you like to see added? The part about possibly triggering "Fix Model"?

**Comment by DanRathbun** [comment]
> ... what info would you like to see added? The part about possibly triggering "Fix Model"?

Yes. And the warning that it is likely to be removed when bteer working API features are added.

(But this probable means an issue in the stubs tracker.)

**Comment by thomthom** [comment]
Logged as SU-40207

**Comment by DanRathbun** [comment]
The warning was added to the docs and the abilities were added (mostly) via new methods as mentioned in [Issue 470](https://github.com/SketchUp/api-issue-tracker/issues/470#issuecomment-860088192).

----

An example using the new v2021.1 functionality:

```ruby
# Copy face materials (front and back) from a source face to a target face.
# For v2021.1 and higher, any texture positioning and projection is copied.
# @param face1 [Sketchup::Face] the source face.
# @param face2 [Sketchup::Face] the target face.
# @return [Boolean] whether texture positioning was enabled during copy.
def copy_face_materials(face1, face2)
  # Test if the API is at or higher than 2021.1:
  positioning_enabled = face1.respond_to?(:texture_projected?)
  #
  frontside = true
  backside  = false
  reference = face1.vertices.first.position
  #
  for side in [frontside, backside]

    meth =( side ? :material : :back_material )
    matl = face1.send(meth)

    # Copy this side's material (might set to nil):
    face2.send("#{meth.to_s}=", matl)

    next unless positioning_enabled

    # If this side's material has a texture and is positioned:
    if matl.texture && face1.texture_positioned?(side)
      mapping = face.uv_tile_at(reference, side)
      if face1.texture_projected?(side)
        face2.position_material(
          matl, mapping, side, 
          face1.get_texture_projection(side)
        )
      else
        face2.position_material(matl, mapping, side)
      end
    end

  end # for side
  #
  return positioning_enabled
end
```

~
