### ISSUE TITLE
Sketchup::ComponentDefinition#name= Does not update DefinitionList

### ISSUE THREAD

**Issue by 3dmod** [SketchUp/api-issue-tracker#778]
SketchUp/LayOut Version: 2022.0.315
OS Platform: Monterey 12.2.1

Describe briefly what you are doing and what is happening.

If you change the name of ComponentDefinition using Sketchup::ComponentDefinition#name= then the DefinitionList does not remove the previous name or add the new name.

Describe what the expected result is.

In the code snippet below you can see the following steps

1. Component with the Name "New" is added to DefinitionList. 
2. Component with the Name "New" has name changed to "New#1"
- 2a. Here the following returns nil - Sketchup.active_model.definitions["New"]
3. Component with the Name "New#1" is added to DefinitionList.

Outcomes
Step 3 should be adding a Component with the Name "New" to the the DefinitionList
If you do the same steps with UI instead of code you see the desired outcome.

```ruby
Sketchup.active_model.definitions.add "New"
Sketchup.active_model.definitions["New"].name = Sketchup.active_model.definitions.unique_name "New" 
Sketchup.active_model.definitions.add "New"
```

A screen capture of the above.
https://user-images.githubusercontent.com/76130464/158623478-5845c398-1e9f-4f05-bfef-7fd80a0d0b89.mov

**Comment by DanRathbun** [comment]
Tested on Windows 10 64-bit under SketchUp `v22.0.354` and the code snippet **works as expected**.

@3dmod Suggest that you **update** to `v22.0.353` for Mac and **restest**.

REF: https://help.sketchup.com/release-notes/sketchup-desktop-202201

**Comment by thomthom** [comment]
Yea, this is a regressions in the first release of SU2022.0 fixed in the patch update.
