### ISSUE TITLE
C API missing ability to set the material size

### ISSUE THREAD

**Issue by thomthom** [SketchUp/api-issue-tracker#783]
When a material has a texture, the C API is missing the ability to set its world space dimmensions:
https://forums.sketchup.com/t/a-question-about-sumaterialpositioninput/184754/12?u=tt_su

In the Ruby API this is done by `Sketchup::Texture#size=`
https://ruby.sketchup.com/Sketchup/Texture.html#size=-instance_method

**Comment by DanRathbun** [comment]
How does this differ from Issue #40 ?

**Comment by thomthom** [comment]
Ugh, it had the wrong label (`documentation` instead of `parity`). I'd filtered out documentation issues.

Duplicate of #40

**Comment by DanRathbun** [comment]
@thomthom Actually, I think that this issue is indeed different (although) related to #40.

How does code get the width and height (in inches) of a texture when all the C API functions return (or accept) values in pixels ?

I've tried assuming that texture images are 96 ppi but the math doesn't "add up".

**Comment by DanRathbun** [comment]
Perhaps remove **duplicate** label and reopen this issue ?

**Comment by thomthom** [comment]
> How does code get the width and height (in inches) of a texture when all the C API functions return (or accept) values in pixels ?

To get the user define size of a texture on a material in SketchUp you use the scaling factor returned from `SUTextureGetDimensions`. Apply that to the pixel size and you get the defined model size.

**Comment by DanRathbun** [comment]
According to the docs, the scaling values are **not** used when a textured material is directly applied to a face.

Ordinarily we think of a scaling factor as a ratio.

For the "Brick Antique 01" material, we want to get 58.0 inches.

The image is `384` pixels wide and the scaling `s_scale` of `0.01724138`. The product of these values is `6.62068992`.
If we then divide the pixel width by this product we get `58.0`. This seems weird.

It really reduces to the the width (with a bit of floating point error) equals the reciprocal of the scale values:
```
               pixel_width            1
inch_width = ----------------  =  ---------
          pixel_width * s_scale    s_scale
```

**This should be documented**.
