### ISSUE TITLE
Loading outside components is taking a lot of time for files as big as 400MB.

### ISSUE THREAD

**Issue by Nithin-1997** [SketchUp/api-issue-tracker#807]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version:
2. OS Platform:

Describe briefly what you are doing and what is happening.

Describe what the expected result is.

```ruby
# Complete reprodusible code snippet. (Important!)
```

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by thomthom** [comment]
We need more information to go by than this.

What SketchUp version(s)? What are the times you are seeing?
Can you send us a sample model? (developer-support@sketchup.com)

**Comment by DanRathbun** [comment]
REF: https://forums.sketchup.com/t/loading-a-definition-to-the-model/203267

**Comment by thomthom** [comment]
Closing this as we cannot work it without example models. If you want to send the model privately you can use developer-support@sketchup.com

**Comment by Nithin-1997** [comment]
I've sent the model to the above-mentioned email id
