### ISSUE TITLE
C-API SUModelSetGeoReference() call does not *truly* geo-locate the Sketchup file.

### ISSUE THREAD

**Issue by jonnyns** [SketchUp/api-issue-tracker#82]
**Probable bug:**
C-API SUModelSetGeoReference() call does not *truly* geo-locate the Sketchup file.

**Environment:**
Sketchup 2018 and Sketchup C-API SDK_Win_x64_18-0-18664. Compilation: 64-bit DLL.

**Observations:**
Using the C-API SDK in an importer DLL, I attempt to geo-locate the resulting file.
I calculate the *latitude* and *longitude* values and use the C-API call:

```c
su_res = SUModelSetGeoReference(model_, latitude, longitude, height, true, false);
This returns su_res == SU_ERROR_NONE
```

Immediately I check the state as this:
bool ok;

```c
su_res = SUModelIsGeoReferenced(model_, &ok);
This returns su_res == SU_ERROR_NONE and ok == true
```

However, after successfull import, the Sketchup Model Info / Geo-location dialog box 
claims “This model is not geolocated”

But, the dialog button “Set Manual Location…” *will* present a dialog and show the *very same* 
information entered in the call `SUModelSetGeoReference()`.
Thus… the `SUModelSetGeoReference()` call works - kind of - but Sketchup is *still* not satisfied.

Now, pressing the “Set Manual Geo-Location” dialog "OK" button *will* geo-locate the file, 
but *only* if the user manually *alters* one of the four displayed values.

**Expectation:**
That a succesfull C-API `SUModelSetGeoReference()` call would lead to Sketchup fully accepting the file
as geo-located. This is not so.

**Comment by thomthom** [comment]
Thank you for the report. Could you attach a model showing this sympthom?

**Comment by jonnyns** [comment]
[georef.skp.zip](https://github.com/SketchUp/api-issue-tracker/files/1903081/georef.skp.zip)

This is an example of a generated file using the importer (before *forcing* geolocation using the dialog box).
A ruby test using model.georeferenced? claims false, of course. That is expected.
Shadow_info contents:
SomeCity
SomeCountry
20
312
false
false
true
true
false
false
60.671892470760724
80
16.738720662672264
0.0
2018-11-08 14:30:00 +0100
1541683800
(-0.454094, -0.875818, 0.163529)
2018-11-08 08:45:07 +0100
1541663107
2018-11-08 16:27:49 +0100
1541690869
1.0
false

**Comment by DanRathbun** [comment]
Related (rhetorical) questions ... 

The GUI seems to create or update the `"GeoReference"` attribute dictionary primarily for Google Earth. 

1. Does the C API also do this ?
2. Is this likely to become optional in the future ?

**Comment by thomthom** [comment]
Logged as SU-40201
