### ISSUE TITLE
Uncaught exception happened in SUModelCreateFromFileWithStatus 

### ISSUE THREAD

**Issue by GreatWhite2018** [SketchUp/api-issue-tracker#835]
Hi experts,
When I use API function SUModelCreateFromFileWithStatus to read several models, a SEH exception happened.
I think this issue can cause security risk.

The SketchUp SDK Version is 22.0.316
OS Platform: Windows 10 Enterprise
![image](https://user-images.githubusercontent.com/41320746/195795300-58da033a-2ddc-49f8-99c6-05a00f0fbf03.png)
The models are contaminated, what's the best way to share the model for you?

Thanks

**Comment by thomthom** [comment]
Can you send them to developer-support@sketchup.com please?

**Comment by GreatWhite2018** [comment]
Hi @thomthom, I find that the issue found by my colleague has not been solved. Could you triage that issue first please? I will send the contaminated models mentioned here later.
[https://github.com/SketchUp/api-issue-tracker/issues/773](url)

**Comment by thomthom** [comment]
We don't have any means to deliver fixes that quickly. I logged the issue before the weekend and it's being looked into.

**Comment by GreatWhite2018** [comment]
OK, I have sent the models. @thomthom

**Comment by thomthom** [comment]
@GreatWhite2018 - I didn't notice you referenced an older ticket at first. Is this issue the same as #773?

**Comment by zhuda** [comment]
Hi @thomthom, yes this tickect should be the same as #773. May I know that status of these two issues? We are waiting for the fix and SDK to consume. Do you have an ETA?

**Comment by DanRathbun** [comment]
REF Issue from #773 : Logged as: SKEXT-3399

**Comment by thomthom** [comment]
@zhuda - a patch should have been delivered to your company before the Christmas holidays. I can check who that contact was.

**Comment by zhuda** [comment]
@thomthom yes please check who the contact is.

**Comment by GreatWhite2018** [comment]
Thanks @thomthom , I have received the email

**Comment by zhuda** [comment]
@thomthom  just fyi, we get the patch build and it works well for all reported exception issues. so you may close this ticket as you wish. Thanks.
