### ISSUE TITLE
Can not change the style of leader line on Layout::LinearDimension by Ruby API

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/api-issue-tracker#836]
I can not  find  the function to change the style of leader line.

![image](https://user-images.githubusercontent.com/28385638/195802083-d55245a3-f405-40dd-bf13-a77bb1dfa1d8.png)

**Comment by thomthom** [comment]
@ackarkka - are we missing this?

**Comment by DanRathbun** [comment]
It looks like it is supposed to be this method:
* [`Layout::LinearDimension#leader_line_type=`](https://ruby.sketchup.com/Layout/LinearDimension.html#leader_line_type=-instance_method)

The leader line type can be one of the following:

```ruby
Layout::LinearDimension::LEADER_LINE_TYPE_SINGLE_SEGMENT
Layout::LinearDimension::LEADER_LINE_TYPE_TWO_SEGMENT
Layout::LinearDimension::LEADER_LINE_TYPE_BEZIER
Layout::LinearDimension::LEADER_LINE_TYPE_HIDDEN
```
#### Example:

```ruby
start_point = Geom::Point2d.new(1, 1)
end_point = Geom::Point2d.new(5, 5)
height = 1.0
dim = Layout::LinearDimension.new(start_point, end_point, height)
doc.add_entity(dim, layers.first, pages.first)
dim.leader_line_type = Layout::LinearDimension::LEADER_LINE_TYPE_BEZIER
```
