### ISSUE TITLE
Windows - HTMLDialogs - not child windows of SU

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#84]
Was writing some code to check the Oauth issue brought up in the forum, and I noticed (on Windows):

1. HTMLDialogs do not minimize when the SU window is minimized.

2. Each HTMLDialog creates another item on the taskbar.

Both of these issues should really be fixed.  IMHO, they will certainly slow adoption of HTMLDialog.

Greg

**Comment by Eneroth3** [comment]
I don't see this. For me HTMLDialogs are hidden when the main SU window is minimized and do not appear on the taskbar. Could the behavior you observe be related to your custom Ruby interpreter?

**Comment by MSP-Greg** [comment]
@Eneroth3

Thanks for checking and replying,  I copied some code from a forum post; it's due to the setting of the `style` init parameter.
```ruby
UI::HtmlDialog::STYLE_DIALOG    # as prev, child window
UI::HtmlDialog::STYLE_UTILITY   # not checked yet
UI::HtmlDialog::STYLE_WINDOW    # independent window
```

Greg
