### ISSUE TITLE
UI.add_context_menu_handler is executed when selecting object instead of right-click

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#848]
To create a selection context menu, we usually write the following

```ruby
UI.add_context_menu_handler do |menu|
  #create some menu item
end
```

What I discovered is that **the creation of the context menu is triggered whenever you _select_ an object** (i.e. the content of the block is executed when you select an object). I thought that the context menu would be created only when you right-click.

This is true for all versions of Sketchup.

You can reproduce the problem by a small ruby file containing:

```ruby
UI.add_context_menu_handler do |menu|
  puts "Context menu is calculated"
end
```

For me, **this is not efficient and may affect performance**, because many plugins may contribute to the selection contextual menu and may have to perform some calculation on the selection to adapt te menu items to be displayed.  Most users would select many times and right-click a few times.

**Comment by Eneroth3** [comment]
This is an interesting observation. My first thought was that a short delay would be more noticeable on right click than on selection, as you expect the context menu to appear instantly but aren't waiting for a reaction to selecting. Then I wondered if the view redraw showing the selection happens before or after the menu code is executed and if that might be a noticeable delay, and then it struck me that right click too changes the selection so there is no need to "pre-load" the menu before you right click.

Maybe this could be optimized in SketchUp so the menu code runs on right click alone.

That said, in the most typical use case (checking if the selection contains an object of a given class) the execution time should be close to nothing. Do you have a use case where there is noticeable delay in calculating the menu?
