### ISSUE TITLE
FrameChangeObserver#frameChange: argument from_page always nil

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#862]
I noticed that the first argument (`from_page`) of the callback method is always `nil`.

Not a big deal for what I use, but I wonder why?

**Comment by DanRathbun** [comment]
It is a known bug (on Windows platform) that has never been fixed, likely due to priority policy.

It and a workaround are explained in the documentation:
* [`Sketchup::FrameChangeObserver#frameChange`](https://ruby.sketchup.com/Sketchup/FrameChangeObserver.html#frameChange-instance_method)

But **after 15 years** we'd hope that these nagging bugs would percolate to the top and get some love !

**Comment by Fredosixx** [comment]
Maybe it was never fixed because it was not logged here, among the 572 other issues.

I am sure now that it will get attention...!

**Comment by DanRathbun** [comment]
> Maybe it was never fixed because it was not logged here, among the 572 other issues.

**Not true**. I myself logged this bug:

* [Issue 62- : **FrameChangeObserver does not pass a valid "from_scene" page parameter on PC (15 year+ bug)**](https://github.com/SketchUp/api-issue-tracker/issues/620) - MAR 2021

I myself have lost confidence that the many API bugs will be fixed given the backlog and empirical evidence.

Even so, in #244 I advocated ...
> I have come to the opinion that [**`FrameChangeObserver`**](https://ruby.sketchup.com/Sketchup/FrameChangeObserver.html) should be **twilighted and deprecated**. (Even so Issue #620 should be fixed, but no other features added.) The [`frameChange`](https://ruby.sketchup.com/Sketchup/FrameChangeObserver.html#frameChange-instance_method) functionality should be **correctly reimplemented** as part of the [**`PagesObserver`**](https://ruby.sketchup.com/Sketchup/PagesObserver.html) class.
>
> I'd rather that [Issue 237 : Add observer event to detect active scene change](https://github.com/SketchUp/api-issue-tracker/issues/237) be implemented for the [**`PagesObserver`**](https://ruby.sketchup.com/Sketchup/PagesObserver.html) class that would implement 2 callbacks, one for start transition and 1 for transition complete.

----

RELATED ISSUES:

* [Issue 244 : **Fire FrameChangeObserver at least twice for all scene changes**](https://github.com/SketchUp/api-issue-tracker/issues/244) - APR 2019

* [Issue 790 : **FrameChangeObserver#frameChange callback code example incorrect format string**](https://github.com/SketchUp/api-issue-tracker/issues/790) - JUN 2022

**Comment by DanRathbun** [comment]
@thomthom Why do we need this duplicate issue open ?
