### ISSUE TITLE
Clarify camera "2d mode"

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#87]
In the Ruby API documentation `center_2d`  and `#is_2d?` are described to be related to a camera "2d mode". 2d mode refers to 2 point perspective. I suggest writing 2 point perspective in the model description as it isn't any more "2D" than a one point perspective, and because the term 2d mode easily can be interpreted as meaning parallel projection.

**Comment by thomthom** [comment]
Logged as SU-40197

**Comment by DanRathbun** [comment]
Unfortunately the fix was done with incorrect grammar. Opened a new issue ...

[Issue 598 : **Sketchup::Camera#is_2d? method description grammar is incorrect**](https://github.com/SketchUp/api-issue-tracker/issues/598)
