### ISSUE TITLE
view.invalidate or adding Entities causes endless loop in Tool#draw on Mac

### ISSUE THREAD

**Issue by slbaumgartner** [SketchUp/api-issue-tracker#896]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version:
2. OS Platform:

Describe briefly what you are doing and what is happening.

Describe what the expected result is.

```ruby
# Complete reprodusible code snippet. (Important!)
```

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by slbaumgartner** [comment]
On Mac SketchUp 2023 running on macOS Ventura, anything that explicitly (e.g. calling view.invalidate) or implicitly (e.g. adding any Entity to an Entities collection) invalidates the view will cause an endless loop if it happens during a Tool's draw method.  This was discovered while investigating an issue report about TIG's 2DTools on the public SketchUp forum.

The issue does not happen on Windows.  It also does not happen in SketchUp 2022.  I don't have an earlier version of macOS, so I don't know whether Ventura is involved.  Also, I have only tested this on an Intel-based Mac, I don't know whether the Apple Silicon version of SketchUp is affected.

The sample code below demonstrates the issue.  If you load it as is, it will activate an instance of a very simple Tool that does essentially nothing.  If you uncomment either of the code statements in the Tool's draw method before loading, and then click the left mouse button it will immediately send SketchUp into an infinite loop on the draw method (verified via the Ruby debugger).

# investigate bug that causes endless loop if the view is invalidated
# from within a Tool's draw method on macOs SketchUp 2023
# (does not happen on Windows)

module SLBTests
  module Invalidate
    class Invalidate_tester

      def initialize
        @i = 0
      end

      def draw(view)
        # uncomment either of the following code lines to cause an endless
        # loop of draw on Mac SketchUp 2023!  SketchUp will have to
        # be force-quit to break the loop!

        # Explicitly request a redraw in the midst of a draw.
        # A bad idea in any case, but runs without an issue on Windows
        #view.invalidate

        # Adding Entities while inside draw implicitly tells SketchUp the
        # view is invalid (needs the new Entities drawn).
        #gp = Sketchup.active_model.active_entities.add_group() # adding any actual entity also causes implicit redraw
      end

      def onLButtonDown(flags, x, y, view)
        @i = @i + 1 # just to provide a target breakpoint
        view.invalidate() # left click to trigger a draw on the view
      end

    end
  end
end
invtest = SLBTests::Invalidate::Invalidate_tester.new
Sketchup.active_model.select_tool(invtest)

**Comment by DanRathbun** [comment]
Steve please cut and paste your report into the first post. This is where the bot will copy from.
(The form was supposed to help us write good reports but it seems it just confuses people.)

P.S. - GitHub uses markdown just like the forum.

**Comment by slbaumgartner** [comment]
It certainly confused me, and I’m still confused!  Where is the first post and from where do I cut and paste into it? I found that UX to be impenetrable.On May 2, 2023, at 6:02 PM, DanRathbun ***@***.***> wrote:﻿
Steve please cut and paste your report into the first post. This is where the bot will copy from.
(The form was supposed to help us write good reports but it seems it just confuses people.)
P.S. - GitHub uses markdown just like the forum.

**Comment by slbaumgartner** [comment]
As mentioned, both of these practices were present in TIG's 2DTools extension, which has been around a long time, still runs correctly in Windows, and used to run in old versions of Mac.  Something has changed in Mac SketchUp 2023 - a regression.  So either it should be fixed, or the API docs should make it very clear not to do that.

That said, I agree with both of your points.

- The only way calling view.invalidate within #draw could ever have worked is if the call was somehow ignored.  Because it triggers a redraw event, calling it from draw is an infinite recursion _unless_ the call is ignored.  But thinking you need to invalidate the same view as is currently being drawn is of itself illogical.
- TIG used creating temporary Entities in the draw method as a way to get the vertex locations to draw an  interactive "ghost" of the result while the user was in the process of creating an arc, circle, or polygon.  Evidently the current version on Mac interprets this as indicating that the view needs to be redrawn immediately to show the new geometry, again causing an infinite recursion (which is a separate issue from efficiency).  I have already modified the extension's draw code to calculate the required points without resorting to this trick and seen no issue with response.  The downside is that the ghost may now get clipped because the vertices are not known in time to add their positions in getExtents.  Avoiding this will require a significant rework of the flow of the extension.

**Comment by thomthom** [comment]
I see this on ARM mac in SU2023.0.

**Comment by thomthom** [comment]
Might relate to @460 ?
