### ISSUE TITLE
SUTextureWriteToFile() / SUTextureWriterWriteAllTextures() - data are always re-compressed after sdk2017M0 + can't control colorization of texture.

### ISSUE THREAD

**Issue by prachtan** [SketchUp/api-issue-tracker#9]
1). C API SU2017 and newer.
2). Windows.

During process of exporting all textures from model:

```
SUModelGetMaterials(modelRef, numMaterials, &materials[0], &numMaterials);

SUTextureRef textureRef = SU_INVALID;
SUMaterialGetTexture(materials[0], &textureRef);

// extension of file is same - no re-compression should happen
SUTextureWriteToFile(textureRef, path_to_file.c_str()); 
```
And now, if type of the material is:
- `SUMaterialType::SUMaterialType_Textured`
SUTextureWriteToFile() - just write a file,

but if material was type of:
- `SUMaterialType::SUMaterialType_ColorizedTexture`
SUTextureWriteToFile() - unnecessary colorize the image and re-compress the file
_(it could take more than 10 times longer)_

In compare to RubyAPI there is parameter which allows to control this:

`material.texture.write(filename, colorize = false)`

**Comment by thomthom** [comment]
As of SU2018 you can get the original texture data from `SUTextureGetImageRep` - where you then can use `SUImageRepSaveToFile`. You also have `SUTextureGetColorizedImageRep` if you need.

Maybe we can add a note to the documentation for `SUTextureWriteToFile` that `SUImageRef` can be used to obtain the original pixel data.

**Comment by prachtan** [comment]
@thomthom 
I know that, but SUImageRepSaveToFile will save original image data (no re-compression)?

The performance is important for me, in case of huge textures (2048x2048) re-compressing a few png files (to preserve transparency) may take a really long time...

**Comment by thomthom** [comment]
What do you mean by re-compressing?

**Comment by prachtan** [comment]
It's look like texture images in skp file are held as a jpg or png.
We need to get all images _(as fast as is possible)_ from skp file during of process of importing model to be able to use it on our side.

As mentioned here - compressed texture data may be accessible untouched by SU:
https://forums.sketchup.com/t/getting-compressed-texture-data/26236/2

The coloring process must un-compress the file, apply the color, and then compress it again during the save process. Probably it's look same in case of using ImageRep.

We would like to just copy out compressed data from skp. 
We aiming to import huge files with big textures.

Any process of reading, un-compressing, by Sketchup / CAPI to convert it to get raw pixel-bytes, to be able to put it to ImageRep and then compressing it again _(in case of png it can even take 20 second per file)_ to get almost same files like this ones which was stored in skp is pointless ...

**Comment by thomthom** [comment]
So this is a request for a faster way to access texture data. Can you create an example that demonstrate the performance issues of existing API functionality - something we can use for comparison?

**Comment by prachtan** [comment]
IMHO it is more of an issue than an enhancement, I did a few tests and I think that even if the material is not colorized, SUTextureWriteToFile always re-compresses the data. 

I don't know how to achieve this:
https://forums.sketchup.com/t/getting-compressed-texture-data/26236/2

Maybe when You add ImageRep you changed something in SUTextureWriteToFile behaviour
_(kind of internal "cached flag" for compressed data)_.

**Comment by BugraBarin** [comment]
SketchUp itself stores textures in memory as regular uncompressed bitmap data. So they cannot be returned as compressed data without recompressing them. Compression only occurs when saving to a file, and only if you are saving to a compressed image format like jpg. If you want the uncompressed data, you can either just get the data through the API or save to a .bmp file.

If you call SUTextureWriteToFile() and give it a .jpg or .png extension, the data will have to be compressed, because those are compressed formats. SketchUp doesn't hold on the the compressed data in-memory.

**Comment by prachtan** [comment]
@BugraBarin 
We (I and @thomthom ) discuss this problem, and it's look like you changed something between sdk-2017-m0 and newer, this is a test project which can reproduce the issue: https://www.dropbox.com/s/uqyoh705meg7xeh/TextureWriterIssue.zip?dl=0

SUTextureWriteToFile() from version m0 will save in 8 ms, but same code compiled against any newer version will take 30 seconds(!).

Saving from RubyAPI is also very fast:
Sketchup.active_model.materials[0].texture.write(<file_name_with_proper_extension>)

**Comment by BugraBarin** [comment]
Thanks for the test project, very helpful. I don't know what caused this regression but we'll take a look.

**Comment by prachtan** [comment]
@BugraBarin nice to hear this.

Ok, I try to summarize the issue, and explain why I think this is serious problem.
_Now, after some tests I see it clearly, before that I was not sure where exactly the problem was._

The issue is: `SUTextureWriteToFile() / SUTextureWriterWriteAllTextures()` after sdk-2017-M0 always re-compress the data.

Why imho it's serious - issue case:

Let's suppose that we have our standalone skp file importer. 
We need to read all geometries and textures from skp file - for example we are renderer.
All textureas are stored in skp file as JPG/PNG _(it's easy to find JFIF / PNG magics inside of skp file binary)_ We just read/copy-out untouched pngs/jpgs from skp to our external cache to be able to use it, this was very fast, 8-10 ms / per file.

We support skp-2017 file format, based on sdk-2017-M0, there was no major changes between M0 and M1/M2, we didn't recompile against any of them. Now we need to recompile our plugin against sdk-2018 to be able to read new skp-2018 file version.

Our customer has skp-2017 file, with 20 huge png-textures. He used our old skp sdk-2017-M0 plugin.
Reading pngs took: 20 x 10 [ms/png] = **200 ms** in all. 
Now our customer just re-save file from version skp-2017 to skp-2018. We need to use sdk-2018 to be able to read exactly same file _(but in newer version)_.
Reading pngs will take: 20 x 30 [seconds/png] = **600 seconds** in all - this is **10 minutes(!)**

@thomthom found little improvement for this, using `SUTextureGetImageRep() +  SUImageRepSaveToFile()` decrases saving/compressing time from 30 seconds/png in case of `SUTextureWriteToFile()` to 3.5 seconds / png in case of `SUImageRepSaveToFile()` _(parallel compression? different png compression algorithm?)_ but from our perspective it's still unacceptable: 20 png x 3.5 seconds/png = 1 minute 10 seconds (!) with a comparison to 200 ms in version M0

Do I need to put this to centercode beta issue tracker or here is enough?

**Comment by thomthom** [comment]
Just to get all the data logged, I set up a test yesterday with one of @prachtan's test models. It contained four textured materials. 4096x4096.

I looped over all materials and used `SUTextureWriteToFile`. Then afterwards I made some tests with `SUImageRepSaveToFile` just to compare. Some interesting numbers.

```
SU2017 (SDK_Win_x64_18-0-15444)

Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 47661 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 10691 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 36816 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 351 milliseconds
Press any key to continue . . .


SU2017 (SDK_Win_17-0-18899_0)

Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 49649 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 10945 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 8 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 9 milliseconds
Press any key to continue . . .


SU2018

Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 48745 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 10647 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 35101 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 358 milliseconds
Press any key to continue . . .


SU2018 SUTextureGetImageRep

Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 3400 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 665 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 3296 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 616 milliseconds
Press any key to continue . . .


SU2018 SUTextureGetColorizedImageRep

Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 7504 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 6130 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 5650 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 722 milliseconds
Press any key to continue . . .
```

**Comment by prachtan** [comment]
One small comment to the above numbers _(this may not be clearly shown above)_ : _Materials 01_ and _02_ are **colorized**, higher time of saving the file is explainable because image need to be: uncompressed + colorized + compressed again. But materials _03_ and _04_ wasn't colorized - it should be just copy-out from skp file - the issue is clearly visible on _Material 03_ on different sdk.

**Comment by thomthom** [comment]
Logged as SU-38309

**Comment by thomthom** [comment]
@prachtan - what is ideal output for you guys? Do you prefer the original texture data without colorization in all cases? So you can apply the colorization yourselves?

**Comment by zsacul** [comment]
> Do you prefer the original texture data without colorization in all cases? So you can apply the colorization yourselves?

That would be best for me...

**Comment by prachtan** [comment]
> @prachtan - what is ideal output for you guys? Do you prefer the original texture data without colorization in all cases? So you can apply the colorization yourselves?

@thomthom: What exactly is stored in the Skp file? Once I was scanning the SKP file looking for PNG magic. I think I found a picture without colorization. As I recall, skp2017M0 also exports _(original)_ image without coloring. So I think that the original texture file data would be best for us too...

I apologize for the late answer, I missed the notification ...

**Comment by thomthom** [comment]
Collecting information from another thread:

> Thomthom, yes, but as you remember, we're talking about an external/standalone CAPI for our importer, there is no Ruby in this context. From our point of view the main problem is the performance of re-compressing texture images, as I see (on SU2018), material.texture.write() can save a huge png file without any performance bottlenecks.
> 
> Update:
> After manual extraction PNG from SKP (by copy out the PNG bytes from skp), it looks like Ruby "material.texture.write()" saves raw and original data that are kept in skp file (same CRC) without any re-compression. It looks like the same mechanizm is used by SU (same CRC) when the "Edit texture in external editor" button has been clicked.

> I wonder if this wouldn't be the easiest way to add two additional functions to the API:
> 
> SUTextureGetFileSize() - get size of the raw image file (JPG/PNG/BMP/GIF stored in skp) 
> SUTextureGetFileBytes() - get the raw image file bytes,

**Comment by jinyistyle** [comment]
@prachtan,
My name is Jin Yi. I work on the extensibility team as a Software Engineer.
On my machine, I'm getting to work on this issue. On my machine with 2018/2019 SDK, I am getting around ~36000ms for writing the first texture that you provided long time ago. It's like a 4096x4096 image.

Currently I have the timing down to ~600ms on my machine, is this decent enough?

**Comment by prachtan** [comment]
Hey @jinyistyle 

Saving the colorized texture to PNG _(with full re-compression)_ at ~600 ms sounds very good.

Saving a non-colorized texture should take about ~8-10 ms per file.
_(the SKP file contains compressed PNG/JPG bytes inside, so it should only write untouched bytes to the file without any processing)_

Above test results for SDK2017
> SU2017 (SDK_Win_17-0-18899_0)
> 
> Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
> 01 - PNG textured  took 49649 milliseconds

If we're now ~ 600 ms, it will be awesome.

> Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
> 02 - JPG textured  took 10945 milliseconds

> Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
> 03 - PNG textured - no-color for CAPI  took 8 milliseconds
> Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
> 04 - JPG textured - no-color for CAPI  took 9 milliseconds
> Press any key to continue . . .

For non-colorized data, untouched bytes are exported - so it's only disk write time.

**Comment by thomthom** [comment]
@prachtan  - are you also looking for a way to save out textures from materials without colorization, even if the material is colorized?

**Comment by prachtan** [comment]
It would be great if it could behave in the same way as RubyAPI `Texture#write(filename, colorize = false) ⇒ Boolean` but it probably breaks current CAPI.

From our point of view, the most important thing is to get the image bytes as fast as is possible - hence this suggestion to add:

> SUTextureGetFileSize() - get size of the raw image file (JPG/PNG/BMP/GIF stored in skp)
> SUTextureGetFileBytes() - get the raw image file bytes,

In conclusion, yes we would like to get raw image _(without colorization)_. Colorization can be easily reproduced on our side and the customer will get an untouched image _(without colorization)_ for other effects.

**Comment by thomthom** [comment]
@prachtan - in your workflow, is there any technical preference/need to be using `SUTextureWriteToFile` vs `SUTextureWriterWriteAllTextures` vs `SUImageRepSaveToFile`? Or is it entirely based on what is fastest?

**Comment by prachtan** [comment]
The preferred way is `SUTextureWriteToFile` we just get the `SUTextureRef `and write the file. 

`SUImageRepSaveToFile` is acceptable, but does ImageRep have access to raw bytes of the source image? I thought it had only uncompressed pixel buffer under the hood and it requires re-compression on write.

`SUTextureWriterWriteAllTextures` looks archaic. We have no control over the names of exported texture files, and as far as I know, it can't load textures from `SUMaterialRef`

**Comment by thomthom** [comment]
Taking a step back and trying to look at the whole workflow. Including the conversation in #66

To quickly and easily obtain all materials (thus textures) in a model we could use:

* `SUModelGetNumAllMaterials` (new)
* `SUModelGetAllMaterials` (new)

Then, to write the textures out the API user could use:

* `SUTextureWriteToFile`
* `SUTextureWriteRawToFile` (new)

The former would write out the colorized texture (as it currently does), and then we could have a new function to save out the raw image data without colorization. I guess this should be the easiest and most flexible way for render engines and exporters to dump the texture data to disk.

---

We then have the ImageRep functions for getting an in-memory representation of the textures:

* `SUTextureGetImageRep`
* `SUTextureGetColorizedImageRep`
* `SUImageRepSaveToFile`

I'm not sure how relevant these are for the workflow of render engines and exporters in terms of getting textures out fast. I guess in that context the main need is to get a file on disk?

I need to look closer at `ImageRep`, I'm not sure if this object carry the original image fileformat data with it - might just be uncompressed pixel data. In which case it would always require re-encoding when writing to disk.

---

* `SUTextureWriterWriteAllTextures`
* `SUTextureWriterWriteTexture`

These are being used by some exporters/render engines to deal with the projected textures that SketchUp supports. Some engines need to convert these into un-projected textures. In this case I'm not clear whether there is a need to have control over saving out colorized or not. But in the cases where the texture saved is not modified in any way we should make sure it dumps the raw original image data.

---

In all of the above, it also sounds like there would be useful to have control over the format and quality of the texture if it's colorized and needs to be re-encoded. So maybe new functions is needed for that.

**Comment by prachtan** [comment]
Sound great!

If you are working on this, you may also consider adding:

> SUTextureGetRawFileSize() - get size of the raw image file (JPG/PNG/BMP/GIF stored in skp)
> SUTextureGetRawFileBytes() - get the raw image file bytes,

Other applications may want to get the original PNG/JPG data as memory buffers and save them _(embed them)_ directly in a single continuous library/_(project)_ file, just like SU does in SKP. 

We could skip the unnecessary saving / reading of file content to disk.

**Comment by thomthom** [comment]
Thanks for the input.

So I take it that for you - developer for a render engine that tries to consume the model as fast as possible, iterating all materials and being able to write out the raw original un-colorized texture is the ideal path?

`SUImageRep` and `SUTextureWriter` isn't something you deal with?

**Comment by thomthom** [comment]
Hey @prachtan - can you test on your machine again with the textures.skp example you had. Back in 2017 when I made my initial timing I saw 8-10ms for dumping the non-colorized materials. (https://github.com/SketchUp/api-issue-tracker/issues/9#issuecomment-342416080)

But today, it consistently takes twice that with the same SDK version:

```
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
01 - PNG textured  took 109687 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
02 - JPG textured  took 25062 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 24 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 32 milliseconds
```

I'm not sure what causing this. Different HD with different write speed? (I have an SSD now, I think I had one then. Are there big difference in SSD speeds?)

Or maybe compiler difference? The SDK is still the SU2017M0 binaries.

---

Another thing I noticed. If I skipped the colorized textures my timings for 03 and 04 was different:

```
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 719 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 337 milliseconds
```

I then made another test where I wrote out 03 and 04 five times in a loop:

```
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 739 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 356 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 16 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 20 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 16 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 21 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 17 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 20 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 16 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 28 milliseconds
```

It looks like there is some lazy initialisation going on. So timings for the first write (of each file format) has an extra overhead.

**Comment by thomthom** [comment]
I just disabled Dropbox (my project was stored there), CrashPlan (my backup software) and Window Defender:

```
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 719 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 331 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 14 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 12 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 14 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 11 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 13 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 10 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 13 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 10 milliseconds
```

Times are back to "normal".

**Comment by thomthom** [comment]
With Defender re-enabled:

```
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 716 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 333 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 13 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 18 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 15 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 18 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 14 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 18 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\png_texture.png
03 - PNG textured - no-color for CAPI  took 15 milliseconds
Writing texture: C:\Users\Thomas\SourceTree\SLAPI-Tests\temp\jpg_texture.jpg
04 - JPG textured - no-color for CAPI  took 18 milliseconds
```

It appear to be the main culprit for the abnormality I saw.

Note to self, disable all you can when doing performance test.

**Comment by thomthom** [comment]
Hey @prachtan - how are you obtaining the colorization type for materials? Do you use Ruby to obtain that?

**Comment by prachtan** [comment]
Hey @thomthom we have two different products: 

- classic importer based on C SDK _(when the customer would like to import skp file)_,
- the SketchUp LiveSync plugin based on C and Ruby,

So, we use different approaches when we need it.

You're right, there's no CAPI to get the colorization type - no equivalent for Ruby's `Material::#colorize_type`.  
_(I think, that there is an issue for this - If I well remember, created by Dan)_

It's possible to get the material type: `SUMaterialGetType()` but when the material is `SUMaterialType::SUMaterialType_ColorizedTexture` we can't get colorization type _(in this case, we use Ruby in our plugin)_

There is also no equivalent in CAPI for Ruby's `Material::#colorize_deltas`, so you may also fill the gap if you are working now on SDK improvements. But as far as I remember, you published an example in C how to reproduce the colorization, so I'm not sure if the `colorize_deltas` are required in C.

Regarding your previous question:

We use `SUImageRep` in our LiveSync plugin _(we don't need to save images on disk when scenes are synchronized in real time)_ and at this moment `SUImageRep` works well for us.

In the previous version of our importer we used `SUTextureWriter` for textures with perspective correction.
But now we've dropped the support for this kind of textures, because sometimes it generates thousands of tiny textures, and this negatively impacts the performance of our renderer.

**Comment by thomthom** [comment]
@prachtan Thank you very much for this insight. I took another step back and compared the API features between the Ruby and C API. I didn't find an issue in the GitHub tracker about the `colorize_type`, butI recalled talking about it. And I included it into a document where I try to outline the current limitations and issues regarding working with materials and textures in our APIs.

I might in fact share that with you at some point to get your input on this.

Regarding the texture writer - yes it will generate new textures when there is non-affine UV mapping applied to the face. The whole purpose for that class was to provide compatibility with external consumers that didn't support non-affine UV mapping. Though the expense of that you end up with a lot of unique textures.

You say you don't support them - do you simply skip them? I've seen some exporters, render engines convert the UVQ values to UV - and accepting that there might be some visual deviance. In many cases it's not particularly noticeable.

**Comment by prachtan** [comment]
> You say you don't support them - do you simply skip them? I've seen some exporters, render engines convert the UVQ values to UV - and accepting that there might be some visual deviance. In many cases it's not particularly noticeable.

Exactly, sometimes we end up with thousands of tiny textures - a single unique texture for almost every face. So, we decided to skip support for this and we use UV computed from UVQ _(honestly, based on your post about this conversion, somewhere in the forum)_ :)

At the moment, we didn't hear that the small visual deviance for this case it was a big problem for our clients, but maybe someday we'll add support for UVQ.

Perhaps if you are working on a materials system, you can also add the option to get the `SUImageRep` from the face with a new image with perspective correction applied _(exactly the same as` SUTextureWriter`, but with a memory bitmap instead of a disk file)_. Based on memory bitmaps, we can build texture atlas in the fly, to reduce the number of small images and achieve better rendering performance _(less context switching)_.

About `colorize_type`, maybe it was a discussion on SU forum, after fast search I found this:
https://forums.sketchup.com/t/how-does-colorised-texture-work/51168

**Comment by thomthom** [comment]
> Perhaps if you are working on a materials system, you can also add the option to get the `SUImageRep` from the face with a new image with perspective correction applied _(exactly the same as` SUTextureWriter`, but with a memory bitmap instead of a disk file)_. Based on memory bitmaps, we can build texture atlas in the fly, to reduce the number of small images and achieve better rendering performance _(less context switching)_.

We could look into adding `ImageRep` to be an alternative output to `TextureWriter`. I think there's a few other places where the API writes images to disk (`view.write_image`) where we could offer an `ImageRep`.

**Comment by jinyistyle** [comment]
Hey @prachtan,

We were able to speed up the texture write tremendously by magnitudes (30x or so on my machine). So you should notice a difference. However, this doesn't affect writing out colorized textures since those get re-compressed.

**Comment by prachtan** [comment]
Hey @jinyistyle That's a great news!
So... where can I get the newest SDK? :)
_Are you planning any alpha/beta releases for codecenter?_

**Comment by DanRathbun** [comment]
This is a public site, @prachtan. Please review any NDAs and follow restrictions for non-public programs.
