### ISSUE TITLE
Tool double-click and modal HtmlDialog: focus lost in translation

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#903]
I was finally able to identify a major issue with a **complete loss of focus when you call a modal HtmlDialog from the DoubleClick event of an interactive tool**. This is for me a **critical bug**, for which there is no workaround.

Here is the code
```ruby
def test_modal_tool
  Sketchup.active_model.select_tool MyTool.new
end

class MyTool

def onLButtonDoubleClick(flags, x, y, view)
  UI::HtmlDialog.new.show_modal
end

end	#class MyTool
```

When you execute the method `test_modal_tool`, you start the interactive tool. Then, just double click to launch the modal Html Dialog. The dialog displays. Then what happens is the folowing:

- **the mouse focus is completley messed up**. clicking anywhere in the dialog box, including on its close button, has no effect. Clicking anywhere in the Sketchup Window has no effect too.
- The only way to restore a normal situation is to switch to another application and then go back to Sketchup.

The problem happens on **SU2023.0.419 on Windows**.

I also tested that **this is specific to the _Double-click_ event**. A simple click would not provoke the issue

**Comment by DanRathbun** [comment]
Clicking on the modal dialog caption bar and attempting to drag it causes the model to Pan.

----

I thought I had reported serious issues with modal dialogs previously. Such as being able to switch the focus to non-modal windows like Model Info or the Ruby Console.

**Comment by Fredosixx** [comment]
...and this does not happen in SU2022....
