### ISSUE TITLE
Visibility of text drawn using an Overlay

### ISSUE THREAD

**Issue by slbaumgartner** [SketchUp/api-issue-tracker#905]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version:
2. OS Platform:

Describe briefly what you are doing and what is happening.

Describe what the expected result is.

```ruby
# Complete reprodusible code snippet. (Important!)
```

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by DanRathbun** [comment]
What is the report? (I only see the issue template.)

**Comment by slbaumgartner** [comment]
I opened this and then saw the template says this repository is for issues only, not feature requests.  So I signed off without entering anything and put a FR on the public forum instead.  I thought that it would automatically be deleted since I typed nothing.  But obviously not…

**Comment by DanRathbun** [comment]
No, it is **also** for Feature Requests, the 3rd line says "_Bugs or **feature requests** that do not relate to the APIs will be removed._"

See the last section of the template/instructions (above). ThomThom will label such as "enhancement" with other categorical labels, such as "ui".

**Comment by DanRathbun** [comment]
**BUMP** Either close this or edit the original post and add the API feature request.
The public forum is not likely to get any traction. This is the place to file FRs.
