### ISSUE TITLE
Trouble with C API InstancePath

### ISSUE THREAD

**Issue by TommyKaneko** [SketchUp/api-issue-tracker#91]
In the making of my C++ wrapper for the C API, I have been running into issues with InstancePathRef objects.  I am having particular issues with getting `SUInstancePathGetInstanceAtDepth` to work.

This is my code in context:
https://github.com/TommyKaneko/Sketchup-API-C-Wrapper/blob/master/src/SUAPI-CppWrapper/model/InstancePath.cpp#L155

```
ComponentInstance InstancePath::instance_at_depth(size_t depth) {
  SUComponentInstanceRef instance = SU_INVALID;
  SUResult res = SUInstancePathGetInstanceAtDepth(m_instance_path, depth, &instance);
  assert(res == SU_ERROR_NONE); _unused(res);
  return ComponentInstance(instance);
}
```

The instance returned by SUInstancePathGetInstanceAtDepth always seems to be a NULL ptr.  Added to that that, the SUResult returned in this case is SU_ERROR_NONE, and does not complain with SU_ERROR_NULL_POINTER_OUTPUT , as one might expect.  I have checked that the SUInstancePathRef is valid prior to calling this method.

In my case, I create the InstancePath object using the SUModelGetInstancePathByPid method, so the issue may be hidden in there.

Any ideas about the issue?  Is there a bug?

Thinking aloud, I notice that the SUComponentInstanceRef object passed to SUInstancePathGetInstanceAtDepth must always be NULL, as there is no SUComponentInstnaceCreate() method available in the API.

**Comment by TommyKaneko** [comment]
I may have found a solution.

Is it the case that SUInstancePathGetInstanceAtDepth accepts depths starting at `0`, much like a zero-indexed array?  I have managed to get a proper ComponentInstance through using the zero index.

Having said that I am still have issues using the object returned with the above approach - I can't get the ComponentDefinition of the instance through SUComponentInstanceGetDefinition (even though the object appears to be valid).

**Comment by thomthom** [comment]
Yes, the index is zero based, like most things. It's the same for the size of `std::vector` and accessing by index. The size is always one more than the max index.

**Comment by DanRathbun** [comment]
The docs generally assume zero base. But will note otherwise. The PolygonMesh class is an example where they explicitly note the indices start at 1.
