### ISSUE TITLE
Exported thumbnail doesn't display the same material as the model

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/api-issue-tracker#922]
1. SketchUp Version: 2023
2. OS Platform: Windows 11

There is a difference between the thumbnail and the actual model.

[1.skp](https://drive.google.com/file/d/1dloBw5KOpmKYIMtvVktE_bhS_pi5lRmp/view?usp=sharing)

```ruby
Sketchup.active_model.selection[0].definition.thumbnail_camera = Sketchup.active_model.active_view.camera
Sketchup.active_model.selection[0].definition.save_thumbnail File.join('E:', "1.jpg")
```
![image](https://github.com/SketchUp/api-issue-tracker/assets/28385638/b53bd150-1af6-4db7-a600-b9764178350d)
![image](https://github.com/SketchUp/api-issue-tracker/assets/28385638/4d5f8034-8775-4305-8cec-ee98dea1897c)

**Comment by thomthom** [comment]
I think that has been by design in the thumbnail logic. It prunes out the background color.

**Comment by thomthom** [comment]
Or are you talking about something else? Can you add some specifics to what is expected behaviour?

**Comment by LItterBoy-GB** [comment]
> Or are you talking about something else? Can you add some specifics to what is expected behaviour?

The export preview of the model in black has turned to white

**Comment by thomthom** [comment]
Oh, the material of the model. Hm.. didn't notice that. Interesting.

**Comment by ChrisFullmer** [comment]
Looking at this issue, it appears that the component thumbnail was created before the dark material was applied. Now the thumbnail is cached in the model without the dark material. You can use definition.refresh_thumbnail to update the cached thumbnail. Then write out the thumbnail and it will show the dark material.
