### ISSUE TITLE
SUComponentInstanceFromEntity returns NULL if underlying entity is a Group

### ISSUE THREAD

**Issue by TommyKaneko** [SketchUp/api-issue-tracker#93]
You can cast between SUComponentInstanceRef and SUGroupRef (if the entity is a group), however, if you try to cast from SUEntityRef to SUComponentInstanceRef if the entity is a Group, then an invalid NULL object is returned.

I don't think this is intended, as a Group is a sub class of ComponentInstance (in C++ terms, or can be cast, in C lingo).

```
SUEntityRef group_entity; // a group entity
SUComponentInstanceRef instance = SUComponentInstanceFromEntity(group_entity);
if (SUEntityType(group_entity) == SURefType_Group) {
  // instance.ptr == NULL;
}
```

**Comment by thomthom** [comment]
Logged as SU-40192
