### ISSUE TITLE
Need help : Code to reload mutiple component in Sketchup

### ISSUE THREAD

**Issue by Quocanhelnino** [SketchUp/api-issue-tracker#934]
Hello, can anyone help me resolve this isssue :
- I have many simple component in with name : com1, com2, com3...in a file original.
- I have save all component to file com1.skp, com2.skp, com3.skp... in folder A
- Then i edit file component com1.skp, com2.skp, com3.skp....in folder A, Now i want to reload all component from folder A (have edited) to file original.
- It's same action with reload component in sketchup but with mutiple block in one time.
Thanks for any help guy!

**Comment by thomthom** [comment]
For help on usage of the API please use the developer section of the forums: https://forums.sketchup.com/c/developers/12
