### ISSUE TITLE
Model#delete_attribute: Is it supported? Does it work?

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#935]
The method `Model#delete_attribute(dict, key)` seems to be defined, BUT it is **not mentioned explicitely in the API documentation**.

And, ANYWAY, **it does not work**: it does not remove the attribute....

We need clarification...

**Comment by thomthom** [comment]
It's not part of the API no. It's one of the many unfortunate monkey patches Dynamic Component is doing.
