### ISSUE TITLE
Intel Threading Building Blocks Library - multiple versions & copies

### ISSUE THREAD

**Issue by MSP-Greg** [SketchUp/api-issue-tracker#968]
Searching the main SU App directory and the 'shipped' plugins' folders, there seem to be multiple copies and versions of dll's that are part of the 'Intel Threading Building Blocks Library'.

Is this intentional?

See forum post https://forums.sketchup.com/t/update-c-plugin-to-2024-issue/271791/23

Just checked on Windows...

**Comment by thomthom** [comment]
In the "shipped extensions" folder?

Do you have path and names for these files?

**Comment by MSP-Greg** [comment]
Versions of the tbb.dll file:

2020.3.2020.622 Scan Essentials
2017.0.2018.910 SketchUp

**Comment by thomthom** [comment]
Looks like  Scan Essentials and SU use each their own version. SE is using it's own copy as it cannot rely on SU's DLLs.
