### ISSUE TITLE
How to assign a texture material to SUComponentDefinitionRef  with SUDrawingElementSetMaterial？

### ISSUE THREAD

**Issue by yuanningcz** [SketchUp/api-issue-tracker#973]
I am using SkecthUp-2022 C api for development work under the Windows 10 platform。Here's what I want to do：

Place the side of a cylinder under the SUComponentDefinitionRef. Then assign the texture material to SUComponentDefinitionRef instead of the cylinder.

A serious error occurred in the texture material of the cylinder, as shown in the picture:
![error](https://github.com/SketchUp/api-issue-tracker/assets/18526951/f77e12d2-0846-4326-ad81-cdf303661c83)

The texture material picture is this:
![Antique Brick](https://github.com/SketchUp/api-issue-tracker/assets/18526951/11e3176a-a928-4c06-b710-a7417f1f00d0)

I can't upload the skp file where the error occurred。

Below is my code：

**1. Create the sides of the cylinder**

    SUGeometryInputRef geomInput = SU_INVALID;
    SU_CALL(SUGeometryInputCreate(&geomInput));

    size_t verCount = 0;
    for (...) 
    {
		SUPoint3D pt = PointFromVertex(*it, dSacle); 
		SU_CALL(SUGeometryInputAddVertex(geom_input, &pt));
    }
	
	 for (size_t nIndex = 0; nIndex < face_info.nTrangles; nIndex++) 
	 {
        SULoopInputRef loop_input = SU_INVALID;
        SU_CALL(SULoopInputCreate(&loop_input));
        SU_CALL(SULoopInputAddVertexIndex(loop_input, face_info.verIndexs_[nIndex * 3] + global_vertex_count));
        SU_CALL(SULoopInputAddVertexIndex(loop_input, face_info.verIndexs_[nIndex * 3 + 1] + global_vertex_count));
        SU_CALL(SULoopInputAddVertexIndex(loop_input, face_info.verIndexs_[nIndex * 3 + 2] + global_vertex_count));
        SU_CALL(SULoopInputEdgeSetSoft(loop_input, 0, true));
        SU_CALL(SULoopInputEdgeSetSoft(loop_input, 1, true));
        SU_CALL(SULoopInputEdgeSetSoft(loop_input, 2, true));

        size_t added_face_index;
        SU_CALL(SUGeometryInputAddFace(geom_input, &loop_input, &added_face_index));

        bool bSense = face_info.sense;
        SU_CALL(SUGeometryInputFaceSetReverse(geom_input, added_face_index, bSense));
	 }

**2. Place the cylinder under the SUComponentDefinitionRef** 

	SSUEntitiesRef parentEnt; //this is the SUComponentDefinitionRef object
	SUEntitiesFill(parentEnt, geomInput, true) == SU_ERROR_NONE;

**3、Assign texture material to SUComponentDefinitionRef** 

    SUMaterialRef material = SU_INVALID;
	SUMaterialCreate(&material);
	SUMaterialSetName(material, matInfos.m_strMatName.c_str());
	SUMaterialSetColor(material, &matInfos.m_color));
	SUMaterialSetUseOpacity(material, matInfos.m_bHasAlpha);
	SUMaterialSetOpacity(material, matInfos.m_fAlpha);

	std::string texture_file = matInfos.m_strTexPath;
	SUTextureRef texture = SU_INVALID;
	if (SUTextureCreateFromFile(&texture, "Antique Brick.png", 39.37, 39.37) ==
		SU_ERROR_NONE) 
	{
		SU_CALL(SUMaterialSetTexture(material, texture));
	}

    SUDrawingElementSetMaterial(SUComponentDefinitionToDrawingElement(pSuComponent), suMatNew);

	How to assign a texture material to SUComponentDefinitionRef or SUGroupRef to avoid material deformation on the surface.

**Comment by thomthom** [comment]
`SUComponentDefinitionRef` is not a `SUDrawingElementRef`. It is never directly placed in the model.

What you want to do is place an instance `SUComponentInstanceRef` of the definition and assign a material to that.
