### ISSUE TITLE
Cannot attach a rb file to this GitHub API Tracker

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#976]
Apparently, the **extension .rb is not allowed for file attachment**...

...which is somehow ironic for a Ruby API issue tracker!

**Comment by MSP-Greg** [comment]
For GitHub, that's normal.  Try using a `<file_name>.rb.txt` extension.

I suspect it's due to a need for filtering, and once one allows files beyond a select few extensions, they'd always be dealing with requests for additional 'allowed' extensions.  Also, remember that *nix systems have 'shebang' lines...

**Comment by Fredosixx** [comment]
I would have thought that it is the administrator (here Sketchup) who enables or disables allowed extensions.

For a site dedicated to Ruby, it would make sense to eanble attachment of rb files.

**Comment by MSP-Greg** [comment]
I believe admins don't have control of allowed extensions.

**Comment by Fredosixx** [comment]
Whatever the reason and responsible, it is really a silly situation that a discussion forum about a language cannot accept files of this language....!

**Comment by MSP-Greg** [comment]
The rules are set by GitHub.  As mentioned, a ruby file may be an 'executable' file depending on the system OS/platform/configuration.

There are a lot of people on GitHub that are very new at coding, and many may not realize that 'script' files may be 'executable'.  

Script files can be malicious, and people could accidentally run them.

**Comment by Fredosixx** [comment]
Ok. But if it is enough to add a .txt extension to overcome the limitation, I question the security argument....!

**Comment by thomthom** [comment]
As Greg mentions, this is something GitHub control and there is no admin control for org or repo owners to adjust this.

Gist is also an option to share file(s) if needed.

I'm closing this as we cannot take any actions on this.
