### ISSUE TITLE
How to check what version SketchUp's CEF is ?

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/api-issue-tracker#98]
How do we check what version SketchUp's CEF is ?

Can it be exposed as a [**`UI::HtmlDialog`**](http://ruby.sketchup.com/UI/HtmlDialog.html) class method ?

----

**ADD**: (_a proposed example class method returning a Hash object, from [comment below](https://github.com/SketchUp/api-issue-tracker/issues/98#issuecomment-397460980)_) ...
```ruby
UI::HtmlDialog::chrome_versioning
#=>
{ "CEF" => "3.2743.1422.g976502e",
  "Chromium" => "52.0.2743.24",
  "WebKit" => "537.36",
  "JavaScript" => "5.2.361.13"
}
```

**Comment by thomthom** [comment]
I'm not sure, maybe via the userAgent string from within JS?
Why do you want to access this from Ruby?

**Comment by DanRathbun** [comment]
What the version is was prompted by a related question in the public forum.
And I told the OP that he'd need to check whether his version of Chrome (or browser) supported a certain feature. (I don't remember yet, having not finshed my coffee, and working til after midnight last.)

I'll add the reason later when I remember it.

But basically, it is going to be just like the situation with loading component files that causes BugSplat when they are newer than the present client. It helps to know what the version is ahead of time, before the attempt to load it.

So, if we can ask the `UI::HtmlDialog` class what it's version of CEF is, we can adapt our code's behavior if we need to. We may need to do this before opening a dialog and loading a page (because say that the page is dynamically generated.) If you guys are modifying the user agent string within CEF then is seems like you'd be able to export the version/build etc. and wrap it into a Ruby class getter method.

**Comment by DanRathbun** [comment]
Jim Foltz reminded of an ol' thread in the forum to display the internal CEF flags page.

https://forums.sketchup.com/t/su17-combobox-htmldialog-bug/34741/15
... where John Boundy posted this snippet ...
```ruby
wd = UI::HtmlDialog.new(
{
  :dialog_title => "ChromeEmbeddedFramework",
  :style => UI::HtmlDialog::STYLE_DIALOG
})
wd.set_url('chrome://flags/')
wd.show
```
... and following this, MaxB posted an image.

The image is likely from `17.0 M0` ... but anyway, ... the idea is that a **class method** would return a hash of values like the following ... 
```ruby
UI::HtmlDialog::chrome_versioning
#=>
{ "CEF" => "3.2743.1422.g976502e",
  "Chromium" => "52.0.2743.24",
  "WebKit" => "537.36",
  "JavaScript" => "5.2.361.13"
}
```
We'd only likely need these first 4 values in order to make decisions based upon bug reports in official trackers elsewhere.

Since there is no way to “duck-type” how the browser dialog classes deal with JS or HTML, we have to rely upon outside sources (the Chromium project, etc.)

**Comment by DanRathbun** [comment]
> @thomthom : Why do you want to access this from Ruby?

[This was the question on HTTP Basic Authentication](https://forums.sketchup.com/t/htmldialog-make-a-get-request-with-authentication-header/70220/4?u=danrathbun) that prompted me asking and starting this thread.

If he checked Chrome docs and found it supported URI embedded credentials up until a certain version, then if at the simplest, the API docs for `UI::HtmlDialog` (or even the API release notes) had some mention of a versioning, a person could make a decision.

----

Now, this a poor example yes, because doing so is deprecated and browsers are dropping support (and I gave a better authentication example in that thread anyway.) But it is an example of needing to know ahead of time if some feature is supported or not.

This one (URI embedded credentials) looks like it was [dropped from Chrome ~2012](https://bugs.chromium.org/p/chromium/issues/detail?id=82250#c7) and from Internet Explorer prior to that.

**Comment by thomthom** [comment]
Logged as SU-40188

**Comment by DanRathbun** [comment]
Release **2021.1** has added the following class constants:
```ruby
UI::HtmlDialog::CEF_VERSION
UI::HtmlDialog::CHROME_VERSION
```

----

#### Chrome Flags page

> _Jim Foltz reminded of an ol' thread in the forum to display the internal CEF flags page._
> 
> _https://forums.sketchup.com/t/su17-combobox-htmldialog-bug/34741/15_
> ... _where John Boundy posted this snippet_ ...
> 
> ```ruby
> wd = UI::HtmlDialog.new(
> {
>   :dialog_title => "ChromeEmbeddedFramework",
>   :style => UI::HtmlDialog::STYLE_DIALOG
> })
> wd.set_url('chrome://flags/')
> wd.show
> ```

**UPDATE** It appears that the 2021.1 HtmlDialog using CEF 88 **no longer** will display the Chrome flags page when given the `"chrome://flags/"` URL.

**We will need to use `"chrome://version/"` as the URL.** (It displays the same page.)

----

#### WebKit Version

However, (as mentioned by Thomas,) the User Agent string does have the WebKit version embedded within it.
So if we absolutely think we need it, we can get it like so:
```javascript
sketchup.webkit_version(navigator.userAgent.split('AppleWebKit/')[1].split(' ')[0]);
```

... where on the Ruby-side we have ...
```ruby
dialog.add_action_callback("webkit_version") { |_unused, version|
  WEBKIT_VERSION = version
}
```

----

#### JavaScript Version

After doing some research it becomes evident that the Javascript version is problematic and varies from browser to browser, by company and project. Looking at CEF's JavaScript version, we can see it tracks along with the Chromium version. So it is an internal project version for Chromium's scripting engine.

In the wider world, a global JS version number was dropped from use in 2011 (with the last number used being "1.8.5",) as it made not much sense, because individual browser projects implemented JS features at different times and releases that were not synchronized with the "global JS version" nor with ECMA JS editions. The implementations often added small partial ECMA edition support, ... ie, these feature updates being unique to each project in what they added.

**What a coder really wants to know is what ECMAScript edition features does the current browser scripting engine support.
It is widely promoted to always favor feature sniffing / detection over conditional statements that compare hard version numbers.**

----

@thomthom, **Given the above, I believe this issue is satisfied and be closed.**
