### ISSUE TITLE
incorrect extension cursor hotspot on Windows Sketchup 2024

### ISSUE THREAD

**Issue by slbaumgartner** [SketchUp/api-issue-tracker#982]
As of SketchUp 2024 (24.0.553), the cursor hotspot in one of my extensions ([Angular Dimension 2, at sketchUcation](https://sketchucation.com/plugin/1879-angular_dimension_5)) is no longer being set correctly on Windows 10 or 11.  The extension code sets it to 0, 31, which should be the **lower** left corner, but the hotspot on the GUI acts like it is at 0,0, the **upper** left corner.  It works correctly on all prior versions of SketchUp on Windows and also on macOS.  I tried changing the hotspot coordinates in the code, and the changes are ignored.  I suspect this resulted from some change in how SVG is handled, likely interacting with something about the specific svg files for this extension, created using InkScape, but I have been unable to find a fix.

**Comment by slbaumgartner** [comment]
Here is a zip of a minimal Tool to demonstrate the issue.

[SLB_Cursor_Demo.zip](https://github.com/user-attachments/files/15788766/SLB_Cursor_Demo.zip)

**Comment by slbaumgartner** [comment]
Ack! I mistakenly marked this closed and don't know how to reopen it!

**Comment by slbaumgartner** [comment]
I subsequently redrew the cursor svg using Affinity Designer, and the new svg does not have the problem.

**Comment by thomthom** [comment]
> Here is a zip of a minimal Tool to demonstrate the issue.
> 
> [SLB_Cursor_Demo.zip](https://github.com/user-attachments/files/15788766/SLB_Cursor_Demo.zip)

The icons were not drawn to a 32x32 size, not even square:
![image](https://github.com/SketchUp/api-issue-tracker/assets/192418/017c4ee4-9547-4f38-8165-c91a77409350)

To be sure things work as expected, set the drawing area of your SVG icons to 32x32 and 24x24. Any other sizes can yield unpredictable results.

> I subsequently redrew the cursor svg using Affinity Designer, and the new svg does not have the problem.
Thank you for the heads up.
