### ISSUE TITLE
fetch request randomly hangs in UI::HTMLDialog

### ISSUE THREAD

**Issue by tontan2545** [SketchUp/api-issue-tracker#986]
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version: 24.0.483
2. OS Platform: macOS 14.4.1 (23E224)

Describe briefly what you are doing and what is happening.

I'm doing a SketchUp Plugin for a companion app of my company. Essentially I'm building a new website and I use Sketchup's `UI::HTMLDialog` to access that webpage so I could use some internal sketchup specific function while still using web technologies. It works just fine when developing in my local browser, however when I'm testing on SketchUp's `HTMLDialog`, some requests seems to hangs and never send response back. This behaviour spans on ALL html fetch request sent from the dialog ranging from request sending to firebase auth, our own server, and other APIs. It seems like this is a HTMLDialog-specific issue since I could not reproduce this issue on any type of browser. I would like to have guidance on what should be done to fix this issue or even diagnosing the root cause of this. What I've currently done to mitigate the issue is just to do a manual timeout and retry if any request hangs, but this should not be the case.

Describe what the expected result is.

```ruby
def self.create_dialog
      options = {
        :dialog_title => "<Company>",
        :preferences_key => "<company>",
        :max_width => 3840,
        :max_height => 2160,
        :width => 2840,
        :height => 1600,
      }
      dialog = UI::HtmlDialog.new(options)
      dialog.set_url("http://localhost:3000")
      dialog.center
      dialog
    end

    def self.show_dialog
      @dialog = self.create_dialog
      @dialog.add_action_callback("captureSceneImage") do
        filename = File.join(Sketchup.temp_dir, "screenshot-#{DateTime.now.strftime('%d-%m-%y-%H-%M-%S')}.png")
        model = Sketchup.active_model
        view = model.active_view
        view.write_image(filename, 1280, 720, true, 0)
        base64_image = Base64.strict_encode64(open(filename).read)
        @dialog.execute_script("updateSceneImage(\"data:image/png;base64,#{base64_image}\");")
      end
      @dialog.add_action_callback("openURL") do |_, url|
        UI.openURL(url)
      end

      @dialog.show
    end
```

Attach any relevant files.
- Request hangs with sketchup html dialog is trying to send request to google identitykit
<img width="903" alt="Screenshot 2567-07-01 at 18 42 44" src="https://github.com/SketchUp/api-issue-tracker/assets/43312669/ae4792fb-2977-464c-aee5-f2a075353d77">
- Request hangs with trying to do fetch request to our server
<img width="797" alt="set-room-id-hang" src="https://github.com/SketchUp/api-issue-tracker/assets/43312669/41cf2a16-a6ae-41a7-844b-a4775f437867">

**Comment by tontan2545** [comment]
A little more information on the request, seems like it's stalled for a few seconds and never finishes the request
<img width="763" alt="image" src="https://github.com/SketchUp/api-issue-tracker/assets/43312669/f5e95c0d-acf6-4919-a40e-d4aa9858a568">

**Comment by MSP-Greg** [comment]
< sketchup html dialog is trying to send request to google identitykit

CORS issue?  I experimented with some CORS issues a while ago, don't recall much.  I think SU 2024 updated the version of CEF it's bundled with, and CORS handling was stricter than the previous CEF version.  Or, others also had issues.

**Comment by tontan2545** [comment]
@MSP-Greg, if its a CORS issue then it would failed in preflight request am I right? Or connection stalling is also a sign of CORS issue as well

**Comment by MSP-Greg** [comment]
@tontan2545

IIRC, some requests generate a pre-flight, some may not.  MDN may have some info on it.

https://forums.sketchup.com/t/cors-request-no-longer-working-in-plugin-with-su2024-websecurity-change/268712 may have some info, I recall other 'conversations', not sure where they occurred.

**Comment by tontan2545** [comment]
@MSP-Greg 
Saw the form, I guess it seems to be a CORS issue. Not exactly sure why that is but according to the form it's fixed in the SketchUp latest build. Updated the app and everything works now. Idk why that is but that's software dev in a nutshell I guess lmao. Thanks for the advice!

**Comment by johnscollins98** [comment]
My team and our users have noticed a very similar issue on our side that I'm still experiencing in Sketchup 2024.0.533 on Windows.

Raised issue #991 to cover it.
