### ISSUE TITLE
Sketchup::Model.import Argument show_summary = false Fails

### ISSUE THREAD

**Issue by 3dmod** [SketchUp/api-issue-tracker#987]
When using the Sketchup::Model.import method with the show_summary argument equal to false the method does not import and fails.

Same method works with show_summary = true or show_summary argument is not given.

I see this in macOS version 24.0.483.

**Comment by MSP-Greg** [comment]
Never used the method, but the [docs](https://msp-greg.github.io/su/Sketchup/Model.html#import-instance_method) for `Sketchup::Model.import` show different methods signatures for different versions of SketchUp...

**Comment by 3dmod** [comment]
You right, thank you
