### ISSUE TITLE
[SU2024] constant TRUE/FLASE was removed, without any "Breaking Change" warnings in Ruby API Docs

### ISSUE THREAD

**Issue by zfjoy520** [SketchUp/api-issue-tracker#992]
# [SU2024] constant TRUE/FLASE was removed, without any "Breaking Change" warning in Ruby API Docs

# Bug Reports
1. SketchUp 2024
2. OS Platform: MAC OS 13.5

## In SU2022, 2023 or less, TRUE / FALSE constants were built in Ruby API(maybe), but was removed in SU2024, and no "Breaking Change" warnings in Ruby API Docs.

# Compare Test images as follows:
> Only keep default 3 extensions: su_dynamiccomponents、su_sandbox、su_trimble_connect

## SU 2022
![QQ_1722224202841](https://github.com/user-attachments/assets/1b882ac2-c55d-4edf-be59-ba729bcd2c8a)

## SU 2023
![QQ_1722224214531](https://github.com/user-attachments/assets/6832a3da-7067-4fe2-be04-3ac4e958d1bb)

## SU 2024
![QQ_1722224228393](https://github.com/user-attachments/assets/802f9539-893d-41d8-95e2-a894086d2e59)

## Notice that, SU2024 removed builtin su_trimble_connect, so I test again in SU2023 with all extensions disabled, the TRUE constant was predefined too, the image as follows:

![QQ_1722224573795](https://github.com/user-attachments/assets/d7844b98-7096-4bb4-a36b-7681f904a8d3)

**Comment by MSP-Greg** [comment]
The Ruby global constants `TRUE`, `FALSE` and `NIL` were marked as deprecated in Ruby 2.4.  These were part of Ruby, not the SketchUp Ruby API.

```
C:\>ruby -ve "puts TRUE"
ruby 2.4.10p364 (2020-03-31 revision 67879) [x64-mingw32]
-e:1: warning: constant ::TRUE is deprecated
true
```

They were removed in Ruby 3.0.  Generally, SketchUp does not list Ruby changes in their releases note or API docs.

**Comment by zfjoy520** [comment]
This is my mistake, I made a joke, I will close this issue.
Thank you

**Comment by zfjoy520** [comment]
This is my mistake, I made a joke, I will close this issue.
Thank you.
